const COPY = {
  en: {
    eyebrow: 'Payroll configuration',
    title: 'Payroll foundation studio',
    description:
      'Version legal entities, payroll groups, calendars, currencies, rounding and effective periods. This studio does not calculate pay or initiate settlement.',
    create: 'New foundation',
    edit: 'Edit draft',
    save: 'Save draft',
    saving: 'Saving…',
    cancel: 'Cancel',
    simulate: 'Run simulation',
    publish: 'Publish version',
    reverse: 'Reverse publication',
    refresh: 'Refresh',
    retry: 'Try again',
    checkReceipt: 'Check receipt',
    reconcile: 'Reconcile result',
    configurations: 'Foundations',
    configurationCount: '{{count}} configured',
    emptyTitle: 'No payroll foundation is visible',
    emptyDescription: 'Create a draft if the server grants configuration-author access.',
    permissionTitle: 'Actions are server controlled',
    permissionDescription:
      'Unavailable actions are not inferred from browser roles. The payroll owner projection decides edit, simulation, publish, reversal and reconciliation access.',
    partialTitle: 'Some owner dependencies are unavailable',
    partialDescription:
      'Visible foundation data is retained. Refresh before making a high-impact decision.',
    staleTitle: 'Dependency evidence is stale',
    staleDescription: 'Publishing is blocked until the owner reports current dependency evidence.',
    unavailableTitle: 'Owner evidence is unavailable',
    unavailableDescription: 'This configuration remains read-only until owner evidence recovers.',
    updated: 'Last owner refresh',
    notReported: 'Not reported',
    details: 'Foundation detail',
    version: 'Version',
    lifecycle: 'Lifecycle',
    freshness: 'Freshness',
    legalEntity: 'Legal entity',
    payrollGroup: 'Payroll group',
    calendar: 'Pay calendar',
    currency: 'Currency and rounding',
    effectivePeriod: 'Effective period',
    dependencies: 'Dependency pins',
    countryPack: 'Country pack reference',
    supportedCurrencies: 'Supported currencies',
    settlementCurrency: 'Settlement currency',
    cadence: 'Cadence',
    periods: 'Calendar periods',
    openEnded: 'Open-ended',
    noDependencies: 'No dependency pins were supplied.',
    simulation: 'Simulation evidence',
    simulationNotRun: 'No simulation exists for this version.',
    simulationPassed: 'Simulation passed',
    simulationFailed: 'Simulation returned findings',
    simulationStale: 'Simulation belongs to another version.',
    findings: 'Findings',
    versions: 'Version history',
    versionsUnavailable: 'Version history is temporarily unavailable.',
    authorPublisher: 'Author / publisher separation',
    authorPublisherDescription:
      'Publish is shown only when the server projection grants it. The server rejects publication by the version author.',
    publishReviewTitle: 'Review publication impact',
    publishReviewDescription:
      'Publishing makes this simulated foundation effective for its configured period. Review the version, dependency freshness and simulation receipt before continuing.',
    publishConfirm: 'Publish simulated version',
    reverseReviewTitle: 'Review publication reversal',
    reverseReviewDescription:
      'Reversal is a separate audited command. The published version remains effective unless the owner receipt confirms success.',
    reverseConfirm: 'Submit reversal',
    publishBlocked: 'Publication requirements',
    commandSucceeded: 'Owner receipt confirms the command succeeded.',
    commandPending: 'The owner accepted the command. Check the same receipt for a durable result.',
    resultUnknownTitle: 'Command result is unknown',
    resultUnknownDescription:
      'Do not submit a replacement command. Look up or reconcile this same durable receipt.',
    reversalFailedTitle: 'Publication reversal failed',
    reversalFailedDescription:
      'The publication remains in effect. Review the receipt and owner evidence before retrying.',
    conflictTitle: 'A newer version exists',
    conflictDescription:
      'Your draft is preserved. Refresh and compare it with the latest owner version.',
    deniedTitle: 'The server denied this action',
    deniedDescription: 'Nothing changed. Request the required role, purpose or legal-entity scope.',
    commandFailedTitle: 'The command was not confirmed',
    commandFailedDescription: 'Your draft is preserved and no success is assumed.',
    receipt: 'Durable receipt',
    receiptId: 'Command ID',
    commandStatus: 'Status',
    editorCreate: 'Create payroll foundation draft',
    editorUpdate: 'Edit payroll foundation draft',
    editorDescription:
      'All values are tenant configuration. No company, statutory or payment rule is embedded.',
    entityId: 'Legal entity ID',
    entityCode: 'Legal entity code',
    entityName: 'Legal entity display name',
    packId: 'Country pack ID',
    packVersion: 'Country pack version',
    packDigest: 'Country pack SHA-256',
    groupId: 'Payroll group ID',
    groupCode: 'Payroll group code',
    currenciesHelp: 'ISO codes, comma separated',
    calendarId: 'Calendar ID',
    effectiveFrom: 'Effective from',
    effectiveTo: 'Effective to (optional)',
    periodCode: 'Period code',
    periodStart: 'Period start',
    periodEnd: 'Period end',
    paymentDate: 'Payment date',
    addPeriod: 'Add period',
    removePeriod: 'Remove period',
    roundingCurrency: 'Currency',
    roundingScale: 'Decimal scale',
    roundingMode: 'Rounding mode',
    roundingIncrement: 'Exact decimal increment',
    addRounding: 'Add rounding policy',
    removeRounding: 'Remove rounding policy',
    invalidDraft: 'Complete the highlighted foundation contract.',
    versionLabel: 'v{{version}}',
    selectConfiguration: 'Select {{name}}',
    statusLabel: '{{status}}',
  },
  ko: {
    eyebrow: '급여 설정',
    title: '급여 기반 스튜디오',
    description:
      '법인, 급여군, 달력, 통화, 반올림, 유효기간을 버전으로 관리합니다. 급여 계산이나 지급 실행은 이 화면의 범위가 아닙니다.',
    create: '새 기반 만들기',
    edit: '초안 편집',
    save: '초안 저장',
    saving: '저장 중…',
    cancel: '취소',
    simulate: '시뮬레이션 실행',
    publish: '버전 게시',
    reverse: '게시 되돌리기',
    refresh: '새로고침',
    retry: '다시 시도',
    checkReceipt: '영수증 확인',
    reconcile: '결과 대사',
    configurations: '급여 기반',
    configurationCount: '{{count}}개 설정',
    emptyTitle: '표시할 급여 기반이 없습니다',
    emptyDescription: '서버가 설정 작성 권한을 부여한 경우 초안을 만들 수 있습니다.',
    permissionTitle: '작업 권한은 서버가 결정합니다',
    permissionDescription:
      '브라우저 역할로 권한을 추론하지 않습니다. 급여 소유자 projection이 편집, 시뮬레이션, 게시, 되돌리기, 대사 권한을 결정합니다.',
    partialTitle: '일부 소유자 의존성을 사용할 수 없습니다',
    partialDescription: '표시된 데이터는 유지됩니다. 중요한 결정을 하기 전에 새로고침하세요.',
    staleTitle: '의존성 증거가 오래되었습니다',
    staleDescription: '소유자가 최신 의존성 증거를 제공할 때까지 게시할 수 없습니다.',
    unavailableTitle: '소유자 증거를 사용할 수 없습니다',
    unavailableDescription: '소유자 증거가 복구될 때까지 이 설정은 읽기 전용입니다.',
    updated: '마지막 소유자 갱신',
    notReported: '보고되지 않음',
    details: '기반 상세',
    version: '버전',
    lifecycle: '수명주기',
    freshness: '신선도',
    legalEntity: '법인',
    payrollGroup: '급여군',
    calendar: '급여 달력',
    currency: '통화 및 반올림',
    effectivePeriod: '유효기간',
    dependencies: '의존성 고정',
    countryPack: '국가 정책 팩 참조',
    supportedCurrencies: '지원 통화',
    settlementCurrency: '정산 기준 통화',
    cadence: '주기',
    periods: '달력 기간',
    openEnded: '종료일 없음',
    noDependencies: '제공된 의존성 고정이 없습니다.',
    simulation: '시뮬레이션 증거',
    simulationNotRun: '이 버전에 대한 시뮬레이션이 없습니다.',
    simulationPassed: '시뮬레이션 통과',
    simulationFailed: '시뮬레이션에서 발견 항목이 있습니다',
    simulationStale: '다른 버전의 시뮬레이션입니다.',
    findings: '발견 항목',
    versions: '버전 이력',
    versionsUnavailable: '버전 이력을 일시적으로 사용할 수 없습니다.',
    authorPublisher: '작성자 / 게시자 분리',
    authorPublisherDescription:
      '서버 projection이 허용한 경우에만 게시 작업을 표시합니다. 서버는 해당 버전 작성자의 게시를 거부합니다.',
    publishReviewTitle: '게시 영향 검토',
    publishReviewDescription:
      '게시하면 시뮬레이션된 기반이 설정된 유효기간에 적용됩니다. 계속하기 전에 버전, 의존성 신선도, 시뮬레이션 영수증을 확인하세요.',
    publishConfirm: '시뮬레이션 버전 게시',
    reverseReviewTitle: '게시 되돌리기 검토',
    reverseReviewDescription:
      '되돌리기는 별도의 감사 대상 명령입니다. 소유자 영수증이 성공을 확인할 때까지 게시 버전은 계속 유효합니다.',
    reverseConfirm: '되돌리기 제출',
    publishBlocked: '게시 요구사항',
    commandSucceeded: '소유자 영수증이 작업 성공을 확인했습니다.',
    commandPending: '소유자가 작업을 접수했습니다. 같은 영수증으로 최종 결과를 확인하세요.',
    resultUnknownTitle: '작업 결과를 알 수 없습니다',
    resultUnknownDescription:
      '새 작업을 보내지 마세요. 동일한 영구 영수증을 조회하거나 대사하세요.',
    reversalFailedTitle: '게시 되돌리기에 실패했습니다',
    reversalFailedDescription:
      '게시 상태는 유지됩니다. 다시 시도하기 전에 영수증과 소유자 증거를 확인하세요.',
    conflictTitle: '더 최신 버전이 있습니다',
    conflictDescription:
      '작성 중인 초안은 보존됩니다. 새로고침한 뒤 최신 소유자 버전과 비교하세요.',
    deniedTitle: '서버가 이 작업을 거부했습니다',
    deniedDescription: '변경 사항이 없습니다. 필요한 역할, 목적 또는 법인 범위를 요청하세요.',
    commandFailedTitle: '작업이 확인되지 않았습니다',
    commandFailedDescription: '초안은 보존되며 성공으로 간주하지 않습니다.',
    receipt: '영구 영수증',
    receiptId: '명령 ID',
    commandStatus: '상태',
    editorCreate: '급여 기반 초안 만들기',
    editorUpdate: '급여 기반 초안 편집',
    editorDescription:
      '모든 값은 tenant 설정입니다. 회사, 법정 수치, 지급 규칙을 코드에 내장하지 않습니다.',
    entityId: '법인 ID',
    entityCode: '법인 코드',
    entityName: '법인 표시 이름',
    packId: '국가 정책 팩 ID',
    packVersion: '국가 정책 팩 버전',
    packDigest: '국가 정책 팩 SHA-256',
    groupId: '급여군 ID',
    groupCode: '급여군 코드',
    currenciesHelp: 'ISO 코드를 쉼표로 구분',
    calendarId: '달력 ID',
    effectiveFrom: '유효 시작일',
    effectiveTo: '유효 종료일(선택)',
    periodCode: '기간 코드',
    periodStart: '기간 시작일',
    periodEnd: '기간 종료일',
    paymentDate: '지급 예정일',
    addPeriod: '기간 추가',
    removePeriod: '기간 삭제',
    roundingCurrency: '통화',
    roundingScale: '소수 자릿수',
    roundingMode: '반올림 방식',
    roundingIncrement: '정확한 십진 증가 단위',
    addRounding: '반올림 정책 추가',
    removeRounding: '반올림 정책 삭제',
    invalidDraft: '급여 기반 계약의 필수 항목을 확인하세요.',
    versionLabel: 'v{{version}}',
    selectConfiguration: '{{name}} 선택',
    statusLabel: '{{status}}',
  },
} as const;

export type PayrollFoundationCopy = (typeof COPY)[keyof typeof COPY];

export function getPayrollFoundationCopy(...languages: Array<string | null | undefined>) {
  return languages.some((language) => {
    if (!language) return false;
    try {
      return new Intl.Locale(language).language === 'ko';
    } catch {
      return false;
    }
  })
    ? COPY.ko
    : COPY.en;
}

export function foundationCopyValue(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replace(`{{${key}}}`, String(value)),
    template
  );
}
