export function secureAttachmentCopy(language: 'ko' | 'en') {
  if (language === 'ko') {
    return {
      add: '보안 첨부 추가',
      title: '검증된 첨부 트레이',
      description: '파일은 AV·DLP·파서·OCR 검사를 통과한 뒤에만 AI에 전달됩니다.',
      remove: '첨부 영구 삭제',
      removeAll: '전체 첨부 영구 삭제',
      retry: '다시 시도',
      dismiss: '알림 닫기',
      uploading: '보안 저장소 업로드 중',
      uploadFailed: '첨부 업로드에 실패했습니다.',
      deleting: '삭제 요청 처리 중',
      deleteFailed: '첨부 삭제 요청에 실패했습니다.',
      waiting: '모든 첨부의 보안 검사가 끝나면 전송할 수 있습니다.',
      ready: '사용 가능',
      citations: (count: number) => `인용 ${count}개`,
      retention: '자동 삭제',
      errors: {
        COUNT_EXCEEDED: '첨부는 한 대화에 최대 6개까지 추가할 수 있습니다.',
        EMPTY_FILE: '비어 있는 파일은 첨부할 수 없습니다.',
        SIZE_EXCEEDED: '파일당 최대 크기는 100MB입니다.',
        TYPE_BLOCKED: 'PDF, Office 문서, PNG/JPEG, TXT/CSV 파일만 첨부할 수 있습니다.',
      },
      states: {
        UPLOADING: '업로드 중',
        SCANNING: '보안 검사 중',
        READY: '검증 완료',
        PARTIAL: '일부 검사 지연',
        BLOCKED: '정책 차단',
        FAILED: '처리 실패',
        CANCELLED: '취소됨',
        DELETION_PENDING: '영구 삭제 중',
        DELETED: '삭제 완료',
      },
      stages: {
        UPLOAD: '업로드',
        AV: '악성코드',
        DLP: 'DLP',
        PARSER: '문서 파서',
        OCR: 'OCR',
        INDEX: '인덱스',
      },
    } as const;
  }
  return {
    add: 'Add secure attachment',
    title: 'Verified attachment tray',
    description: 'Files reach AI only after AV, DLP, parser, and OCR checks.',
    remove: 'Permanently delete attachment',
    removeAll: 'Permanently delete all',
    retry: 'Retry',
    dismiss: 'Dismiss alert',
    uploading: 'Uploading to secure storage',
    uploadFailed: 'Attachment upload failed.',
    deleting: 'Deletion is in progress',
    deleteFailed: 'Attachment deletion request failed.',
    waiting: 'You can send after every attachment finishes security inspection.',
    ready: 'Ready',
    citations: (count: number) => `${count} citations`,
    retention: 'Auto-delete',
    errors: {
      COUNT_EXCEEDED: 'You can attach up to six files per conversation.',
      EMPTY_FILE: 'Empty files cannot be attached.',
      SIZE_EXCEEDED: 'Each file can be up to 100 MB.',
      TYPE_BLOCKED: 'Attach PDF, Office, PNG/JPEG, TXT, or CSV files.',
    },
    states: {
      UPLOADING: 'Uploading',
      SCANNING: 'Security scan',
      READY: 'Verified',
      PARTIAL: 'Partially delayed',
      BLOCKED: 'Blocked',
      FAILED: 'Failed',
      CANCELLED: 'Cancelled',
      DELETION_PENDING: 'Deleting',
      DELETED: 'Deleted',
    },
    stages: {
      UPLOAD: 'Upload',
      AV: 'Malware',
      DLP: 'DLP',
      PARSER: 'Parser',
      OCR: 'OCR',
      INDEX: 'Index',
    },
  } as const;
}
