export function secureAttachmentCopy(language: 'ko' | 'en') {
  if (language === 'ko') {
    return {
      add: '보안 첨부 추가',
      title: '검증된 첨부 트레이',
      description: '파일은 AV·DLP·파서·OCR 검사를 통과한 뒤에만 AI에 전달됩니다.',
      pipelineTitle: '보안 검사 및 색인 파이프라인',
      pipelineDescription:
        '서버가 반환한 검사 증거만 표시하며, 필요한 단계가 끝난 파일만 답변 근거로 사용합니다.',
      pipelineEvidence: (ready: number, total: number, citations: number) =>
        `${total}건 중 ${ready}건 검증 완료 · 인용 근거 ${citations}건`,
      pipelineStageReady: '검증',
      pipelineStageAttention: '확인 필요',
      governedBoundary: '암호화된 메타데이터 · 테넌트 격리 증거',
      governanceTitle: '첨부 데이터 보안 및 거버넌스',
      governanceEvidence: 'SHA-256 원본 바인딩 · 테넌트/사용자 범위 격리 · 파일별 보존 기한',
      providerDisclosure:
        'KMS 키 ID, AV 엔진 버전, 외부 학습 금지 증명은 현재 사용자 API에서 공개되지 않습니다.',
      providerLimits: (limit: string, formats: string) =>
        `서버 허용 범위: 파일당 ${limit} · ${formats}`,
      fileType: '형식',
      remove: '첨부 영구 삭제',
      removeAll: '전체 첨부 영구 삭제',
      detachAll: '전체 첨부 해제',
      inspectionLog: '보안 검사 감사 로그',
      maskingHistory: '마스킹 내역',
      ocrViewer: 'OCR 뷰어',
      auditReport: '서명 보안 검증 리포트 발급',
      advancedTitle: '첨부 보안 증거와 관리',
      advancedDescription:
        '실제 계약이 있는 작업만 실행되며 나머지는 지원 상태를 그대로 표시합니다.',
      unavailableCapability: '서버 기능 계약이 배포되지 않았습니다.',
      actualEvidence: '첨부 서비스가 반환한 실제 검사 증거를 표시합니다.',
      evidenceClose: '증거 닫기',
      evidenceLoading: '보안 증거를 불러오는 중입니다.',
      evidenceError: '보안 증거를 확인하지 못했습니다. 다시 시도해 주세요.',
      unsignedAuditNotice: '현재 서버 응답의 증거를 내보내며 서버 서명 인증서는 아닙니다.',
      retry: '다시 시도',
      dismiss: '알림 닫기',
      uploading: '보안 저장소 업로드 중',
      uploadFailed: '첨부 업로드에 실패했습니다.',
      deleting: '삭제 요청 처리 중',
      deleteFailed: '첨부 삭제 요청에 실패했습니다.',
      waiting: '모든 첨부의 보안 검사가 끝나면 전송할 수 있습니다.',
      ready: '사용 가능',
      citations: (count: number) => `인용 ${count}개`,
      retention: '자동 삭제',
      errors: {
        COUNT_EXCEEDED: '첨부는 한 대화에 최대 6개까지 추가할 수 있습니다.',
        EMPTY_FILE: '비어 있는 파일은 첨부할 수 없습니다.',
        SIZE_EXCEEDED: '파일당 최대 크기는 100MB입니다.',
        TYPE_BLOCKED: 'PDF, Office 문서, PNG/JPEG, TXT/CSV 파일만 첨부할 수 있습니다.',
      },
      states: {
        UPLOADING: '업로드 중',
        SCANNING: '보안 검사 중',
        READY: '검증 완료',
        PARTIAL: '일부 검사 지연',
        BLOCKED: '정책 차단',
        FAILED: '처리 실패',
        CANCELLED: '취소됨',
        DELETION_PENDING: '영구 삭제 중',
        DELETED: '삭제 완료',
      },
      stages: {
        UPLOAD: '업로드',
        AV: '악성코드',
        DLP: 'DLP',
        PARSER: '문서 파서',
        OCR: 'OCR',
        INDEX: '인덱스',
      },
    } as const;
  }
  return {
    add: 'Add secure attachment',
    title: 'Verified attachment tray',
    description: 'Files reach AI only after AV, DLP, parser, and OCR checks.',
    pipelineTitle: 'Security inspection and indexing pipeline',
    pipelineDescription:
      'Only server-returned inspection evidence is shown, and only files that finish required stages can ground an answer.',
    pipelineEvidence: (ready: number, total: number, citations: number) =>
      `${ready} of ${total} verified · ${citations} citation records`,
    pipelineStageReady: 'Verified',
    pipelineStageAttention: 'Needs attention',
    governedBoundary: 'Encrypted metadata · tenant-isolated evidence',
    governanceTitle: 'Attachment data security and governance',
    governanceEvidence: 'SHA-256 source binding · tenant/user isolation · per-file retention',
    providerDisclosure:
      'KMS key ID, AV engine version, and external-training attestation are not disclosed by the current user API.',
    providerLimits: (limit: string, formats: string) =>
      `Server allowance: ${limit} per file · ${formats}`,
    fileType: 'Type',
    remove: 'Permanently delete attachment',
    removeAll: 'Permanently delete all',
    detachAll: 'Detach all attachments',
    inspectionLog: 'Security inspection audit log',
    maskingHistory: 'Masking history',
    ocrViewer: 'OCR viewer',
    auditReport: 'Issue signed security verification report',
    advancedTitle: 'Attachment security evidence and controls',
    advancedDescription:
      'Only server-backed actions run; other controls show their live support state.',
    unavailableCapability: 'The server capability contract is not deployed.',
    actualEvidence: 'Shows inspection evidence returned by the attachment service.',
    evidenceClose: 'Close evidence',
    evidenceLoading: 'Loading security evidence.',
    evidenceError: 'Security evidence could not be verified. Try again.',
    unsignedAuditNotice:
      'Exports current server-response evidence; this is not a server-signed certificate.',
    retry: 'Retry',
    dismiss: 'Dismiss alert',
    uploading: 'Uploading to secure storage',
    uploadFailed: 'Attachment upload failed.',
    deleting: 'Deletion is in progress',
    deleteFailed: 'Attachment deletion request failed.',
    waiting: 'You can send after every attachment finishes security inspection.',
    ready: 'Ready',
    citations: (count: number) => `${count} citations`,
    retention: 'Auto-delete',
    errors: {
      COUNT_EXCEEDED: 'You can attach up to six files per conversation.',
      EMPTY_FILE: 'Empty files cannot be attached.',
      SIZE_EXCEEDED: 'Each file can be up to 100 MB.',
      TYPE_BLOCKED: 'Attach PDF, Office, PNG/JPEG, TXT, or CSV files.',
    },
    states: {
      UPLOADING: 'Uploading',
      SCANNING: 'Security scan',
      READY: 'Verified',
      PARTIAL: 'Partially delayed',
      BLOCKED: 'Blocked',
      FAILED: 'Failed',
      CANCELLED: 'Cancelled',
      DELETION_PENDING: 'Deleting',
      DELETED: 'Deleted',
    },
    stages: {
      UPLOAD: 'Upload',
      AV: 'Malware',
      DLP: 'DLP',
      PARSER: 'Parser',
      OCR: 'OCR',
      INDEX: 'Index',
    },
  } as const;
}
