approvedGitRepositories:
  - '**'

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

packageExtensions:
  "@mui/x-internals@*":
    dependencies:
      react-dom: "^19.1.0"
  "storybook@*":
    dependencies:
      react: "^19.1.0"
