enableGlobalCache: true

enableScripts: true

npmMinimalAgeGate: 1440

nodeLinker: node-modules

packageExtensions:
  "@mui/x-internals@*":
    dependencies:
      react-dom: "^19.1.0"
  "storybook@*":
    dependencies:
      react: "^19.1.0"
