import { useTranslation } from 'react-i18next';

function interpolate(value: string, variables?: Record<string, string | number>) {
  return Object.entries(variables ?? {}).reduce(
    (result, [key, replacement]) => result.replaceAll(`{{${key}}}`, String(replacement)),
    value
  );
}

export function useWorkplaceAssistantCopy() {
  const { t } = useTranslation('rooms');
  const copy = {
    userEyebrow: t('workplace.assistant.userEyebrow'),
    userTitle: t('workplace.assistant.userTitle'),
    userDescription: t('workplace.assistant.userDescription'),
    adminEyebrow: t('workplace.assistant.adminEyebrow'),
    adminTitle: t('workplace.assistant.adminTitle'),
    adminDescription: t('workplace.assistant.adminDescription'),
    loading: t('workplace.assistant.loading'),
    loadError: t('workplace.assistant.loadError'),
    commandError: t('workplace.assistant.commandError'),
    offline: t('workplace.assistant.offline'),
    readOnly: t('workplace.assistant.readOnly'),
    privacyTitle: t('workplace.assistant.privacyTitle'),
    privacyNotice: t('workplace.assistant.privacyNotice'),
    noStorage: t('workplace.assistant.noStorage'),
    createTitle: t('workplace.assistant.createTitle'),
    requestText: t('workplace.assistant.requestText'),
    requestTextHint: t('workplace.assistant.requestTextHint'),
    reason: t('workplace.assistant.reason'),
    processingConsent: t('workplace.assistant.processingConsent'),
    feedbackConsent: t('workplace.assistant.feedbackConsent'),
    addItem: t('workplace.assistant.addItem'),
    removeItem: t('workplace.assistant.removeItem'),
    requirement: t('workplace.assistant.requirement'),
    beneficiaryId: t('workplace.assistant.beneficiaryId'),
    beneficiaryName: t('workplace.assistant.beneficiaryName'),
    beneficiary: t('workplace.assistant.beneficiary'),
    beneficiaryTarget: t('workplace.assistant.beneficiaryTarget'),
    beneficiaryTargets: {
      SELF: t('workplace.assistant.beneficiaryTargets.SELF'),
      DELEGATE: t('workplace.assistant.beneficiaryTargets.DELEGATE'),
      TEAM: t('workplace.assistant.beneficiaryTargets.TEAM'),
    },
    beneficiarySelf: t('workplace.assistant.beneficiarySelf'),
    beneficiaryDelegate: t('workplace.assistant.beneficiaryDelegate'),
    beneficiaryLoading: t('workplace.assistant.beneficiaryLoading'),
    beneficiaryDenied: t('workplace.assistant.beneficiaryDenied'),
    beneficiaryUnavailable: t('workplace.assistant.beneficiaryUnavailable'),
    beneficiaryStale: t('workplace.assistant.beneficiaryStale'),
    beneficiaryTargetUnavailable: t('workplace.assistant.beneficiaryTargetUnavailable'),
    retryBeneficiaries: t('workplace.assistant.retryBeneficiaries'),
    resourceType: t('workplace.assistant.resourceType'),
    site: t('workplace.assistant.site'),
    floor: t('workplace.assistant.floor'),
    anySite: t('workplace.assistant.anySite'),
    anyFloor: t('workplace.assistant.anyFloor'),
    siteTimeZone: t('workplace.assistant.siteTimeZone'),
    browserTimeZone: t('workplace.assistant.browserTimeZone'),
    startsAt: t('workplace.assistant.startsAt'),
    endsAt: t('workplace.assistant.endsAt'),
    purpose: t('workplace.assistant.purpose'),
    features: t('workplace.assistant.features'),
    accessibleOnly: t('workplace.assistant.accessibleOnly'),
    visibleToColleagues: t('workplace.assistant.visibleToColleagues'),
    create: t('workplace.assistant.create'),
    suggestionBoundary: t('workplace.assistant.suggestionBoundary'),
    authorityBoundary: t('workplace.assistant.authorityBoundary'),
    redactedRequest: t('workplace.assistant.redactedRequest'),
    retainedContentDeleted: t('workplace.assistant.retainedContentDeleted'),
    retainedUntil: t('workplace.assistant.retainedUntil'),
    requestState: t('workplace.assistant.requestState'),
    proposalsTitle: t('workplace.assistant.proposalsTitle'),
    proposalsDescription: t('workplace.assistant.proposalsDescription'),
    proposalSelected: t('workplace.assistant.proposalSelected'),
    rationale: t('workplace.assistant.rationale'),
    constraints: t('workplace.assistant.constraints'),
    exclusions: t('workplace.assistant.exclusions'),
    conflicts: t('workplace.assistant.conflicts'),
    alternatives: t('workplace.assistant.alternatives'),
    noAlternatives: t('workplace.assistant.noAlternatives'),
    waitlistEligible: t('workplace.assistant.waitlistEligible'),
    policyResult: t('workplace.assistant.policyResult'),
    unvalidated: t('workplace.assistant.unvalidated'),
    validateReason: t('workplace.assistant.validateReason'),
    holdTtl: t('workplace.assistant.holdTtl'),
    allowAlternatives: t('workplace.assistant.allowAlternatives'),
    validate: t('workplace.assistant.validate'),
    validationTitle: t('workplace.assistant.validationTitle'),
    validationTime: t('workplace.assistant.validationTime'),
    validationValid: t('workplace.assistant.validationValid'),
    validationInvalid: t('workplace.assistant.validationInvalid'),
    confirmReason: t('workplace.assistant.confirmReason'),
    failurePolicy: t('workplace.assistant.failurePolicy'),
    keepSucceeded: t('workplace.assistant.keepSucceeded'),
    compensateAll: t('workplace.assistant.compensateAll'),
    explicitConfirmation: t('workplace.assistant.explicitConfirmation'),
    confirm: t('workplace.assistant.confirm'),
    resultTitle: t('workplace.assistant.resultTitle'),
    resultDescription: t('workplace.assistant.resultDescription'),
    recheck: t('workplace.assistant.recheck'),
    refreshRequest: t('workplace.assistant.refreshRequest'),
    getOnly: t('workplace.assistant.getOnly'),
    batchSummary: t('workplace.assistant.batchSummary'),
    authority: t('workplace.assistant.authority'),
    lastResult: t('workplace.assistant.lastResult'),
    feedbackTitle: t('workplace.assistant.feedbackTitle'),
    feedbackDescription: t('workplace.assistant.feedbackDescription'),
    feedbackRating: t('workplace.assistant.feedbackRating'),
    helpful: t('workplace.assistant.helpful'),
    notHelpful: t('workplace.assistant.notHelpful'),
    feedbackComment: t('workplace.assistant.feedbackComment'),
    feedbackImprove: t('workplace.assistant.feedbackImprove'),
    feedbackConfirmation: t('workplace.assistant.feedbackConfirmation'),
    sendFeedback: t('workplace.assistant.sendFeedback'),
    feedbackSaved: t('workplace.assistant.feedbackSaved'),
    receipt: t('workplace.assistant.receipt'),
    receiptResult: t('workplace.assistant.receiptResult'),
    receiptReplayed: t('workplace.assistant.receiptReplayed'),
    governanceStatus: t('workplace.assistant.governanceStatus'),
    available: t('workplace.assistant.available'),
    paused: t('workplace.assistant.paused'),
    blocked: t('workplace.assistant.blocked'),
    governanceEvidence: t('workplace.assistant.governanceEvidence'),
    tenantOptIn: t('workplace.assistant.tenantOptIn'),
    killSwitch: t('workplace.assistant.killSwitch'),
    providerReference: t('workplace.assistant.providerReference'),
    modelVersion: t('workplace.assistant.modelVersion'),
    promptVersion: t('workplace.assistant.promptVersion'),
    toolVersion: t('workplace.assistant.toolVersion'),
    retentionDays: t('workplace.assistant.retentionDays'),
    feedbackUseEnabled: t('workplace.assistant.feedbackUseEnabled'),
    redactionState: t('workplace.assistant.redactionState'),
    adminConfirmation: t('workplace.assistant.adminConfirmation'),
    updateGovernance: t('workplace.assistant.updateGovernance'),
    managePermissionRequired: t('workplace.assistant.managePermissionRequired'),
    elevationRequired: t('workplace.assistant.elevationRequired'),
    unknownGovernance: t('workplace.assistant.unknownGovernance'),
    refreshGovernance: t('workplace.assistant.refreshGovernance'),
    auditTitle: t('workplace.assistant.auditTitle'),
    auditDescription: t('workplace.assistant.auditDescription'),
    requestFilter: t('workplace.assistant.requestFilter'),
    auditLimit: t('workplace.assistant.auditLimit'),
    applyFilter: t('workplace.assistant.applyFilter'),
    generatedAt: t('workplace.assistant.generatedAt'),
    noAudit: t('workplace.assistant.noAudit'),
    event: t('workplace.assistant.event'),
    actor: t('workplace.assistant.actor'),
    correlation: t('workplace.assistant.correlation'),
    timestamp: t('workplace.assistant.timestamp'),
    metadata: t('workplace.assistant.metadata'),
    yes: t('workplace.assistant.yes'),
    no: t('workplace.assistant.no'),
    unknown: t('workplace.assistant.unknown'),
    resourceTypes: {
      ROOM: t('workplace.assistant.resourceTypes.ROOM'),
      DESK: t('workplace.assistant.resourceTypes.DESK'),
      LOCKER: t('workplace.assistant.resourceTypes.LOCKER'),
      PARKING: t('workplace.assistant.resourceTypes.PARKING'),
      FOCUS_POD: t('workplace.assistant.resourceTypes.FOCUS_POD'),
      PHONE_BOOTH: t('workplace.assistant.resourceTypes.PHONE_BOOTH'),
      EQUIPMENT: t('workplace.assistant.resourceTypes.EQUIPMENT'),
    },
    requestStates: {
      SUGGESTED: t('workplace.assistant.requestStates.SUGGESTED'),
      VALIDATED: t('workplace.assistant.requestStates.VALIDATED'),
      AWAITING_CONFIRMATION: t('workplace.assistant.requestStates.AWAITING_CONFIRMATION'),
      PROCESSING: t('workplace.assistant.requestStates.PROCESSING'),
      SUCCEEDED: t('workplace.assistant.requestStates.SUCCEEDED'),
      PARTIAL: t('workplace.assistant.requestStates.PARTIAL'),
      FAILED: t('workplace.assistant.requestStates.FAILED'),
      RESULT_UNKNOWN: t('workplace.assistant.requestStates.RESULT_UNKNOWN'),
    },
    policyResults: {
      UNVALIDATED: t('workplace.assistant.policyResults.UNVALIDATED'),
      ALLOWED: t('workplace.assistant.policyResults.ALLOWED'),
      DENIED: t('workplace.assistant.policyResults.DENIED'),
      CONFLICT: t('workplace.assistant.policyResults.CONFLICT'),
      UNAVAILABLE: t('workplace.assistant.policyResults.UNAVAILABLE'),
    },
    batchStates: {
      PENDING: t('workplace.assistant.batchStates.PENDING'),
      PROCESSING: t('workplace.assistant.batchStates.PROCESSING'),
      SUCCEEDED: t('workplace.assistant.batchStates.SUCCEEDED'),
      FAILED: t('workplace.assistant.batchStates.FAILED'),
      RESULT_UNKNOWN: t('workplace.assistant.batchStates.RESULT_UNKNOWN'),
      COMPENSATION_PENDING: t('workplace.assistant.batchStates.COMPENSATION_PENDING'),
      COMPENSATED: t('workplace.assistant.batchStates.COMPENSATED'),
      COMPENSATION_FAILED: t('workplace.assistant.batchStates.COMPENSATION_FAILED'),
    },
  };
  return {
    ...copy,
    text: (value: string, variables?: Record<string, string | number>) =>
      interpolate(value, variables),
  };
}
