import type { ProductSurfaceMutationBinding } from './use-product-surface-governed-mutation';

export const DWAION_MUTATION_BINDINGS = {
  'route.dwaion.management.action-policy-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.action-policy-update.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.actions-bootstrap.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.actions-bootstrap.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.agent-create.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.agent-create.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.agent-revision-activate.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.agent-revision-activate.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.agent-revision-create.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.agent-revision-create.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.agent-revision-retire.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.agent-revision-retire.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.agent-revision-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.agent-revision-update.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.domain-retention-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.domain-retention-update.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.evaluation-case-create.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.evaluation-case-create.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.evaluation-create.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.evaluation-create.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.evaluation-lifecycle.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.evaluation-lifecycle.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.evaluation-run.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.evaluation-run.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.gate-configure.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.gate-configure.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.gate-decision.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.gate-decision.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.gate-evidence.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.gate-evidence.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.gate-validation.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.gate-validation.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.gates-bootstrap.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.gates-bootstrap.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.retention-bootstrap.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.retention-bootstrap.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.retention-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.retention-update.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.safety-bootstrap.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.safety-bootstrap.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.safety-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.safety-update.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.source-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.source-update.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.management.sources-bootstrap.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.management',
    routeContractKey: 'route.dwaion.management.sources-bootstrap.action',
    taskKind: 'ADMINISTRATION',
  },
  'route.dwaion.work.action-preview.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.action-preview.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.artifact-autosave.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.artifact-autosave.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.artifact-create.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.artifact-create.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.artifact-export.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.artifact-export.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.artifact-preflight.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.artifact-preflight.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.artifact-publish.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.artifact-publish.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.artifact-version-create.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.artifact-version-create.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.ask-stream.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.ask-stream.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.ask.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.ask.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.conversation-delete.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.conversation-delete.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.conversation-rename.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.conversation-rename.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.feedback.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.feedback.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.memory-create.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.memory-create.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.memory-delete.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.memory-delete.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.memory-preference-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.memory-preference-update.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.memory-runtime-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.memory-runtime-update.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.memory-state.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.memory-state.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.memory-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.memory-update.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.personal-deletion-request.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.personal-deletion-request.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.proposal-analyze.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.proposal-analyze.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.proposal-clear.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.proposal-clear.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.proposal-decision.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.proposal-decision.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.proposal-preferences-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.proposal-preferences-update.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.question-launch-consume.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.question-launch-consume.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.question-launch-create.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.question-launch-create.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.routine-archive.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.routine-archive.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.routine-consent.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.routine-consent.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.routine-create.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.routine-create.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.routine-dry-run.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.routine-dry-run.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.routine-lifecycle.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.routine-lifecycle.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.routine-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.routine-update.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.source-preference-update.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.source-preference-update.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.voice-synthesize.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.voice-synthesize.action',
    taskKind: 'WORK',
  },
  'route.dwaion.work.voice-transcribe.action': {
    productKey: 'dwaion',
    surfaceKey: 'dwaion.work',
    routeContractKey: 'route.dwaion.work.voice-transcribe.action',
    taskKind: 'WORK',
  },
} as const satisfies Record<string, ProductSurfaceMutationBinding>;

export type DwaionMutationRouteContractKey = keyof typeof DWAION_MUTATION_BINDINGS;
