import type { ApproverRoutingCopy } from './approver-routing-workspace';
import type { AuditRecordsCopy } from './audit-records-evidence-workspace';
import type { DeploymentCanaryCopy } from './deployment-canary-workspace';
import type { FormStudioV3Copy } from './form-studio-v3-workspace';
import type { OperationsIncidentCopy } from './operations-incident-recovery-workspace';
import type { PolicyGovernanceCopy } from './policy-governance-workspace';
import type { TemplateLibraryCopy } from './template-library-workspace';
import type { AdminV2StateCopy, AdminV2WorkspaceHeader } from './admin-v2-types';

export const stateCopy: AdminV2StateCopy = {
  loadingTitle: 'Loading workspace',
  loadingDescription: 'Loading current scoped records.',
  emptyTitle: 'No records',
  emptyDescription: 'No records are available in this scope.',
  forbiddenTitle: 'Access denied',
  forbiddenDescription: 'Current authority cannot access this workspace.',
  conflictTitle: 'Version conflict',
  conflictDescription: 'Local input is preserved. Refresh the server version before continuing.',
  conflictAction: 'Refresh version',
  unavailableTitle: 'Service unavailable',
  unavailableDescription: 'The source could not be verified.',
  retryAction: 'Retry source',
  staleTitle: 'Authority stale',
  staleDescription: 'Commands are closed until current authority is verified.',
  staleAction: 'Refresh authority',
};

function header(title: string): AdminV2WorkspaceHeader {
  return {
    eyebrow: 'Approval administration',
    title,
    description: `${title} description`,
    evidenceLabel: 'Governed evidence',
  };
}

export const templateCopy: TemplateLibraryCopy = {
  header: header('Template library'),
  state: stateCopy,
  searchLabel: 'Search templates',
  categoriesLabel: 'Template categories',
  allCategoryLabel: 'All templates',
  catalogTitle: 'Curated templates',
  catalogDescription: 'Reusable governed form packages.',
  detailTitle: 'Template detail',
  detailDescription: 'Select a template to inspect its package.',
  factsTitle: 'Package facts',
  dependenciesTitle: 'Dependencies',
  releaseNotesTitle: 'Release notes',
  featuredLabel: 'Recommended',
  installedLabel: 'Installed',
  importLabel: 'Import package',
  compareLabel: 'Compare versions',
  installLabel: 'Request governed install',
  mobileInstallLabel: 'Install requires desktop review',
  mobileInstallReason: 'Installation is review-only on mobile.',
  installReadyTitle: 'Compatibility verified',
  installReadyDescription: 'The package passed deterministic compatibility checks.',
};

export const formCopy: FormStudioV3Copy = {
  header: header('Form Studio V3'),
  state: stateCopy,
  navigationLabel: 'Form Studio views',
  builderTab: 'Builder',
  rulesTab: 'Data and rules',
  validationTab: 'Validation',
  reviewTab: 'Review',
  structureTitle: 'Form structure',
  structureDescription: 'Pages, sections, and fields.',
  canvasTitle: 'Responsive canvas',
  canvasDescription: 'Authoritative field order and layout.',
  inspectorTitle: 'Field inspector',
  inspectorDescription: 'Data, access, and retention settings.',
  rulesTitle: 'Data and rules lab',
  rulesDescription: 'Deterministic conditions and calculations.',
  validationTitle: 'Validation results',
  validationDescription: 'Resolve blocking results before review.',
  reviewTitle: 'Version review',
  reviewDescription: 'Compare immutable version changes.',
  fieldRequiredLabel: 'Required field',
  fieldOptionalLabel: 'Optional field',
  addFieldLabel: 'Add field',
  duplicateFieldLabel: 'Duplicate field',
  saveDraftLabel: 'Save draft',
  validateLabel: 'Run validation',
  submitReviewLabel: 'Submit governed review',
  mobileReviewLabel: 'Publication review only',
  mobileReviewReason: 'Editing and publication are disabled on mobile.',
  schemaTitle: 'Schema contract',
  schemaDescription: 'Compatibility and integrity facts.',
  deterministicLabel: 'Deterministic validation coverage',
  changeBeforeLabel: 'Published',
  changeAfterLabel: 'Proposed',
  noSelectionLabel: 'Select a field to inspect it.',
};

export const routingCopy: ApproverRoutingCopy = {
  header: header('Approver directory'),
  state: stateCopy,
  navigationLabel: 'Routing workspace views',
  directoryTab: 'Directory',
  simulationTab: 'Simulation',
  exceptionsTab: 'Exceptions',
  directoryTitle: 'Reusable approver groups',
  directoryDescription: 'Purpose-bound directory sources and owners.',
  groupDetailTitle: 'Group detail',
  groupDetailDescription: 'Select a group to inspect resolved membership.',
  membersTitle: 'Resolved members',
  membersDescription: 'Exact users from the current authority revision.',
  simulationTitle: 'Routing simulation',
  simulationDescription: 'Explain the exact route without mutating production.',
  simulationInputsTitle: 'Simulation inputs',
  simulationRouteTitle: 'Resolved route',
  explanationTitle: 'Decision explanation',
  exceptionsTitle: 'Routing exceptions',
  exceptionsDescription: 'Read-only exception evidence and remediation requests.',
  noSelectionLabel: 'Select an approver group.',
  runSimulationLabel: 'Run simulation',
  refreshDirectoryLabel: 'Refresh directory',
  editGroupLabel: 'Edit group draft',
  publishGroupLabel: 'Publish group',
  mobileEditGroupLabel: 'Editing requires desktop review',
  mobilePublishGroupLabel: 'Publication requires desktop review',
  mobileCommandReason: 'Production routing changes are disabled on mobile.',
  retireGroupLabel: 'Retire group',
  mobileRetireLabel: 'Retirement requires desktop review',
  mobileRetireReason: 'Production group changes are disabled on mobile.',
  requestRemediationLabel: 'Request remediation',
  failClosedTitle: 'No candidate fails closed',
  failClosedDescription: 'A missing resolver result never becomes an automatic approval.',
};

export const policyCopy: PolicyGovernanceCopy = {
  header: header('Policy and notification studio'),
  state: stateCopy,
  navigationLabel: 'Policy governance views',
  catalogTab: 'Policies',
  calendarTab: 'Business calendars',
  deliveryTab: 'Delivery preview',
  delegationTab: 'Delegation review',
  catalogTitle: 'Policy catalog',
  catalogDescription: 'Published and proposed policy families.',
  policyDetailTitle: 'Policy detail',
  policyDetailDescription: 'Select a policy to inspect it.',
  impactTitle: 'Impact analysis',
  impactDescription: 'Affected assets and in-flight requests.',
  providersTitle: 'Notification providers',
  providersDescription: 'Current probe truth, never inferred readiness.',
  calendarTitle: 'Business calendars',
  calendarDescription: 'Timezone, holidays, and effective exceptions.',
  simulationTitle: 'SLA simulation',
  simulationDescription: 'Deterministic reminder and escalation timeline.',
  deliveryTitle: 'Localized delivery preview',
  deliveryDescription: 'Safe variables, fallback, and redaction.',
  escalationTitle: 'Escalation timeline',
  escalationDescription: 'Reminder, breach, reassignment, and terminal behavior.',
  delegationTitle: 'Delegation governance',
  delegationDescription: 'Scoped proxy authority with durable evidence.',
  noSelectionLabel: 'Select a policy.',
  editPolicyLabel: 'Edit policy draft',
  runSimulationLabel: 'Run timeline simulation',
  submitReviewLabel: 'Submit publication review',
  mobileReviewLabel: 'Publication requires desktop review',
  mobileReviewReason: 'High-risk publication commands are disabled on mobile.',
  mobileEditLabel: 'Editing disabled on mobile',
  mobileEditReason: 'Use desktop to change production policy configuration.',
  reviewDelegationLabel: 'Review delegation evidence',
  highRiskTitle: 'High-risk automatic outcome',
  providerTruthTitle: 'Provider readiness is probe-backed',
  providerTruthDescription: 'Unconfigured or stale providers cannot be selected as ready.',
};

export const operationsCopy: OperationsIncidentCopy = {
  header: header('Operations incident recovery'),
  state: stateCopy,
  navigationLabel: 'Operations recovery views',
  incidentsTab: 'Incidents',
  recoveryTab: 'Recovery plan',
  queuesTab: 'Queues',
  incidentsTitle: 'Active incidents',
  incidentsDescription: 'Server-reported delivery and processing incidents.',
  incidentDetailTitle: 'Incident detail',
  incidentDetailDescription: 'Select an incident to inspect evidence.',
  evidenceTitle: 'Source evidence',
  evidenceDescription: 'Current server facts and dependency observations.',
  recoveryTitle: 'Staged recovery plan',
  recoveryDescription: 'Dry-run evidence and exact recovery steps.',
  eligibilityTitle: 'Execution eligibility',
  stepsTitle: 'Recovery steps',
  payloadTitle: 'Redacted payload inspector',
  payloadDescription: 'Only server-redacted diagnostic fields are displayed.',
  queuesTitle: 'Processing queues',
  queuesDescription: 'Current queue depth, age, and source revision.',
  noSelectionLabel: 'Select an incident.',
  refreshLabel: 'Refresh source',
  prepareRecoveryLabel: 'Prepare recovery plan',
  executeRecoveryLabel: 'Execute staged recovery',
  mobileExecuteLabel: 'Execution requires desktop review',
  mobileExecuteReason: 'Recovery execution is disabled on mobile.',
  pauseQueueLabel: 'Pause queue',
  mobilePauseLabel: 'Queue control requires desktop review',
  mobilePauseReason: 'Queue mutations are disabled on mobile.',
  serverEvidenceTitle: 'Server evidence only',
  serverEvidenceDescription: 'The workspace never infers recovery success from client time.',
};

export const auditCopy: AuditRecordsCopy = {
  header: header('Audit and records evidence'),
  state: stateCopy,
  navigationLabel: 'Audit records views',
  explorerTab: 'Audit explorer',
  evidenceTab: 'Evidence bundle',
  retentionTab: 'Retention and hold',
  explorerTitle: 'Scoped audit events',
  explorerDescription: 'Authorized events with exact actor and target context.',
  eventDetailTitle: 'Event detail',
  eventDetailDescription: 'Select an event to inspect current evidence.',
  evidenceTitle: 'Evidence bundle',
  evidenceDescription: 'Server-generated manifests and verification results.',
  timelineTitle: 'Evidence timeline',
  manifestsTitle: 'Artifact manifests',
  manifestsDescription: 'Digest and source status reported by the server.',
  retentionTitle: 'Retention and legal hold',
  retentionDescription: 'Policy eligibility, preservation, and dual-control review.',
  noSelectionLabel: 'Select an audit event.',
  refreshLabel: 'Refresh evidence',
  verifyLabel: 'Verify current evidence',
  prepareExportLabel: 'Prepare governed export',
  mobileExportLabel: 'Export requires desktop review',
  mobileExportReason: 'Evidence export commands are disabled on mobile.',
  requestHoldReviewLabel: 'Request legal-hold review',
  mobileHoldLabel: 'Hold change requires desktop review',
  mobileHoldReason: 'Legal-hold mutations are disabled on mobile.',
  truthTitle: 'No inferred immutability claims',
  truthDescription: 'Integrity and archive labels reflect only current server verification.',
};

export const deploymentCopy: DeploymentCanaryCopy = {
  header: header('Approval asset deployment'),
  state: stateCopy,
  navigationLabel: 'Deployment workspace views',
  packagesTab: 'Asset packages',
  promotionTab: 'Promotion review',
  canaryTab: 'Canary evidence',
  rollbackTab: 'Rollback assessment',
  packagesTitle: 'Immutable asset packages',
  packagesDescription: 'Forms, workflows, policies, and connector dependencies.',
  packageDetailTitle: 'Package detail',
  packageDetailDescription: 'Select a package to inspect its manifest.',
  dependenciesTitle: 'Dependency validation',
  promotionTitle: 'Promotion plan',
  promotionDescription: 'Maker-checker gates and scheduled activation.',
  gatesTitle: 'Promotion gates',
  canaryTitle: 'Server-observed canary',
  canaryDescription: 'Current health evidence for the approval asset package.',
  observationsTitle: 'Evidence observations',
  rollbackTitle: 'Rollback assessment',
  rollbackDescription: 'Reversibility and external-effect blockers.',
  blockersTitle: 'Rollback blockers',
  noSelectionLabel: 'Select an asset package.',
  refreshLabel: 'Refresh deployment evidence',
  validatePackageLabel: 'Validate package',
  submitPromotionLabel: 'Submit promotion review',
  mobilePromotionLabel: 'Promotion requires desktop review',
  mobilePromotionReason: 'Production promotion is disabled on mobile.',
  pauseCanaryLabel: 'Pause canary progression',
  mobilePauseLabel: 'Canary control requires desktop review',
  mobilePauseReason: 'Canary mutations are disabled on mobile.',
  requestRollbackLabel: 'Request governed rollback',
  mobileRollbackLabel: 'Rollback requires desktop review',
  mobileRollbackReason: 'Rollback commands are disabled on mobile.',
  evidenceTruthTitle: 'Server-observed evidence',
  evidenceTruthDescription: 'No client timer or optimistic state can declare deployment success.',
};

export const metrics = [
  { id: 'active', label: 'Active', value: '12', tone: 'success' as const },
  { id: 'review', label: 'Pending review', value: '3', tone: 'warning' as const },
  { id: 'blocked', label: 'Blocked', value: '1', tone: 'danger' as const },
];

export const facts = [
  { id: 'owner', label: 'Owner', value: 'Finance Governance' },
  { id: 'revision', label: 'Authority revision', value: 'rev-184' },
];

export const healthy = { label: 'HEALTHY', tone: 'success' as const };
export const attention = { label: 'ATTENTION', tone: 'warning' as const };
