// @vitest-environment jsdom
import { act } from 'react';
import { fireEvent, getByRole, queryByRole } from '@testing-library/dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { OperationsIncidentRecoveryWorkspace } from './operations-incident-recovery-workspace';
import { attention, facts, healthy, metrics, operationsCopy } from './admin-v2-test-fixtures';
import { createAdminV2TestHarness, type AdminV2TestHarness } from './admin-v2-test-harness';

const incidents = [
  {
    id: 'incident-1',
    title: 'Approval delivery timeout',
    description: 'A provider acknowledgement was not received within policy.',
    severityLabel: 'SEV-2',
    detectedLabel: 'Detected 8 minutes ago',
    affectedLabel: '4 deliveries',
    correlationLabel: 'corr-approval-184',
    status: attention,
    sourceStatus: healthy,
    facts,
    evidence: [
      {
        id: 'evidence-1',
        title: 'Provider timeout receipt',
        detail: 'The server recorded an upstream timeout.',
        meta: 'source revision op-29',
        status: attention,
      },
    ],
  },
] as const;

const recoveryPlan = {
  incidentId: 'incident-1',
  planId: 'plan-1',
  planRevisionLabel: 'Plan revision 7',
  createdAtLabel: 'Generated by server at 10:42',
  dryRunStatus: healthy,
  executionStatus: { label: 'READY_FOR_REVIEW', tone: 'info' as const },
  eligibilityFacts: facts,
  steps: [
    {
      id: 'step-1',
      title: 'Reconcile provider receipt',
      detail: 'Read the provider receipt before preparing retry.',
      status: healthy,
    },
  ],
  redactedPayloadLabel: 'Server-redacted diagnostic payload',
  redactedPayloadPreview: '{ "requestId": "req-184", "secret": "[REDACTED]" }',
} as const;

const queues = [
  {
    id: 'queue-1',
    name: 'Approval integration delivery',
    description: 'Durable delivery queue for approval events.',
    depthLabel: 'Depth 4',
    oldestLabel: 'Oldest 8 minutes',
    sourceRevisionLabel: 'queue rev-29',
    status: attention,
  },
] as const;

describe('APR-22 operations incident recovery workspace', () => {
  let harness: AdminV2TestHarness;

  beforeEach(() => {
    vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT', true);
    harness = createAdminV2TestHarness();
  });

  afterEach(async () => {
    await harness.destroy();
    vi.unstubAllGlobals();
  });

  function props(view: 'incidents' | 'recovery' | 'queues' = 'incidents') {
    return {
      state: 'ready' as const,
      copy: operationsCopy,
      metrics,
      view,
      incidents,
      selectedIncidentId: 'incident-1',
      recoveryPlan,
      queues,
      prepareRecoveryReady: false,
      prepareRecoveryDisabledReason: 'An authored recovery plan is required.',
      executeRecoveryReady: true,
      executeRecoveryDisabledReason: 'A pending server stage is required.',
      pauseQueueReady: false,
      pauseQueueDisabledReason: 'The API has no queue pause command.',
      onViewChange: vi.fn(),
      onSelectIncident: vi.fn(),
      onRefresh: vi.fn(),
      onPrepareRecovery: vi.fn(),
      onExecuteRecovery: vi.fn(),
      onPauseQueue: vi.fn(),
      onRetry: vi.fn(),
      onResolveConflict: vi.fn(),
    };
  }

  it('renders server evidence and closes recovery preparation without authored inputs', async () => {
    const current = props();
    await harness.render(<OperationsIncidentRecoveryWorkspace {...current} />);
    expect(harness.node.textContent).toContain(operationsCopy.serverEvidenceDescription);
    expect(harness.node.textContent).toContain(incidents[0].correlationLabel);
    await act(async () => {
      fireEvent.click(getByRole(harness.node, 'button', { name: /Approval delivery timeout/u }));
      fireEvent.click(
        getByRole(harness.node, 'button', { name: operationsCopy.prepareRecoveryLabel })
      );
    });
    expect(current.onSelectIncident).toHaveBeenCalledWith('incident-1');
    expect(current.onPrepareRecovery).not.toHaveBeenCalled();
    expect(harness.node.textContent).toContain(current.prepareRecoveryDisabledReason);
  });

  it('executes only a server dry-run-qualified plan and keeps mobile execution disabled', async () => {
    const current = props('recovery');
    await harness.render(<OperationsIncidentRecoveryWorkspace {...current} />);
    expect(harness.node.textContent).toContain(recoveryPlan.planRevisionLabel);
    await act(async () =>
      fireEvent.click(
        getByRole(harness.node, 'button', { name: operationsCopy.executeRecoveryLabel })
      )
    );
    expect(current.onExecuteRecovery).toHaveBeenCalledWith('plan-1');
    expect(
      getByRole<HTMLButtonElement>(harness.node, 'button', {
        name: operationsCopy.mobileExecuteLabel,
      }).disabled
    ).toBe(true);
  });

  it('hides a recovery plan bound to a different selected incident and sends no command', async () => {
    const current = {
      ...props('recovery'),
      incidents: [
        ...incidents,
        { ...incidents[0], id: 'incident-2', title: 'Secondary provider incident' },
      ],
      selectedIncidentId: 'incident-2',
    };
    await harness.render(<OperationsIncidentRecoveryWorkspace {...current} />);
    expect(
      queryByRole(harness.node, 'button', { name: operationsCopy.executeRecoveryLabel })
    ).toBeNull();
    expect(current.onExecuteRecovery).not.toHaveBeenCalled();
  });

  it('fails closed on 503 and exposes only explicit source retry', async () => {
    const current = props();
    await harness.render(<OperationsIncidentRecoveryWorkspace {...current} state="unavailable" />);
    expect(harness.node.textContent).not.toContain(incidents[0].title);
    await act(async () =>
      fireEvent.click(getByRole(harness.node, 'button', { name: operationsCopy.state.retryAction }))
    );
    expect(current.onRetry).toHaveBeenCalledTimes(1);
  });

  it('keeps unsupported queue pause visible and inert when the queue list is empty', async () => {
    const current = props('queues');
    await harness.render(<OperationsIncidentRecoveryWorkspace {...current} queues={[]} />);
    const pause = getByRole<HTMLButtonElement>(harness.node, 'button', {
      name: operationsCopy.pauseQueueLabel,
    });
    expect(pause.disabled).toBe(true);
    await act(async () => fireEvent.click(pause));
    expect(current.onPauseQueue).not.toHaveBeenCalled();
    expect(harness.node.textContent).toContain(current.pauseQueueDisabledReason);
  });
});
