type WidenCopy<T> = { [K in keyof T]: T[K] extends string ? string : WidenCopy<T[K]> };

export const DWAION_ARTIFACT_COPY_KO = {
  eyebrow: '검증형 AI 산출물',
  title: '결과물 스튜디오',
  description:
    'AI와 함께 문서를 작성하고 불변 버전과 결정형 사전검사를 거쳐 개인 워크스페이스 게시 상태로 관리합니다.',
  loading: '결과물을 불러오는 중입니다',
  errorTitle: '결과물을 불러오지 못했습니다',
  permissionTitle: '결과물에 접근할 권한이 없습니다',
  permissionDescription: '현재 계정의 DWAI·ON 결과물 권한을 확인해 주세요.',
  emptyTitle: '아직 만든 결과물이 없습니다',
  emptyDescription: '문서, 업무 계획 또는 비교 초안을 만들고 안전한 검토 흐름을 시작하세요.',
  create: '결과물 만들기',
  createTitle: '새 결과물',
  createDescription: '개인 워크스페이스에서 관리할 결과물의 유형과 첫 내용을 입력합니다.',
  retry: '다시 시도',
  partial: '일부 버전 또는 사전검사 상태를 확인하지 못했습니다.',
  commandFailed: '요청을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.',
  revisionConflict: '다른 곳에서 문서가 변경되었습니다. 최신 버전을 불러왔습니다.',
  artifacts: '내 결과물',
  close: '패널 닫기',
  openArtifacts: '결과물 목록 열기',
  openEvidence: '출처 근거 열기',
  document: '문서',
  sources: '출처 근거',
  noEvidence: '연결된 출처 참조가 없습니다',
  noEvidenceDescription: '현재 버전에 출처 참조가 연결되면 이곳에 표시됩니다.',
  editorTitle: '제목',
  editorLabel: '결과물 본문',
  artifactTypes: { DOCUMENT: '문서', WORK_PLAN: '업무 계획', COMPARISON: '비교' },
  artifactStates: {
    DRAFT: '초안',
    REVIEW_REQUIRED: '검토 필요',
    PUBLISHED: '개인 게시됨',
    ARCHIVED: '보관됨',
  },
  autosave: {
    IDLE: '저장된 상태',
    DIRTY: '저장 대기',
    SAVING: '자동 저장 중',
    SAVED: '자동 저장됨',
    CONFLICT: '저장 충돌',
    FAILED: '저장 실패',
  },
  conflictHelp: '다른 revision이 먼저 저장되어 로컬 변경을 적용하지 않았습니다.',
  versions: '버전 비교',
  versionTitle: '불변 버전 비교',
  versionDescription: '두 버전의 저장된 본문을 불러와 읽기 전용으로 비교합니다.',
  versionEmpty: '비교할 버전이 아직 없습니다.',
  leftVersion: '기준 버전',
  rightVersion: '비교 버전',
  compare: '비교',
  loadingVersion: '버전 불러오는 중',
  preflight: '버전 생성 및 사전검사',
  preflightRun: '버전 만들고 검사',
  preflightRunning: '버전 생성·검사 중',
  preflightStates: { PASS: '통과', REVIEW: '검토 필요', BLOCKED: '차단' },
  preflightNotRun: '현재 버전의 사전검사가 필요합니다.',
  sourceVerification: '출처 검증',
  verificationUnavailable: '출처 진위와 최신성 검증은 아직 연결되지 않았습니다.',
  verificationStates: { UNVERIFIED: '미검증', UNKNOWN: '최신성 알 수 없음' },
  publish: '개인 게시',
  publishing: '게시 중',
  publishHelp: '수신자에게 공유하지 않고 내 워크스페이스에서 검토 완료 상태로 표시합니다.',
  recipientSharingUnavailable: '수신자 공유와 외부 쓰기는 제공하지 않습니다.',
  exportRequest: '내보내기 요청',
  exportRequesting: '요청 중',
  exportHelp: '현재 버전은 내보내기 요청 영수증만 생성하며 파일을 만들거나 내려받지 않습니다.',
  exportFormats: { MARKDOWN: 'Markdown', DOCX: 'Word 문서', PDF: 'PDF' },
  exportReceipt: '내보내기 요청 접수',
  exportReceiptDetail: '{{format}} 요청 · 파일 생성 대기',
  releaseBlocked: {
    PERMISSION_REQUIRED: '이 작업을 수행할 권한이 없습니다.',
    UNSAVED_CHANGES: '현재 변경 사항이 저장된 뒤 진행할 수 있습니다.',
    REVISION_CONFLICT: '저장 충돌을 해결한 뒤 진행할 수 있습니다.',
    VERSION_REQUIRED: '먼저 현재 초안의 불변 버전을 만들어야 합니다.',
    PREFLIGHT_REQUIRED: '현재 불변 버전에 대한 사전검사가 필요합니다.',
    PREFLIGHT_BLOCKED: '사전검사 결과를 해결한 뒤 진행할 수 있습니다.',
    PERSONAL_PUBLISH_UNAVAILABLE: '개인 게시 상태 기능을 사용할 수 없습니다.',
    PUBLISH_REQUIRED: '현재 버전을 개인 게시한 뒤 내보내기를 요청할 수 있습니다.',
    EXPORT_REQUEST_UNAVAILABLE: '내보내기 요청 기능을 사용할 수 없습니다.',
  },
  cancel: '취소',
  closeAction: '닫기',
  save: '만들기',
  saving: '만드는 중',
  updatedAt: '업데이트',
  sourceReference: '참조',
  currentVersion: '현재 버전',
  versionPrefix: 'v',
  publishedVersion: '게시 버전',
  separator: '·',
  labelSeparator: ':',
  revisionPrefix: 'r',
} as const;

export const DWAION_ARTIFACT_COPY_EN: DwaionArtifactCopy = {
  eyebrow: 'Governed AI deliverables',
  title: 'Artifact studio',
  description:
    'Draft with AI, capture immutable versions, run deterministic preflight, and manage personal workspace publication state.',
  loading: 'Loading artifacts',
  errorTitle: 'Artifacts could not be loaded',
  permissionTitle: 'You do not have access to artifacts',
  permissionDescription: 'Check the DWAI·ON artifact permissions for the current account.',
  emptyTitle: 'No artifacts yet',
  emptyDescription: 'Create a document, work plan, or comparison and begin a governed review flow.',
  create: 'Create artifact',
  createTitle: 'New artifact',
  createDescription: 'Choose a type and enter the first content for your personal workspace.',
  retry: 'Retry',
  partial: 'Some version or preflight state could not be verified.',
  commandFailed: 'The request could not be completed. Try again shortly.',
  revisionConflict: 'The artifact changed elsewhere. The latest revision was loaded.',
  artifacts: 'My artifacts',
  close: 'Close panel',
  openArtifacts: 'Open artifact list',
  openEvidence: 'Open source references',
  document: 'Document',
  sources: 'Source references',
  noEvidence: 'No source references are linked',
  noEvidenceDescription: 'References linked to the current version appear here.',
  editorTitle: 'Title',
  editorLabel: 'Artifact body',
  artifactTypes: { DOCUMENT: 'Document', WORK_PLAN: 'Work plan', COMPARISON: 'Comparison' },
  artifactStates: {
    DRAFT: 'Draft',
    REVIEW_REQUIRED: 'Review required',
    PUBLISHED: 'Published personally',
    ARCHIVED: 'Archived',
  },
  autosave: {
    IDLE: 'Saved',
    DIRTY: 'Waiting to save',
    SAVING: 'Autosaving',
    SAVED: 'Autosaved',
    CONFLICT: 'Save conflict',
    FAILED: 'Save failed',
  },
  conflictHelp: 'Another revision was saved first, so the local change was not applied.',
  versions: 'Compare versions',
  versionTitle: 'Immutable version comparison',
  versionDescription: 'Load two saved bodies and compare them read-only.',
  versionEmpty: 'No versions are available to compare.',
  leftVersion: 'Base version',
  rightVersion: 'Comparison version',
  compare: 'Compare',
  loadingVersion: 'Loading version',
  preflight: 'Version and preflight',
  preflightRun: 'Create version and inspect',
  preflightRunning: 'Creating version and inspecting',
  preflightStates: { PASS: 'Passed', REVIEW: 'Review required', BLOCKED: 'Blocked' },
  preflightNotRun: 'The current immutable version requires preflight.',
  sourceVerification: 'Source verification',
  verificationUnavailable: 'Source authenticity and freshness verification are not connected yet.',
  verificationStates: { UNVERIFIED: 'Unverified', UNKNOWN: 'Freshness unknown' },
  publish: 'Publish personally',
  publishing: 'Publishing',
  publishHelp: 'Marks the version reviewed in your workspace without sharing it with recipients.',
  recipientSharingUnavailable: 'Recipient sharing and external writes are unavailable.',
  exportRequest: 'Request export',
  exportRequesting: 'Requesting',
  exportHelp:
    'This release creates an export request receipt only. It does not generate or download a file.',
  exportFormats: { MARKDOWN: 'Markdown', DOCX: 'Word document', PDF: 'PDF' },
  exportReceipt: 'Export request accepted',
  exportReceiptDetail: '{{format}} requested · file generation pending',
  releaseBlocked: {
    PERMISSION_REQUIRED: 'You do not have permission for this action.',
    UNSAVED_CHANGES: 'Wait until current changes are saved.',
    REVISION_CONFLICT: 'Resolve the save conflict first.',
    VERSION_REQUIRED: 'Create an immutable version from the current draft first.',
    PREFLIGHT_REQUIRED: 'Run preflight against the current immutable version.',
    PREFLIGHT_BLOCKED: 'Resolve the preflight outcome before continuing.',
    PERSONAL_PUBLISH_UNAVAILABLE: 'Personal publication state is unavailable.',
    PUBLISH_REQUIRED: 'Publish the current version personally before requesting export.',
    EXPORT_REQUEST_UNAVAILABLE: 'Export requests are unavailable.',
  },
  cancel: 'Cancel',
  closeAction: 'Close',
  save: 'Create',
  saving: 'Creating',
  updatedAt: 'Updated',
  sourceReference: 'Reference',
  currentVersion: 'Current version',
  versionPrefix: 'v',
  publishedVersion: 'Published version',
  separator: '·',
  labelSeparator: ':',
  revisionPrefix: 'r',
};

export type DwaionArtifactCopy = WidenCopy<typeof DWAION_ARTIFACT_COPY_KO>;
