export const DWAION_ARTIFACT_COLLABORATION_COPY = {
  ko: {
    title: '팀 산출물과 협업 검토',
    description: '수신자 ACL 사전검사, 충돌 복구, 만료형 내부 공유를 실제 영수증으로 관리합니다.',
    loading: '협업 정책과 작업공간을 확인하는 중입니다',
    available: '협업 연결됨',
    unavailable: '협업 설정 필요',
    providerRecovery: '관리자에게 팀 ACL 브로커와 보안 저장소 설정을 요청해 주세요.',
    retry: '상태 다시 확인',
    error: '협업 상태를 확인하지 못했습니다. 서버 상태를 확인한 뒤 다시 시도해 주세요.',
    preflightTitle: '팀 공유 사전검사',
    teamId: '팀 ID',
    invalidTeam: '올바른 팀 UUID를 입력해 주세요.',
    members: '수신자와 역할',
    membersPlaceholder: 'user@company.com,EDITOR',
    membersHelp: '한 줄에 수신자 ID와 OWNER, EDITOR, REVIEWER, VIEWER 중 하나를 입력합니다.',
    excludeSources: '접근할 수 없는 출처를 제외하고 재검사',
    runPreflight: '권한 사전검사',
    createWorkspace: '팀 작업공간 만들기',
    allowedSources: '허용 출처',
    excludedSources: '제외 출처',
    preflightStates: {
      READY: '사전검사 통과',
      PARTIAL: '일부 출처 제외',
      PERMISSION_DENIED: '권한 확인 필요',
      EXPIRED: '사전검사 만료',
    },
    excludeAndRetry: '접근 불가 출처 제외',
    removeDenied: '권한 없는 수신자 제거',
    requestAccess: '접근 권한 요청',
    accessRequestUnavailable: '현재 환경에서는 접근 권한 요청을 전송할 수 없습니다.',
    accessRequestSubmitted: '접근 요청 접수 증거',
    recoveryTitle: '검토 복구와 재상신',
    recoveryHelp:
      '사전검사 결과를 기준으로 소명이나 개인 초안을 실제 산출물 버전에 저장하고 다시 검사·공유합니다.',
    explanation: '검토 소명',
    explanationPlaceholder: '검토자가 확인할 예외 사유와 근거를 입력하세요.',
    saveExplanation: '소명 저장',
    savePrivateDraft: '개인 초안 보관',
    resubmit: '재검사 후 재상신',
    automaticMasking: '모두 마스킹',
    syntheticReplacement: '합성 데이터로 대체',
    reviewNotification: '검토 재전송',
    reviewRejection: '검토 거절',
    providerActionUnavailable: '현재 연결된 공급자가 이 작업을 제공하지 않습니다.',
    workspaceActive: '팀 작업공간',
    authorizedMembers: '권한 확인된 구성원',
    preflightEvidenceTitle: '팀 공유 게이트 증거',
    artifactRevision: '산출물 리비전',
    decisionRevision: '판정 리비전',
    evidenceFingerprint: '검증 핑거프린트',
    preflightExpiresAt: '사전검사 만료',
    memberChecks: '수신자 ACL 확인',
    reviewWorkflowTitle: '검토 역할과 승인 경계',
    reviewWorkflowHelp:
      '작업공간 계약에서 확인된 역할만 표시합니다. 단계별 승인 판정과 기한은 현재 API에서 제공되지 않습니다.',
    reviewDecisionUnavailable: '단계별 검토 판정 미제공',
    wormEvidenceTitle: 'WORM 감사 서명',
    wormEvidenceUnavailable:
      '현재 협업 계약은 서명된 WORM 영수증을 반환하지 않습니다.',
    allowed: '허용',
    denied: '차단',
    syncDocument: '현재 문서 동기화',
    applyMembers: '사전검사 권한 적용',
    conflictTitle: '동시 편집 충돌을 해결해 주세요',
    localVersion: '내 변경',
    serverVersion: '서버 최신본',
    loadLatest: '최신본 다시 불러오기',
    readOnlyFallback:
      '결정 전에는 작업공간을 읽기 전용으로 두고 두 버전을 안전하게 비교할 수 있습니다.',
    conflicts: {
      USE_LOCAL: '내 변경 사용',
      USE_SERVER: '서버 버전 사용',
      MERGE: '현재 내용으로 병합',
      STASH: '내 변경 보관',
      ROLLBACK: '이전 버전으로 복원',
    },
    shareTitle: '만료형 내부 공유',
    permission: '공유 권한',
    permissions: { VIEW: '보기', COMMENT: '댓글', EDIT: '편집' },
    expiry: '공유 만료',
    createShare: '내부 공유 만들기',
    noShares: '활성 또는 이전 공유가 없습니다.',
    revoke: '공유 해지',
    shareReceipt: '공유 영수증',
    revocationReceipt: '해지 영수증',
  },
  en: {
    title: 'Team artifacts and review',
    description:
      'Manage recipient ACL preflight, conflict recovery, and expiring internal shares with live receipts.',
    loading: 'Checking collaboration policy and workspace',
    available: 'Collaboration connected',
    unavailable: 'Collaboration setup required',
    providerRecovery: 'Ask an administrator to configure the team ACL broker and secure store.',
    retry: 'Check status again',
    error: 'Collaboration state could not be verified. Check the service and retry.',
    preflightTitle: 'Team share preflight',
    teamId: 'Team ID',
    invalidTeam: 'Enter a valid team UUID.',
    members: 'Recipients and roles',
    membersPlaceholder: 'user@company.com,EDITOR',
    membersHelp: 'Enter one recipient per line with OWNER, EDITOR, REVIEWER, or VIEWER.',
    excludeSources: 'Exclude inaccessible sources and rerun',
    runPreflight: 'Run authorization preflight',
    createWorkspace: 'Create team workspace',
    allowedSources: 'Allowed sources',
    excludedSources: 'Excluded sources',
    preflightStates: {
      READY: 'Preflight passed',
      PARTIAL: 'Some sources excluded',
      PERMISSION_DENIED: 'Permission review required',
      EXPIRED: 'Preflight expired',
    },
    excludeAndRetry: 'Exclude inaccessible sources',
    removeDenied: 'Remove unauthorized recipients',
    requestAccess: 'Request access',
    accessRequestUnavailable: 'Access-request delivery is unavailable in this environment.',
    accessRequestSubmitted: 'Access request submission evidence',
    recoveryTitle: 'Review recovery and resubmission',
    recoveryHelp:
      'Save an explanation or private draft as a governed artifact version, then rerun preflight and share.',
    explanation: 'Review explanation',
    explanationPlaceholder: 'Describe the exception and evidence for the reviewer.',
    saveExplanation: 'Save explanation',
    savePrivateDraft: 'Keep private draft',
    resubmit: 'Recheck and resubmit',
    automaticMasking: 'Mask all',
    syntheticReplacement: 'Replace with synthetic data',
    reviewNotification: 'Resend review',
    reviewRejection: 'Reject review',
    providerActionUnavailable: 'The connected provider does not offer this action.',
    workspaceActive: 'Team workspace',
    authorizedMembers: 'Authorized members',
    preflightEvidenceTitle: 'Team share gate evidence',
    artifactRevision: 'Artifact revision',
    decisionRevision: 'Decision revision',
    evidenceFingerprint: 'Evidence fingerprint',
    preflightExpiresAt: 'Preflight expiry',
    memberChecks: 'Recipient ACL checks',
    reviewWorkflowTitle: 'Review roles and approval boundary',
    reviewWorkflowHelp:
      'Only roles verified by the workspace contract are shown. Stage decisions and deadlines are not returned by the current API.',
    reviewDecisionUnavailable: 'Stage-level review decisions unavailable',
    wormEvidenceTitle: 'WORM audit signature',
    wormEvidenceUnavailable:
      'The current collaboration contract does not return a signed WORM receipt.',
    allowed: 'Allowed',
    denied: 'Denied',
    syncDocument: 'Sync current document',
    applyMembers: 'Apply preflight members',
    conflictTitle: 'Resolve the concurrent edit conflict',
    localVersion: 'My changes',
    serverVersion: 'Latest server version',
    loadLatest: 'Load latest version',
    readOnlyFallback:
      'The workspace remains a safe read-only comparison until a resolution is chosen.',
    conflicts: {
      USE_LOCAL: 'Use my changes',
      USE_SERVER: 'Use server version',
      MERGE: 'Merge current content',
      STASH: 'Stash my changes',
      ROLLBACK: 'Roll back revision',
    },
    shareTitle: 'Expiring internal share',
    permission: 'Permission',
    permissions: { VIEW: 'View', COMMENT: 'Comment', EDIT: 'Edit' },
    expiry: 'Share expiry',
    createShare: 'Create internal share',
    noShares: 'No current or previous shares.',
    revoke: 'Revoke share',
    shareReceipt: 'Share receipt',
    revocationReceipt: 'Revocation receipt',
  },
} as const;
