type WidenCopy<T> = { [K in keyof T]: T[K] extends string ? string : WidenCopy<T[K]> };

export const DWAION_PERSONAL_CONTROLS_COPY_KO = {
  eyebrow: '개인 AI 거버넌스',
  title: '나의 AI 제어',
  description:
    'DWAI·ON이 참조할 정보 경계와 사용자가 직접 저장한 선호, 보존·삭제 요청을 한곳에서 관리합니다.',
  loading: '개인 AI 설정을 불러오는 중입니다',
  errorTitle: '개인 AI 설정을 불러오지 못했습니다',
  permissionTitle: '개인 AI 설정을 볼 권한이 없습니다',
  permissionDescription: '현재 계정의 개인 AI 설정 권한을 확인해 주세요.',
  emptyTitle: '사용 가능한 AI 정보 출처가 없습니다',
  emptyDescription: '조직에서 허용한 정보 출처가 제공되면 여기에서 개별 동의를 관리합니다.',
  retry: '다시 시도',
  partial: '일부 설정의 최신 상태를 확인하지 못했습니다.',
  commandFailed: '요청을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.',
  revisionConflict: '설정이 다른 곳에서 변경되었습니다. 최신 내용을 다시 불러와 주세요.',
  memoryPreferenceTitle: '명시적 메모리 저장',
  memoryPreferenceDescription:
    '내가 직접 입력한 선호만 암호화해 저장합니다. 대화에서 자동 추론하거나 자격 증명을 저장하지 않습니다.',
  memoryPreferenceStates: { UNSET: '선택 필요', DISABLED: '사용 안 함', ENABLED: '사용' },
  memoryEffective: '저장 허용됨',
  memoryNotEffective: '저장 중지됨',
  runtimeUnavailable:
    '저장과 관리는 가능하지만 현재 답변 생성 런타임에는 아직 자동 적용되지 않습니다.',
  sourceTitle: '업무 신호 분석 범위',
  sourceDescription:
    '출처별로 허용 여부를 정합니다. 유효한 출처는 개인 루틴의 드라이런에서 참조 식별자만 사용합니다.',
  sourceLabels: { WORK_ITEM: '업무 항목', MAIL: '메일', CALENDAR: '일정' },
  sourceDescriptions: {
    WORK_ITEM: '현재 권한으로 볼 수 있는 업무의 식별자와 상태',
    MAIL: '현재 권한으로 볼 수 있는 메일의 식별자와 메타데이터',
    CALENDAR: '현재 권한으로 볼 수 있는 일정의 식별자와 시간 정보',
  },
  unavailable: '사용할 수 없음',
  enabled: '사용',
  disabled: '사용 안 함',
  effective: '유효',
  notEffective: '적용 안 됨',
  referenceOnly: '원문 복제 없음',
  memoryTitle: '내가 저장한 선호',
  memoryDescription:
    '응답 형식·길이·말투·업무 방식만 저장할 수 있습니다. 계정·결제·규제 식별정보는 저장할 수 없습니다.',
  memoryEmpty: '저장된 선호가 없습니다',
  addMemory: '선호 추가',
  editMemory: '선호 수정',
  deleteMemory: '선호 삭제',
  memoryKind: '선호 유형',
  memoryKinds: {
    RESPONSE_LENGTH: '응답 길이',
    OUTPUT_FORMAT: '출력 형식',
    TONE: '말투',
    WORKING_STYLE: '업무 방식',
  },
  memoryValue: '기억할 내용',
  memorySource: '사용자 직접 입력',
  memoryStates: { ACTIVE: '사용', DISABLED: '일시 중지', DELETED: '삭제됨' },
  sensitiveWarning: '비밀번호, 인증 토큰, 주민번호, 계좌·카드 번호는 입력하지 마세요.',
  save: '저장',
  saving: '저장 중',
  saved: '개인 AI 설정을 저장했습니다.',
  cancel: '취소',
  deleteTitle: '이 선호를 삭제할까요?',
  deleteDescription: '삭제한 선호는 다시 사용할 수 없습니다.',
  deleteConfirm: '삭제',
  clearTitle: '개인 AI 데이터 정리',
  clearDescription:
    'AI 제안은 즉시 내 제안함에서 숨기고, 나머지 개인 데이터는 삭제 요청을 접수합니다.',
  clearAction: '데이터 정리',
  clearConfirm: '정리 요청',
  clearing: '요청 중',
  clearScopes: {
    PROPOSALS: 'AI 제안함 비우기',
    ROUTINE: '개인 AI 루틴',
    MEMORY: '명시적 메모리',
    ARTIFACT: '결과물과 버전',
    ARTIFACT_EXPORT: '내보내기 요청',
  },
  clearEvidence: '처리 증거',
  proposalHidden: '제안함에서 숨긴 항목',
  deletionRequested: '삭제 요청 접수',
  requestState: {
    REQUESTED: '접수됨',
    RUNNING: '처리 중',
    PARTIAL: '일부 처리',
    COMPLETED: '완료',
    BLOCKED_LEGAL_HOLD: '법적 보존으로 차단',
    FAILED: '실패',
  },
  receiptId: '요청 ID',
  requestedAt: '요청 시각',
  executionUnavailable:
    '현재 버전은 삭제 요청 접수까지만 지원합니다. 실행 완료로 표시하지 않습니다.',
  sourceUnaffected: '메일·일정·업무 원본 데이터와 필수 감사 메타데이터는 삭제 대상이 아닙니다.',
  privacyUnavailable: '보존·삭제 정책을 볼 권한이 없어 해당 영역을 표시하지 않습니다.',
  retentionTitle: '보존 경계',
  retentionDays: '보존 {{days}}일 · 삭제 유예 {{grace}}일',
  legalHold: '법적 보존 적용',
  noLegalHold: '법적 보존 없음',
  separator: '·',
  revisionPrefix: 'r',
} as const;

export const DWAION_PERSONAL_CONTROLS_COPY_EN: DwaionPersonalControlsCopy = {
  eyebrow: 'Personal AI governance',
  title: 'My AI controls',
  description:
    'Manage the information boundaries DWAI·ON may reference, explicit preferences, and retention or deletion requests in one place.',
  loading: 'Loading personal AI controls',
  errorTitle: 'Personal AI controls could not be loaded',
  permissionTitle: 'You do not have access to personal AI controls',
  permissionDescription: 'Check the personal AI permissions for the current account.',
  emptyTitle: 'No AI information sources are available',
  emptyDescription: 'Source-level consent appears here when your organization enables sources.',
  retry: 'Retry',
  partial: 'Some controls could not be verified.',
  commandFailed: 'The request could not be completed. Try again shortly.',
  revisionConflict: 'These controls changed elsewhere. Refresh before trying again.',
  memoryPreferenceTitle: 'Explicit memory storage',
  memoryPreferenceDescription:
    'Only preferences you enter are encrypted and stored. Conversations are not inferred and credentials are never stored.',
  memoryPreferenceStates: { UNSET: 'Choice required', DISABLED: 'Off', ENABLED: 'On' },
  memoryEffective: 'Storage allowed',
  memoryNotEffective: 'Storage stopped',
  runtimeUnavailable:
    'Preferences can be stored and managed, but are not yet applied automatically to answer generation.',
  sourceTitle: 'Work signal analysis scope',
  sourceDescription:
    'Choose each source independently. Effective sources expose reference identifiers only to routine dry runs.',
  sourceLabels: { WORK_ITEM: 'Work items', MAIL: 'Mail', CALENDAR: 'Calendar' },
  sourceDescriptions: {
    WORK_ITEM: 'Identifiers and status visible to the current account',
    MAIL: 'Mail identifiers and metadata visible to the current account',
    CALENDAR: 'Schedule identifiers and timing visible to the current account',
  },
  unavailable: 'Unavailable',
  enabled: 'On',
  disabled: 'Off',
  effective: 'Effective',
  notEffective: 'Not applied',
  referenceOnly: 'No raw content copy',
  memoryTitle: 'Preferences I saved',
  memoryDescription:
    'Store response format, length, tone, or working style only. Account, payment, and regulated identifiers are rejected.',
  memoryEmpty: 'No saved preferences',
  addMemory: 'Add preference',
  editMemory: 'Edit preference',
  deleteMemory: 'Delete preference',
  memoryKind: 'Preference type',
  memoryKinds: {
    RESPONSE_LENGTH: 'Response length',
    OUTPUT_FORMAT: 'Output format',
    TONE: 'Tone',
    WORKING_STYLE: 'Working style',
  },
  memoryValue: 'Preference',
  memorySource: 'Entered by you',
  memoryStates: { ACTIVE: 'Active', DISABLED: 'Paused', DELETED: 'Deleted' },
  sensitiveWarning: 'Do not enter passwords, tokens, government IDs, bank, or card numbers.',
  save: 'Save',
  saving: 'Saving',
  saved: 'Personal AI controls saved.',
  cancel: 'Cancel',
  deleteTitle: 'Delete this preference?',
  deleteDescription: 'A deleted preference cannot be used again.',
  deleteConfirm: 'Delete',
  clearTitle: 'Clean up personal AI data',
  clearDescription:
    'AI proposals are hidden immediately; other personal domains create a deletion request.',
  clearAction: 'Clean up data',
  clearConfirm: 'Submit request',
  clearing: 'Submitting',
  clearScopes: {
    PROPOSALS: 'Clear AI proposal inbox',
    ROUTINE: 'Personal AI routines',
    MEMORY: 'Explicit memories',
    ARTIFACT: 'Artifacts and versions',
    ARTIFACT_EXPORT: 'Export requests',
  },
  clearEvidence: 'Processing evidence',
  proposalHidden: 'Items hidden from proposals',
  deletionRequested: 'Deletion request accepted',
  requestState: {
    REQUESTED: 'Requested',
    RUNNING: 'Running',
    PARTIAL: 'Partially completed',
    COMPLETED: 'Completed',
    BLOCKED_LEGAL_HOLD: 'Blocked by legal hold',
    FAILED: 'Failed',
  },
  receiptId: 'Request ID',
  requestedAt: 'Requested at',
  executionUnavailable:
    'This release accepts deletion requests only. It does not claim execution is complete.',
  sourceUnaffected:
    'Source mail, calendar, work records, and required audit metadata are unaffected.',
  privacyUnavailable:
    'Retention and deletion controls are hidden because permission is unavailable.',
  retentionTitle: 'Retention boundaries',
  retentionDays: 'Retain {{days}} days · deletion grace {{grace}} days',
  legalHold: 'Legal hold active',
  noLegalHold: 'No legal hold',
  separator: '·',
  revisionPrefix: 'r',
};

export type DwaionPersonalControlsCopy = WidenCopy<typeof DWAION_PERSONAL_CONTROLS_COPY_KO>;
