type WidenCopy<T> = { [K in keyof T]: T[K] extends string ? string : WidenCopy<T[K]> };

export const DWAION_PERSONAL_CONTROLS_COPY_KO = {
  eyebrow: '개인 AI 거버넌스',
  title: '나의 AI 제어',
  description:
    'DWAI·ON이 참조할 정보 경계와 사용자가 직접 저장한 선호, 보존·삭제 요청을 한곳에서 관리합니다.',
  tabsLabel: '개인 AI 제어 영역',
  tabs: {
    sources: '업무 신호 분석 허용',
    memories: '개인 명시적 메모리',
    cleanup: '데이터 비우기',
    compliance: '컴플라이언스',
  },
  livePolicy: '서버 정책 응답 확인',
  partialPolicy: '일부 정책 응답 미확인',
  savedMemoryCount: '저장한 선호',
  deletionUnavailableBadge: '삭제 실행 미지원',
  revalidate: '권한·정책 다시 확인',
  governanceTitle: '보안 경계 증거',
  governanceDescription: '현재 API 계약으로 확인한 개인 AI 안전 경계입니다.',
  governanceFacts: {
    inference: '대화 자동 추론',
    sensitive: '민감정보 메모리',
    credential: '자격 증명 저장',
    team: '팀 공유 메모리',
    external: '승인 없는 외부 실행',
  },
  allowed: '허용',
  blocked: '차단',
  boundaryUnknown: '확인되지 않음',
  deletionStatusError:
    '삭제 요청은 접수되었지만 최신 처리 상태를 확인하지 못했습니다. 완료로 간주하지 마세요. 상태를 다시 확인할 수 있습니다.',
  auditUnavailable: '개인 감사 이벤트 목록 API는 제공되지 않습니다.',
  cleanupTitle: '데이터 삭제 및 비우기',
  cleanupDescription:
    '제안함은 즉시 숨김 처리하고, 다른 개인 데이터는 서버 삭제 작업을 요청합니다.',
  cleanupBoundary: '원본 업무·메일·일정과 필수 감사 메타데이터는 삭제하지 않습니다.',
  loading: '개인 AI 설정을 불러오는 중입니다',
  errorTitle: '개인 AI 설정을 불러오지 못했습니다',
  permissionTitle: '개인 AI 설정을 볼 권한이 없습니다',
  permissionDescription: '현재 계정의 개인 AI 설정 권한을 확인해 주세요.',
  emptyTitle: '사용 가능한 AI 정보 출처가 없습니다',
  emptyDescription: '조직에서 허용한 정보 출처가 제공되면 여기에서 개별 동의를 관리합니다.',
  retry: '다시 시도',
  partial: '일부 설정의 최신 상태를 확인하지 못했습니다.',
  commandFailed: '요청을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.',
  revisionConflict: '설정이 다른 곳에서 변경되었습니다. 최신 내용을 다시 불러와 주세요.',
  memoryPreferenceTitle: '명시적 메모리 저장',
  memoryPreferenceDescription:
    '내가 직접 입력한 선호만 암호화해 저장합니다. 대화에서 자동 추론하거나 자격 증명을 저장하지 않습니다.',
  memoryPreferenceStates: { UNSET: '선택 필요', DISABLED: '사용 안 함', ENABLED: '사용' },
  memoryEffective: '답변 개인화 켜짐',
  memoryNotEffective: '답변 개인화 꺼짐',
  memoryStorageTitle: '선호 저장',
  memoryStorageDescription: '직접 입력한 선호를 암호화해 저장하고 언제든 수정하거나 삭제합니다.',
  runtimePreferenceTitle: '답변에 선호 적용',
  runtimePreferenceDescription:
    '활성 선호를 답변 생성에 전달합니다. 선호는 표현 방식에만 사용되며 사실·권한·정책을 바꾸지 않습니다.',
  runtimeRequiresStorage: '답변에 적용하려면 먼저 명시적 메모리 저장을 켜야 합니다.',
  runtimeUnavailable:
    '현재 연결된 런타임이 답변 개인화 계약을 지원하지 않습니다. 선호는 저장만 되고 답변에 전달되지 않습니다.',
  sourceTitle: '업무 신호 분석 범위',
  sourceDescription:
    '출처별로 허용 여부를 정합니다. 유효한 출처는 개인 루틴의 드라이런에서 참조 식별자만 사용합니다.',
  sourceLabels: { WORK_ITEM: '업무 항목', MAIL: '메일', CALENDAR: '일정' },
  sourceDescriptions: {
    WORK_ITEM: '현재 권한으로 볼 수 있는 업무의 식별자와 상태',
    MAIL: '현재 권한으로 볼 수 있는 메일의 식별자와 메타데이터',
    CALENDAR: '현재 권한으로 볼 수 있는 일정의 식별자와 시간 정보',
  },
  unavailable: '사용할 수 없음',
  enabled: '사용',
  disabled: '사용 안 함',
  effective: '유효',
  notEffective: '적용 안 됨',
  referenceOnly: '원문 복제 없음',
  routineScope: '개인 루틴 검증에만 사용',
  unknownScope: '적용 범위 확인 필요',
  memoryTitle: '내가 저장한 선호',
  memoryDescription:
    '응답 형식·길이·말투·업무 방식만 저장할 수 있습니다. 계정·결제·규제 식별정보는 저장할 수 없습니다.',
  memoryEmpty: '저장된 선호가 없습니다',
  memoryFiltersLabel: '메모리 분류',
  memoryFilters: {
    ALL: '전체',
    MANUAL: '수동',
    AI_APPROVED: 'AI 승인',
    EXPIRING: '만료 임박',
  },
  automaticInferenceBlocked:
    '현재 서버 정책은 대화 자동 추론을 차단합니다. AI 승인 메모리를 생성하거나 추정하지 않습니다.',
  automaticInferenceUnknown:
    '자동 메모리 추론 정책을 확인할 수 없어 AI 승인 메모리를 표시하지 않습니다.',
  expiringMemoryEmpty: '앞으로 30일 안에 만료되는 선호가 없습니다.',
  selectMemory: '상세 보기',
  memoryDetailTitle: '선택한 메모리 상세 및 증거',
  memoryProvenanceTitle: '출처 및 변경 증거',
  createdAt: '생성',
  updatedAt: '최근 변경',
  memoryId: '메모리 ID',
  memoryRevision: '서버 리비전',
  memoryOrigin: '등록 방식',
  memorySourceType: '출처 유형',
  manualMemory: '사용자 직접 등록',
  pauseMemory: '일시 비활성화',
  resumeMemory: '다시 활성화',
  memoryGovernanceEvidenceTitle: '고급 메모리 증거',
  memoryGovernanceEvidenceDescription:
    '서버가 검증해 반환한 데이터만 표시하며 값이 없는 지표는 추정하지 않습니다.',
  factVectorTitle: '검증 팩트 벡터 및 신뢰도',
  factVectorUnavailable:
    '현재 개인 메모리 계약은 팩트 벡터나 검증된 신뢰도 점수를 제공하지 않습니다. 임의 점수를 만들지 않습니다.',
  usageEvidenceTitle: '활용 이력 및 사용 지표',
  usageEvidenceUnavailable:
    '메모리별 사용 원장 API가 제공되지 않아 호출 횟수나 영향도를 추정하지 않습니다.',
  kmsEvidenceTitle: 'KMS 및 보안 키 바인딩',
  kmsEvidenceUnavailable:
    '현재 API는 명시적 메모리 저장 정책만 확인하며, 메모리별 KMS 키 바인딩 증거는 반환하지 않습니다.',
  governedUnavailable: '검증 데이터 미제공',
  evidenceAvailable: '서버 검증 완료',
  confidenceLabel: '검증 신뢰도',
  factVectorEmpty: '서버가 반환한 팩트 벡터가 없습니다.',
  useCount: '적용 횟수',
  lastUsedAt: '최근 적용',
  neverUsed: '적용 이력 없음',
  encryptionProvider: '암호화 제공자',
  encryptionKeyVersion: '키 버전',
  encryptionFingerprint: '키 참조 지문',
  evidenceValueMissing: '기능은 사용 가능하지만 이 메모리의 검증 값은 반환되지 않았습니다.',
  addMemory: '선호 추가',
  editMemory: '선호 수정',
  deleteMemory: '선호 삭제',
  narrowMemoryScope: '적용 스코프 축소',
  narrowMemoryScopeDescription: '현재 허용 범위 안에서 이 선호를 사용할 메뉴를 줄입니다.',
  resetMemoryExpiry: '만료일 재설정',
  resetMemoryExpiryDescription: '자동 만료 시각을 바꾸거나 사용자 만료를 해제합니다.',
  memoryScope: '적용 스코프',
  memoryScopes: {
    ASK: 'AI에게 묻기',
    RESEARCH: 'Deep Research',
    PROPOSALS: 'AI 제안함',
    ROUTINES: '나의 AI 루틴',
    ARTIFACTS: '결과물 스튜디오',
  },
  scopeDialogTitle: '적용 스코프 축소',
  scopeDialogDescription: '기존 스코프의 부분집합만 선택할 수 있으며 하나 이상은 남겨야 합니다.',
  scopeRequired: '적용 스코프를 하나 이상 선택해 주세요.',
  expiryDialogTitle: '만료일 재설정',
  expiryDialogDescription: '시간대가 포함된 새 만료 시각을 지정합니다.',
  expiryValue: '만료 일시',
  clearExpiry: '사용자 만료일 해제',
  expiresAt: '만료',
  neverExpires: '사용자 만료 없음',
  memoryKind: '선호 유형',
  memoryKinds: {
    RESPONSE_LENGTH: '응답 길이',
    OUTPUT_FORMAT: '출력 형식',
    TONE: '말투',
    WORKING_STYLE: '업무 방식',
  },
  memoryValue: '기억할 내용',
  memorySource: '사용자 직접 입력',
  memoryStates: { ACTIVE: '사용', DISABLED: '일시 중지', DELETED: '삭제됨', EXPIRED: '만료됨' },
  sensitiveWarning: '비밀번호, 인증 토큰, 주민번호, 계좌·카드 번호는 입력하지 마세요.',
  save: '저장',
  saving: '저장 중',
  saved: '개인 AI 설정을 저장했습니다.',
  cancel: '취소',
  deleteTitle: '이 선호를 삭제할까요?',
  deleteDescription: '삭제한 선호는 다시 사용할 수 없습니다.',
  deleteConfirm: '삭제',
  clearTitle: '개인 AI 데이터 정리',
  clearDescription:
    'AI 제안은 즉시 내 제안함에서 숨기고, 나머지 개인 데이터는 삭제 요청을 접수합니다.',
  clearAction: '데이터 정리',
  clearConfirm: '정리 요청',
  clearing: '요청 중',
  clearScopes: {
    PROPOSALS: 'AI 제안함 비우기',
    ROUTINE: '개인 AI 루틴',
    MEMORY: '명시적 메모리',
    ARTIFACT: '결과물과 버전',
    ARTIFACT_EXPORT: '내보내기 요청',
  },
  clearEvidence: '처리 증거',
  proposalHidden: '제안함에서 숨긴 항목',
  deletionRequested: '삭제 요청 접수',
  requestState: {
    REQUESTED: '접수됨',
    RUNNING: '처리 중',
    PARTIAL: '일부 처리',
    COMPLETED: '완료',
    BLOCKED_LEGAL_HOLD: '법적 보존으로 차단',
    FAILED: '실패',
  },
  receiptId: '요청 ID',
  requestedAt: '요청 시각',
  executionUnavailable:
    '현재 버전은 삭제 요청 접수까지만 지원합니다. 실행 완료로 표시하지 않습니다.',
  executionRunning: '서버 삭제 작업 상태를 조회하고 있습니다.',
  completionUnverified: '완료 주장 권한 없음',
  completionVerificationAvailable: '완료 증거 확인 가능',
  completedAt: '완료 시각',
  sourceUnaffected:
    '메일·일정·업무 원본 데이터와 필수 감사 메타데이터는 삭제 대상이 아닙니다. 백업 삭제와 암호화 키 폐기는 지원하지 않습니다.',
  privacyUnavailable: '보존·삭제 정책을 볼 권한이 없어 해당 영역을 표시하지 않습니다.',
  retentionTitle: '보존 경계',
  retentionDays: '보존 {{days}}일 · 삭제 유예 {{grace}}일',
  legalHold: '법적 보존 적용',
  noLegalHold: '법적 보존 없음',
  separator: '·',
  revisionPrefix: 'r',
} as const;

export const DWAION_PERSONAL_CONTROLS_COPY_EN: DwaionPersonalControlsCopy = {
  eyebrow: 'Personal AI governance',
  title: 'My AI controls',
  description:
    'Manage the information boundaries DWAI·ON may reference, explicit preferences, and retention or deletion requests in one place.',
  tabsLabel: 'Personal AI control sections',
  tabs: {
    sources: 'Work signal access',
    memories: 'Explicit memories',
    cleanup: 'Clean up data',
    compliance: 'Compliance',
  },
  livePolicy: 'Server policy response received',
  partialPolicy: 'Some policy responses unavailable',
  savedMemoryCount: 'Saved preferences',
  deletionUnavailableBadge: 'Deletion execution unavailable',
  revalidate: 'Recheck access and policy',
  governanceTitle: 'Security boundary evidence',
  governanceDescription: 'Personal AI safety boundaries confirmed by the current API contract.',
  governanceFacts: {
    inference: 'Conversation inference',
    sensitive: 'Sensitive memories',
    credential: 'Credential storage',
    team: 'Team-shared memory',
    external: 'External action without approval',
  },
  allowed: 'Allowed',
  blocked: 'Blocked',
  boundaryUnknown: 'Not verified',
  deletionStatusError:
    'The deletion request was accepted, but its latest status could not be verified. Do not treat it as completed. You can retry the status check.',
  auditUnavailable: 'A personal audit-event list API is not available.',
  cleanupTitle: 'Data deletion and cleanup',
  cleanupDescription:
    'The proposal inbox is hidden immediately; other personal data starts a server deletion job.',
  cleanupBoundary: 'Source work, mail, calendar data, and required audit metadata are retained.',
  loading: 'Loading personal AI controls',
  errorTitle: 'Personal AI controls could not be loaded',
  permissionTitle: 'You do not have access to personal AI controls',
  permissionDescription: 'Check the personal AI permissions for the current account.',
  emptyTitle: 'No AI information sources are available',
  emptyDescription: 'Source-level consent appears here when your organization enables sources.',
  retry: 'Retry',
  partial: 'Some controls could not be verified.',
  commandFailed: 'The request could not be completed. Try again shortly.',
  revisionConflict: 'These controls changed elsewhere. Refresh before trying again.',
  memoryPreferenceTitle: 'Explicit memory storage',
  memoryPreferenceDescription:
    'Only preferences you enter are encrypted and stored. Conversations are not inferred and credentials are never stored.',
  memoryPreferenceStates: { UNSET: 'Choice required', DISABLED: 'Off', ENABLED: 'On' },
  memoryEffective: 'Answer personalization on',
  memoryNotEffective: 'Answer personalization off',
  memoryStorageTitle: 'Store preferences',
  memoryStorageDescription:
    'Encrypt preferences you enter so you can review, edit, or delete them at any time.',
  runtimePreferenceTitle: 'Apply preferences to answers',
  runtimePreferenceDescription:
    'Send active preferences to answer generation for presentation only. They cannot change facts, access, or policy.',
  runtimeRequiresStorage: 'Turn on explicit memory storage before applying preferences to answers.',
  runtimeUnavailable:
    'The connected runtime does not support answer personalization. Preferences remain stored and are not sent to answer generation.',
  sourceTitle: 'Work signal analysis scope',
  sourceDescription:
    'Choose each source independently. Effective sources expose reference identifiers only to routine dry runs.',
  sourceLabels: { WORK_ITEM: 'Work items', MAIL: 'Mail', CALENDAR: 'Calendar' },
  sourceDescriptions: {
    WORK_ITEM: 'Identifiers and status visible to the current account',
    MAIL: 'Mail identifiers and metadata visible to the current account',
    CALENDAR: 'Schedule identifiers and timing visible to the current account',
  },
  unavailable: 'Unavailable',
  enabled: 'On',
  disabled: 'Off',
  effective: 'Effective',
  notEffective: 'Not applied',
  referenceOnly: 'No raw content copy',
  routineScope: 'Personal routine validation only',
  unknownScope: 'Application scope not verified',
  memoryTitle: 'Preferences I saved',
  memoryDescription:
    'Store response format, length, tone, or working style only. Account, payment, and regulated identifiers are rejected.',
  memoryEmpty: 'No saved preferences',
  memoryFiltersLabel: 'Memory categories',
  memoryFilters: {
    ALL: 'All',
    MANUAL: 'Manual',
    AI_APPROVED: 'AI approved',
    EXPIRING: 'Expiring',
  },
  automaticInferenceBlocked:
    'Current server policy blocks conversation inference. No AI-approved memory is created or inferred.',
  automaticInferenceUnknown:
    'The automatic memory-inference policy could not be verified, so no AI-approved memory is shown.',
  expiringMemoryEmpty: 'No preference expires within the next 30 days.',
  selectMemory: 'View details',
  memoryDetailTitle: 'Selected memory details and evidence',
  memoryProvenanceTitle: 'Provenance and change evidence',
  createdAt: 'Created',
  updatedAt: 'Last changed',
  memoryId: 'Memory ID',
  memoryRevision: 'Server revision',
  memoryOrigin: 'Origin',
  memorySourceType: 'Source type',
  manualMemory: 'Entered explicitly by you',
  pauseMemory: 'Pause memory',
  resumeMemory: 'Resume memory',
  memoryGovernanceEvidenceTitle: 'Advanced memory evidence',
  memoryGovernanceEvidenceDescription:
    'Only server-verified data is shown. Missing metrics are never estimated.',
  factVectorTitle: 'Verified fact vectors and confidence',
  factVectorUnavailable:
    'The personal-memory contract does not provide fact vectors or a verified confidence score. No score is invented.',
  usageEvidenceTitle: 'Usage trail and metrics',
  usageEvidenceUnavailable:
    'A per-memory usage-ledger API is unavailable, so call counts and influence are not estimated.',
  kmsEvidenceTitle: 'KMS and security-key binding',
  kmsEvidenceUnavailable:
    'The API confirms the explicit-memory storage policy but does not return per-memory KMS-binding evidence.',
  governedUnavailable: 'Verified data unavailable',
  evidenceAvailable: 'Verified by server',
  confidenceLabel: 'Verified confidence',
  factVectorEmpty: 'The server returned no fact vectors for this memory.',
  useCount: 'Application count',
  lastUsedAt: 'Last applied',
  neverUsed: 'No application recorded',
  encryptionProvider: 'Encryption provider',
  encryptionKeyVersion: 'Key version',
  encryptionFingerprint: 'Key reference fingerprint',
  evidenceValueMissing:
    'The capability is available, but no verified value was returned for this memory.',
  addMemory: 'Add preference',
  editMemory: 'Edit preference',
  deleteMemory: 'Delete preference',
  narrowMemoryScope: 'Narrow application scope',
  narrowMemoryScopeDescription:
    'Reduce which areas may use this preference within its current scope.',
  resetMemoryExpiry: 'Reset expiry',
  resetMemoryExpiryDescription: 'Change the automatic expiry or remove the user-set expiry.',
  memoryScope: 'Application scope',
  memoryScopes: {
    ASK: 'Ask AI',
    RESEARCH: 'Deep Research',
    PROPOSALS: 'AI proposals',
    ROUTINES: 'My AI routines',
    ARTIFACTS: 'Artifact studio',
  },
  scopeDialogTitle: 'Narrow application scope',
  scopeDialogDescription: 'Keep at least one area. You can only select from the current scope.',
  scopeRequired: 'Select at least one application scope.',
  expiryDialogTitle: 'Reset expiry',
  expiryDialogDescription: 'Choose a new timezone-aware expiry date and time.',
  expiryValue: 'Expiry date and time',
  clearExpiry: 'Remove user-set expiry',
  expiresAt: 'Expires',
  neverExpires: 'No user-set expiry',
  memoryKind: 'Preference type',
  memoryKinds: {
    RESPONSE_LENGTH: 'Response length',
    OUTPUT_FORMAT: 'Output format',
    TONE: 'Tone',
    WORKING_STYLE: 'Working style',
  },
  memoryValue: 'Preference',
  memorySource: 'Entered by you',
  memoryStates: { ACTIVE: 'Active', DISABLED: 'Paused', DELETED: 'Deleted', EXPIRED: 'Expired' },
  sensitiveWarning: 'Do not enter passwords, tokens, government IDs, bank, or card numbers.',
  save: 'Save',
  saving: 'Saving',
  saved: 'Personal AI controls saved.',
  cancel: 'Cancel',
  deleteTitle: 'Delete this preference?',
  deleteDescription: 'A deleted preference cannot be used again.',
  deleteConfirm: 'Delete',
  clearTitle: 'Clean up personal AI data',
  clearDescription:
    'AI proposals are hidden immediately; other personal domains create a deletion request.',
  clearAction: 'Clean up data',
  clearConfirm: 'Submit request',
  clearing: 'Submitting',
  clearScopes: {
    PROPOSALS: 'Clear AI proposal inbox',
    ROUTINE: 'Personal AI routines',
    MEMORY: 'Explicit memories',
    ARTIFACT: 'Artifacts and versions',
    ARTIFACT_EXPORT: 'Export requests',
  },
  clearEvidence: 'Processing evidence',
  proposalHidden: 'Items hidden from proposals',
  deletionRequested: 'Deletion request accepted',
  requestState: {
    REQUESTED: 'Requested',
    RUNNING: 'Running',
    PARTIAL: 'Partially completed',
    COMPLETED: 'Completed',
    BLOCKED_LEGAL_HOLD: 'Blocked by legal hold',
    FAILED: 'Failed',
  },
  receiptId: 'Request ID',
  requestedAt: 'Requested at',
  executionUnavailable:
    'This release accepts deletion requests only. It does not claim execution is complete.',
  executionRunning: 'Checking the server deletion job state.',
  completionUnverified: 'Completion claim unavailable',
  completionVerificationAvailable: 'Completion evidence can be verified',
  completedAt: 'Completed at',
  sourceUnaffected:
    'Source mail, calendar, work records, and required audit metadata are unaffected. Backup deletion and encryption-key destruction are unavailable.',
  privacyUnavailable:
    'Retention and deletion controls are hidden because permission is unavailable.',
  retentionTitle: 'Retention boundaries',
  retentionDays: 'Retain {{days}} days · deletion grace {{grace}} days',
  legalHold: 'Legal hold active',
  noLegalHold: 'No legal hold',
  separator: '·',
  revisionPrefix: 'r',
};

export type DwaionPersonalControlsCopy = WidenCopy<typeof DWAION_PERSONAL_CONTROLS_COPY_KO>;
