export const appGovernance = {
  metrics: {
    activeAssignments: 1,
    pendingApprovals: 1,
    reviewsDueSoon: 1,
    resourcesWithoutOwner: 0,
  },
  responsibilities: [
    {
      code: 'APP_ACCESS_MANAGER',
      displayName: 'App access fulfiller',
      description: 'Activates approved app administration packages.',
      riskTier: 'L2',
      sortOrder: 1,
    },
  ],
  principals: [{ type: 'USER', ref: '40', displayName: 'Mail target administrator' }],
  resourceSets: [
    {
      resourceSetId: 'rs-mail',
      key: 'RS_MAIL',
      name: 'Mail administration',
      description: 'Tenant Mail administration boundary',
      lifecycleState: 'ACTIVE',
      version: 3,
      resources: [{ resourceType: 'APP', resourceKey: 'APP.MAIL', resourceName: 'Mail' }],
    },
  ],
  assignments: [
    {
      assignmentId: 'assignment-mail-owner',
      principalType: 'USER',
      principalRef: '20',
      principalName: 'Mail owner',
      responsibilityCode: 'APP_OWNER',
      resourceSetId: 'rs-mail',
      resourceSetKey: 'RS_MAIL',
      resourceSetName: 'Mail administration',
      assignmentSource: 'GOVERNED_DIRECT',
      lifecycleState: 'ACTIVE',
      validFrom: '2026-09-01T00:00:00Z',
      validTo: null,
      reviewDueAt: '2026-12-01T00:00:00Z',
      justification: 'Named owner for the Mail tenant boundary.',
      requestedBy: 10,
      requestedByName: 'Access requester',
      approvedBy: 20,
      approvedByName: 'Access approver',
      approvedAt: '2026-09-01T01:00:00Z',
      decisionReason: 'Ownership evidence verified.',
      firstApproverBootstrapEligible: false,
      version: 1,
      createdAt: '2026-09-01T00:00:00Z',
      updatedAt: '2026-09-01T01:00:00Z',
    },
  ],
  presetCatalog: [
    {
      presetCode: 'MAIL_ADMIN',
      productKey: 'mail',
      appResourceKey: 'APP.MAIL',
      displayName: 'Mail administrator',
      description: 'Minimum Mail administration package.',
      responsibilityCode: 'APP_ACCESS_MANAGER',
      riskTier: 'HIGH',
      catalogVersion: 4,
      requestable: true,
      duties: [
        {
          dutyCode: 'MAIL_POLICY_ADMIN',
          resourceKey: 'APP.MAIL',
          riskTier: 'HIGH',
          auditPolicyException: false,
          capabilityContractKeys: ['mail.admin.policy.update'],
        },
      ],
    },
  ],
  presetAssignments: [
    {
      presetAssignmentId: 'preset-mail-1',
      presetCode: 'MAIL_ADMIN',
      productKey: 'mail',
      presetName: 'Mail administrator',
      principalType: 'USER',
      principalRef: '40',
      principalName: 'Mail target administrator',
      resourceSetId: 'rs-mail',
      resourceSetKey: 'RS_MAIL',
      resourceSetName: 'Mail administration',
      responsibilityAssignmentId: 'assignment-mail-owner',
      assignmentSource: 'GOVERNED_PRESET',
      requestChannel: 'GOVERNANCE',
      lifecycleState: 'APPROVED',
      validFrom: null,
      validTo: '2026-12-31T00:00:00Z',
      reviewDueAt: '2026-12-01T00:00:00Z',
      justification: 'Time-bound Mail policy administration coverage.',
      requestedBy: 10,
      requestedByName: 'Request owner',
      approvedBy: 20,
      approvedByName: 'Security approver',
      approvedAt: '2026-09-17T02:00:00Z',
      decisionReason: 'Scope and expiry verified.',
      activatedBy: null,
      activatedByName: null,
      activatedAt: null,
      activationReason: null,
      version: 2,
      catalogVersion: 4,
      createdAt: '2026-09-17T01:00:00Z',
      updatedAt: '2026-09-17T02:00:00Z',
      duties: [
        {
          assignmentId: 'duty-mail-1',
          dutyCode: 'MAIL_POLICY_ADMIN',
          lifecycleState: 'APPROVED',
          version: 1,
        },
      ],
    },
  ],
  presetReviews: [],
};
