import type { ApprovalHome } from '@dwp-frontend/shared-utils';

export const APPROVAL_MEMBER_PERMISSIONS = [
  {
    resourceType: 'APP',
    resourceKey: 'APP.APPROVALS',
    permissionCode: 'VIEW',
    effect: 'ALLOW' as const,
  },
  ...[
    ['ACTION.APPROVAL_TASK', 'VIEW'],
    ['ACTION.APPROVAL_TASK', 'UPDATE'],
    ['ACTION.APPROVAL_TASK', 'APPROVE'],
    ['ACTION.APPROVAL_REQUEST', 'VIEW'],
    ['ACTION.APPROVAL_REQUEST', 'CREATE'],
    ['ACTION.APPROVAL_REQUEST', 'UPDATE'],
    ['ACTION.APPROVAL_DELEGATION', 'VIEW'],
    ['ACTION.APPROVAL_DELEGATION', 'MANAGE'],
  ].map(([resourceKey, permissionCode]) => ({
    resourceType: 'ACTION',
    resourceKey,
    permissionCode,
    effect: 'ALLOW' as const,
  })),
];

export const APPROVAL_HOME_FIXTURE = {
  generatedAt: '2026-08-14T02:30:00Z',
  metrics: {
    pending: 4,
    dueToday: 3,
    overdue: 1,
    needsInformation: 1,
    myRequestsInFlight: 2,
    averageCycleHours: 5.4,
    slaCompliancePercent: 96,
  },
  focusQueue: [
    {
      taskId: 'approval-task-1',
      requestId: 'approval-request-1',
      requestNumber: 'APR-20260814-001',
      title: '고객 분석 환경 접근 연장',
      summary: '보안 정책 만료 전 접근 권한을 재검토합니다.',
      workflowNameKo: '시스템 접근 예외',
      workflowNameEn: 'Access exception',
      stepKey: 'SECURITY_REVIEW',
      stepName: '보안 검토',
      stepSequence: 1,
      requesterName: '김태현',
      requesterOrgName: 'AI Platform팀',
      status: 'PENDING',
      priority: 'URGENT',
      dataClassification: 'CONFIDENTIAL',
      riskScore: 91,
      submittedAt: '2026-08-14T00:30:00Z',
      dueAt: '2026-08-14T03:30:00Z',
      version: 0,
    },
    {
      taskId: 'approval-task-2',
      requestId: 'approval-request-2',
      requestNumber: 'APR-20260814-002',
      title: '신규 협력사 보안 예외',
      summary: '협력사 온보딩 전에 보안 통제를 검토합니다.',
      workflowNameKo: '협력사 등록',
      workflowNameEn: 'Supplier onboarding',
      stepKey: 'SECURITY_REVIEW',
      stepName: '보안 검토',
      stepSequence: 2,
      requesterName: '박지호',
      requesterOrgName: '구매혁신팀',
      status: 'PENDING',
      priority: 'HIGH',
      dataClassification: 'INTERNAL',
      riskScore: 72,
      submittedAt: '2026-08-13T08:00:00Z',
      dueAt: '2026-08-14T07:00:00Z',
      version: 0,
    },
  ],
  recentRequests: [
    {
      requestId: 'approval-request-3',
      requestNumber: 'APR-20260813-003',
      title: 'GPU 증설 투자 검토',
      summary: 'AI 개발 환경의 GPU 증설 예산을 검토합니다.',
      workflowNameKo: '구매·비용 승인',
      workflowNameEn: 'Capital expenditure',
      currentStepKey: 'PROCUREMENT_REVIEW',
      currentStepName: '구매 조건 검토',
      currentStepSequence: 2,
      totalSteps: 3,
      status: 'IN_REVIEW',
      priority: 'HIGH',
      dataClassification: 'CONFIDENTIAL',
      latestInformationRequest: null,
      submittedAt: '2026-08-13T05:00:00Z',
      dueAt: '2026-08-15T05:00:00Z',
      completedAt: null,
      version: 2,
    },
  ],
  flow: [
    { stage: 'IN_REVIEW', count: 7, atRisk: 2 },
    { stage: 'NEEDS_INFO', count: 1, atRisk: 1 },
    { stage: 'APPROVED', count: 12, atRisk: 0 },
  ],
  insights: [
    {
      key: 'overdue',
      tone: 'RISK',
      titleKo: '기한을 넘긴 결정이 있습니다',
      titleEn: 'A decision is overdue',
      detailKo: '위험도가 높은 항목을 먼저 검토하세요.',
      detailEn: 'Review the highest-risk item first.',
      route: '/approvals/inbox',
    },
  ],
  administrator: false,
  adminPulse: null,
} satisfies ApprovalHome;
