export const AUDIT_POLICY_IMPACT_SNAPSHOT = {
  observedAt: '2026-08-10T12:00:00Z',
  coverageState: 'COMPLETE_INTERNAL_AUDIT_EVENT_OWNER',
  includedOwners: ['PLATFORM_SYS_AUDIT_EVENTS'],
  exclusions: [
    'EXTERNAL_PRODUCT_DATA_RETENTION',
    'EXTERNAL_SHARING_POPULATIONS',
    'EXTERNAL_LEGAL_HOLD_POPULATIONS',
    'FILTER_SPECIFIC_EXPORT_POPULATIONS',
  ],
  auditEventCount: 1284,
  affectedAuditEventCount: 0,
  affectedActorCount: 0,
  affectedTargetCount: 0,
  standardRetentionEventCount: 900,
  extendedRetentionEventCount: 384,
  legalHoldEventCount: 12,
  standardRetentionAffectedEventCount: 0,
  extendedRetentionAffectedEventCount: 0,
  highRiskClassificationAffectedEventCount: 0,
  exportableEventCountBefore: 10000,
  exportableEventCountAfter: 10000,
  integrityProtectedEventCountBefore: 1284,
  integrityProtectedEventCountAfter: 1284,
};

export const AUDIT_POLICY_REVISION_PAGE = {
  items: [
    {
      revisionId: '51000000-0000-0000-0000-000000000001',
      revisionNumber: 1,
      lifecycleState: 'PUBLISHED',
      standardRetentionDays: 365,
      extendedRetentionDays: 2555,
      exportLimitRows: 10000,
      requireExportReason: true,
      integrityEnabled: true,
      highRiskThreshold: 70,
      changeReason: 'Initial governed baseline',
      diff: {},
      contentSha256: 'a'.repeat(64),
      impactSnapshot: AUDIT_POLICY_IMPACT_SNAPSHOT,
      impactSha256: 'b'.repeat(64),
      createdBy: 'system',
      createdAt: '2026-08-11T00:00:00Z',
      publishedAt: '2026-08-11T00:00:00Z',
    },
  ],
  limit: 100,
  hasMore: false,
};

export const ADMIN_TRUTH_AUDIT_REVISION_PAGE = {
  items: [
    {
      revisionId: 'revision-2',
      revisionNumber: 2,
      lifecycleState: 'IN_REVIEW',
      standardRetentionDays: 540,
      extendedRetentionDays: 2555,
      exportLimitRows: 5000,
      requireExportReason: true,
      integrityEnabled: true,
      highRiskThreshold: 70,
      baselineRevisionId: 'revision-1',
      rollbackOfRevisionId: null,
      incidentCaseId: null,
      changeReason: 'Extend standard evidence retention after legal review.',
      diff: {
        standardRetentionDays: { before: 365, after: 540 },
        exportLimitRows: { before: 10000, after: 5000 },
      },
      contentSha256: 'b'.repeat(64),
      impactSnapshot: {
        observedAt: '2026-09-17T01:00:00Z',
        coverageState: 'COMPLETE_INTERNAL_AUDIT_EVENT_OWNER',
        includedOwners: ['PLATFORM_SYS_AUDIT_EVENTS'],
        exclusions: [
          'EXTERNAL_PRODUCT_DATA_RETENTION',
          'EXTERNAL_SHARING_POPULATIONS',
          'EXTERNAL_LEGAL_HOLD_POPULATIONS',
          'FILTER_SPECIFIC_EXPORT_POPULATIONS',
        ],
        auditEventCount: 240,
        affectedAuditEventCount: 48,
        affectedActorCount: 12,
        affectedTargetCount: 19,
        standardRetentionEventCount: 180,
        extendedRetentionEventCount: 60,
        legalHoldEventCount: 3,
        standardRetentionAffectedEventCount: 40,
        extendedRetentionAffectedEventCount: 8,
        highRiskClassificationAffectedEventCount: 0,
        exportableEventCountBefore: 240,
        exportableEventCountAfter: 240,
        integrityProtectedEventCountBefore: 240,
        integrityProtectedEventCountAfter: 240,
      },
      impactSha256: 'c'.repeat(64),
      createdBy: '1',
      createdAt: '2026-09-17T01:00:00Z',
      submittedBy: '1',
      submittedAt: '2026-09-17T01:10:00Z',
      version: 2,
      approval: {
        approvalId: 'approval-revision-2',
        lifecycleState: 'PENDING',
        requestedBy: '1',
        requestedAt: '2026-09-17T01:10:00Z',
        expiresAt: '2026-09-18T01:10:00Z',
        decidedBy: null,
        decidedAt: null,
        decisionReason: null,
        version: 1,
      },
    },
  ],
  limit: 100,
  hasMore: true,
};
