import type {
  CalendarAdminOverview,
  CalendarAvailability,
  CalendarBooking,
  CalendarEvent,
  CalendarHome,
  CalendarResource,
  CalendarShare,
  CalendarSummary,
  CalendarTrashedEvent,
  CompanyCalendar,
  CompanyCalendarEvent,
  HrAbsenceWorkspace,
  HrBenefitsWorkspace,
  HrDomainOperations,
  HrEmployeeContext,
  HrHomeOverview,
  HrPayWorkspace,
  HrTalentWorkspace,
  HrTimeWorkspace,
  ServiceCatalog,
  ServiceRequestSummary,
} from '@dwp-frontend/shared-utils';

export * from './product-area-approval-fixtures';

const HR_SERVICE_DEFINITIONS = [
  [
    'people.personal-data-change',
    'Personal data change',
    'Update governed personal and contact information.',
  ],
  [
    'people.payroll-question',
    'Payroll question',
    'Ask a confidential question about a pay statement or cycle.',
  ],
  [
    'people.benefits-support',
    'Benefits support',
    'Get help with eligibility, coverage, or enrollment.',
  ],
  [
    'people.onboarding-support',
    'Onboarding support',
    'Resolve a new-hire or role-transition onboarding issue.',
  ],
  [
    'people.employment-certificate',
    'Employment certificate',
    'Request a verified employment certificate.',
  ],
  ['people.hr-general', 'General HR help', 'Route an HR question to the right specialist team.'],
] as const;

export const HR_SERVICE_CATALOG_FIXTURE = {
  categories: [
    {
      categoryKey: 'PEOPLE',
      name: 'People & HR',
      description: 'Personal, employment, pay, benefits, and lifecycle help.',
      iconKey: 'users-round',
      tone: 'teal',
      sortOrder: 20,
    },
  ],
  items: HR_SERVICE_DEFINITIONS.map(([serviceKey, name, description], index) => ({
    serviceKey,
    categoryKey: 'PEOPLE',
    name,
    description,
    ownerGroup: index === 1 ? 'PAYROLL_OPERATIONS' : 'PEOPLE_SERVICES',
    lifecycleState: 'ACTIVE' as const,
    requestSchema: {
      fields: [
        {
          key: 'detail',
          type: 'TEXTAREA' as const,
          labelKo: '요청 내용',
          labelEn: 'Request detail',
          required: true,
        },
      ],
    },
    schemaVersion: 1,
    slaHours: index === 1 ? 24 : 16,
    estimatedResolutionHours: index === 1 ? 24 : 12,
    dataClassification: index === 1 ? ('RESTRICTED' as const) : ('CONFIDENTIAL' as const),
    featured: index < 3,
    tags: ['HR', 'EMPLOYEE_SERVICE'],
    version: 1,
  })),
  activeCount: HR_SERVICE_DEFINITIONS.length,
  generatedAt: '2026-08-11T00:20:00Z',
} satisfies ServiceCatalog;

export const HR_SERVICE_REQUESTS_FIXTURE = [
  {
    requestId: 'service-request-people-001',
    requestNumber: 'HR-2026-0811-001',
    serviceKey: 'people.benefits-support',
    serviceNameKo: '복리후생 지원',
    serviceNameEn: 'Benefits support',
    summary: 'Confirm dependent enrollment evidence',
    dataClassification: 'CONFIDENTIAL',
    status: 'AWAITING_REQUESTER',
    priority: 'NORMAL',
    assignedGroup: 'People Services',
    assignedTo: null,
    submittedAt: '2026-08-10T02:00:00Z',
    slaDueAt: '2026-08-11T08:00:00Z',
    updatedAt: '2026-08-11T00:10:00Z',
    version: 2,
  },
] satisfies ServiceRequestSummary[];

export const HR_EMPLOYEE_FIXTURE = {
  personId: 'person-session-user',
  displayName: '박현우',
  businessTitle: 'Digital Platform lead',
  organizationName: 'Digital Workplace',
  managerDisplayName: '김민준',
  directReportCount: 2,
} satisfies HrEmployeeContext;

export const HR_TIME_FIXTURE = {
  employee: HR_EMPLOYEE_FIXTURE,
  card: {
    timeCardId: 'time-card-2026-w33',
    periodStart: '2026-08-10',
    periodEnd: '2026-08-16',
    status: 'OPEN',
    scheduledMinutes: 2400,
    recordedMinutes: 1020,
    exceptionCount: 1,
    dataOrigin: 'DWP_HRIS',
    version: 3,
  },
  entries: [
    {
      timeEntryId: 'time-entry-2026-08-10',
      workDate: '2026-08-10',
      entryType: 'REGULAR',
      minutes: 510,
      workMode: 'OFFICE',
      note: 'Seoul HQ',
      version: 1,
    },
    {
      timeEntryId: 'time-entry-2026-08-11',
      workDate: '2026-08-11',
      entryType: 'REGULAR',
      minutes: 510,
      workMode: 'REMOTE',
      note: null,
      version: 1,
    },
  ],
  exceptions: [
    {
      exceptionId: 'time-exception-001',
      exceptionCode: 'MISSING_BREAK_CONFIRMATION',
      severity: 'WARNING',
      occurredOn: '2026-08-11',
      message: 'Confirm the recorded break before submission.',
      lifecycleState: 'OPEN',
      resolutionNote: null,
    },
  ],
  teamQueue: [
    {
      itemId: 'time-card-minseo-w33',
      domain: 'TIME',
      personId: 'person-minseo-kim',
      employeeName: 'Minseo Kim',
      employeeTitle: 'Product design lead',
      summary: 'Weekly time card · 40h',
      status: 'SUBMITTED',
      submittedAt: '2026-08-11T00:05:00Z',
      version: 1,
    },
  ],
} satisfies HrTimeWorkspace;

export const HR_ABSENCE_FIXTURE = {
  employee: HR_EMPLOYEE_FIXTURE,
  balances: [
    {
      planId: 'leave-plan-annual',
      planKey: 'ANNUAL_LEAVE',
      planName: 'Annual leave',
      grantedMinutes: 9600,
      usedMinutes: 3360,
      pendingMinutes: 480,
      availableMinutes: 5760,
      asOf: '2026-08-11',
      dataOrigin: 'DWP_HRIS',
    },
  ],
  requests: [
    {
      requestId: 'leave-request-001',
      planId: 'leave-plan-annual',
      planName: 'Annual leave',
      startAt: '2026-08-21T00:00:00Z',
      endAt: '2026-08-21T09:00:00Z',
      requestedMinutes: 480,
      status: 'SUBMITTED',
      reason: 'Personal appointment',
      submittedAt: '2026-08-10T07:00:00Z',
      decisionNote: null,
      cancelledAt: null,
      cancellationNote: null,
      version: 1,
    },
  ],
  teamQueue: [
    {
      itemId: 'leave-request-team-001',
      domain: 'ABSENCE',
      personId: 'person-minseo-kim',
      employeeName: 'Minseo Kim',
      employeeTitle: 'Product design lead',
      summary: 'Annual leave · Aug 24',
      status: 'SUBMITTED',
      submittedAt: '2026-08-10T08:30:00Z',
      version: 1,
    },
  ],
  teamCalendar: [
    {
      requestId: 'leave-request-calendar-001',
      personId: 'person-jinho-park',
      employeeName: 'Jinho Park',
      employeeTitle: 'Network automation engineer',
      planName: 'Annual leave',
      startAt: '2026-08-18T00:00:00Z',
      endAt: '2026-08-18T09:00:00Z',
      status: 'APPROVED',
    },
  ],
} satisfies HrAbsenceWorkspace;

export const HR_BENEFITS_FIXTURE = {
  employee: HR_EMPLOYEE_FIXTURE,
  plans: [
    {
      planId: 'benefit-health-core',
      planType: 'HEALTH',
      name: 'Core health coverage',
      providerName: 'Enterprise Benefits',
      coverageLevel: 'FAMILY',
      status: 'ACTIVE',
      effectiveStart: '2026-01-01',
      effectiveEnd: null,
    },
    {
      planId: 'benefit-learning',
      planType: 'LEARNING',
      name: 'Learning allowance',
      providerName: 'DWP People',
      coverageLevel: 'EMPLOYEE',
      status: 'ACTIVE',
      effectiveStart: '2026-01-01',
      effectiveEnd: null,
    },
  ],
  windows: [
    {
      windowId: 'benefit-window-2027',
      name: '2027 annual enrollment',
      windowType: 'OPEN_ENROLLMENT',
      opensAt: '2026-08-01T00:00:00Z',
      closesAt: '2026-08-23T09:00:00Z',
      lifecycleState: 'OPEN',
    },
  ],
  referenceData: true,
} satisfies HrBenefitsWorkspace;

export const HR_PAY_FIXTURE = {
  employee: HR_EMPLOYEE_FIXTURE,
  nextCycle: {
    payCycleId: 'pay-cycle-2026-08',
    name: 'August payroll',
    periodStart: '2026-08-01',
    periodEnd: '2026-08-31',
    payDate: '2026-08-25',
    status: 'VALIDATING',
    timeValidated: true,
    absenceValidated: true,
    sourceConfirmed: false,
    dataOrigin: 'REFERENCE',
  },
  statements: [
    {
      statementId: 'pay-statement-2026-07',
      periodLabel: 'July 2026',
      availabilityState: 'PUBLISHED',
      publishedAt: '2026-07-25T00:00:00Z',
      downloadable: false,
    },
  ],
  monetaryDataRedacted: true,
} satisfies HrPayWorkspace;

export const HR_TALENT_FIXTURE = {
  employee: HR_EMPLOYEE_FIXTURE,
  journeys: [
    {
      journeyId: 'journey-leadership',
      name: 'Leadership onboarding',
      journeyType: 'ROLE_TRANSITION',
      progressPercent: 68,
      targetDate: '2026-09-30',
      status: 'ACTIVE',
    },
  ],
  goals: [
    {
      goalId: 'goal-platform-reliability',
      title: 'Improve platform service reliability',
      goalType: 'PERFORMANCE',
      progressPercent: 72,
      dueDate: '2026-12-31',
      status: 'ON_TRACK',
      version: 2,
    },
  ],
  learning: [
    {
      learningId: 'learning-data-governance',
      title: 'Responsible data operations',
      providerName: 'DWP Academy',
      required: true,
      progressPercent: 40,
      dueDate: '2026-09-15',
      status: 'IN_PROGRESS',
    },
  ],
} satisfies HrTalentWorkspace;

export const HR_HOME_FIXTURE = {
  asOf: '2026-08-11',
  generatedAt: '2026-08-11T00:20:00Z',
  timeZone: 'Asia/Seoul',
  standardDayMinutes: 480,
  employee: HR_EMPLOYEE_FIXTURE,
  time: HR_TIME_FIXTURE.card,
  leaveBalances: HR_ABSENCE_FIXTURE.balances,
  pay: HR_PAY_FIXTURE.nextCycle,
  enrollmentWindows: HR_BENEFITS_FIXTURE.windows,
  journeys: HR_TALENT_FIXTURE.journeys,
  activeBenefitCount: HR_BENEFITS_FIXTURE.plans.length,
  openBenefitWindowCount: HR_BENEFITS_FIXTURE.windows.length,
  activeGoalCount: HR_TALENT_FIXTURE.goals.length,
  requiredLearningCount: HR_TALENT_FIXTURE.learning.filter((item) => item.required).length,
  teamPendingCount: 2,
  teamTimePendingCount: 1,
  teamAbsencePendingCount: 1,
  domainStates: {
    TIME: { availability: 'AVAILABLE', dataOrigin: 'REFERENCE', reasonCode: null },
    ABSENCE: { availability: 'AVAILABLE', dataOrigin: 'REFERENCE', reasonCode: null },
    BENEFITS: { availability: 'AVAILABLE', dataOrigin: 'REFERENCE', reasonCode: null },
    PAY: { availability: 'AVAILABLE', dataOrigin: 'REFERENCE', reasonCode: null },
    TALENT: { availability: 'AVAILABLE', dataOrigin: 'REFERENCE', reasonCode: null },
    TEAM: { availability: 'AVAILABLE', dataOrigin: 'UNKNOWN', reasonCode: null },
  },
  referenceDataPresent: true,
} satisfies HrHomeOverview;

const HR_DOMAIN_OPERATION_METRICS = {
  TIME: [
    { key: 'submitted', value: 1, severity: 'ATTENTION' },
    { key: 'openExceptions', value: 0, severity: 'CRITICAL' },
    { key: 'openCards', value: 2, severity: 'INFO' },
  ],
  ABSENCE: [
    { key: 'submitted', value: 1, severity: 'ATTENTION' },
    { key: 'activePlans', value: 2, severity: 'INFO' },
    { key: 'activeEnrollments', value: 18, severity: 'INFO' },
  ],
  BENEFITS: [
    { key: 'activePlans', value: 3, severity: 'INFO' },
    { key: 'openWindows', value: 1, severity: 'ATTENTION' },
    { key: 'activeEnrollments', value: 18, severity: 'INFO' },
  ],
  PAY: [
    { key: 'openCycles', value: 1, severity: 'ATTENTION' },
    { key: 'pendingStatements', value: 2, severity: 'ATTENTION' },
    { key: 'availableStatements', value: 16, severity: 'INFO' },
  ],
  TALENT: [
    { key: 'activeJourneys', value: 4, severity: 'INFO' },
    { key: 'atRiskGoals', value: 1, severity: 'ATTENTION' },
    { key: 'requiredLearning', value: 3, severity: 'ATTENTION' },
  ],
} satisfies Record<HrDomainOperations['domain'], HrDomainOperations['metrics']>;

export const hrDomainOperationsFixture = (domain: HrDomainOperations['domain']) =>
  ({
    domain,
    generatedAt: '2026-08-11T00:20:00Z',
    metrics: HR_DOMAIN_OPERATION_METRICS[domain],
    workQueue:
      domain === 'TIME'
        ? HR_TIME_FIXTURE.teamQueue
        : domain === 'ABSENCE'
          ? HR_ABSENCE_FIXTURE.teamQueue
          : [],
    dataBoundary: 'TENANT',
  }) satisfies HrDomainOperations;

export const CALENDAR_EVENT_FIXTURE = {
  eventId: 'calendar-event-operating-review',
  calendarId: 'calendar-personal',
  calendarName: 'My calendar',
  calendarColor: '#2764C4',
  organizerUserId: 1,
  organizerName: '박현우',
  organizerEmail: 'hyunwoo.park@sk.com',
  title: 'Digital workplace operating review',
  description: 'Weekly decision and dependency review.',
  type: 'MEETING',
  startsAt: '2026-08-11T01:00:00Z',
  endsAt: '2026-08-11T01:45:00Z',
  timeZone: 'Asia/Seoul',
  allDay: false,
  location: 'Seoul HQ · Focus 08',
  conferenceUrl: 'https://meet.example.invalid/operating-review',
  status: 'CONFIRMED',
  visibility: 'DEFAULT',
  recurrence: 'WEEKLY',
  recurrenceInterval: 1,
  recurrenceUntil: null,
  responseRequired: true,
  myResponse: 'ACCEPTED',
  attendees: [
    {
      userId: 2,
      personPublicId: 'person-minseo-kim',
      email: 'minseo.kim@example.invalid',
      name: 'Minseo Kim',
      type: 'REQUIRED',
      response: 'ACCEPTED',
    },
  ],
  resource: null,
  conflict: false,
  importance: 'HIGH',
  detailLevel: 'FULL',
  redacted: false,
  starred: false,
  preferenceVersion: 0,
  capabilities: {
    canViewDetails: true,
    canEdit: false,
    canDelete: true,
    canRestore: false,
    canRespond: true,
    canStar: true,
  },
  restrictionReason: 'RECURRING_EVENT_SERIES',
  version: 2,
} as const satisfies CalendarEvent;

export const CALENDAR_FOCUS_FIXTURE = {
  ...CALENDAR_EVENT_FIXTURE,
  eventId: 'calendar-event-focus',
  title: 'Protected focus time',
  type: 'FOCUS',
  startsAt: '2026-08-11T05:00:00Z',
  endsAt: '2026-08-11T06:30:00Z',
  location: null,
  conferenceUrl: null,
  responseRequired: false,
  myResponse: null,
  attendees: [],
  recurrence: 'NONE',
  capabilities: {
    canViewDetails: true,
    canEdit: true,
    canDelete: true,
    canRestore: false,
    canRespond: false,
    canStar: true,
  },
  restrictionReason: null,
} as const satisfies CalendarEvent;

export const CALENDAR_RESOURCES_FIXTURE = [
  {
    resourceId: 'calendar-resource-focus-08',
    code: 'SEOUL-FOCUS-08',
    name: 'Focus 08',
    nameKo: '포커스 08',
    nameEn: 'Focus 08',
    type: 'ROOM',
    site: 'Seoul HQ',
    floor: '8F',
    capacity: 8,
    features: ['DISPLAY', 'VIDEO', 'WHITEBOARD'],
    timeZone: 'Asia/Seoul',
    approvalRequired: false,
    state: 'AVAILABLE',
    available: true,
    version: 1,
  },
  {
    resourceId: 'calendar-resource-studio-12',
    code: 'SEOUL-STUDIO-12',
    name: 'Collaboration studio 12',
    nameKo: '협업 스튜디오 12',
    nameEn: 'Collaboration studio 12',
    type: 'ROOM',
    site: 'Seoul HQ',
    floor: '12F',
    capacity: 20,
    features: ['DISPLAY', 'VIDEO', 'ACCESSIBLE'],
    timeZone: 'Asia/Seoul',
    approvalRequired: true,
    state: 'AVAILABLE',
    available: false,
    version: 3,
  },
] as const satisfies readonly CalendarResource[];

export const ROOM_BOOKING_EVENT_FIXTURE = {
  ...CALENDAR_EVENT_FIXTURE,
  eventId: 'room-booking-focus-08',
  title: 'Enterprise room booking review',
  description: 'Review the room booking workflow and operating policy.',
  startsAt: '2026-08-19T05:00:00Z',
  endsAt: '2026-08-19T06:00:00Z',
  location: CALENDAR_RESOURCES_FIXTURE[0].name,
  conferenceUrl: null,
  recurrence: 'NONE',
  resource: CALENDAR_RESOURCES_FIXTURE[0],
  version: 1,
} as const satisfies CalendarEvent;

export const CALENDAR_SUMMARIES_FIXTURE = [
  {
    calendarId: 'calendar-personal',
    calendarKey: 'PERSONAL',
    name: 'My calendar',
    color: '#2764C4',
    type: 'PERSONAL',
    visibility: 'PRIVATE',
    ownerPersonPublicId: 'person-tenant-admin',
    ownerDisplayName: 'Tenant Admin',
    sourceKind: 'OWNED',
    accessLevel: 'OWNER',
    subscriptionPolicy: 'REQUIRED',
    required: true,
    selected: true,
    favorite: true,
    displayOrder: 0,
    version: 1,
    subscriptionVersion: 1,
    capabilities: {
      canViewDetails: true,
      canCreateEvents: true,
      canEditCalendar: true,
      canManageSharing: true,
      canDeleteCalendar: false,
      canUnsubscribe: false,
    },
  },
  {
    calendarId: 'calendar-company',
    calendarKey: 'COMPANY',
    name: 'Company calendar',
    color: '#7C3AED',
    type: 'SYSTEM',
    visibility: 'DEFAULT',
    ownerPersonPublicId: null,
    ownerDisplayName: 'SKAX',
    sourceKind: 'COMPANY',
    accessLevel: 'VIEW_DETAILS',
    subscriptionPolicy: 'REQUIRED',
    required: true,
    selected: true,
    favorite: false,
    displayOrder: 1,
    version: 1,
    subscriptionVersion: 1,
    capabilities: {
      canViewDetails: true,
      canCreateEvents: false,
      canEditCalendar: false,
      canManageSharing: false,
      canDeleteCalendar: false,
      canUnsubscribe: false,
    },
  },
  {
    calendarId: 'calendar-team',
    calendarKey: 'TEAM_DIGITAL_WORKPLACE',
    name: 'Digital Workplace',
    color: '#008C95',
    type: 'TEAM',
    visibility: 'DEFAULT',
    ownerPersonPublicId: 'person-tenant-admin',
    ownerDisplayName: 'Tenant Admin',
    sourceKind: 'TEAM',
    accessLevel: 'EDIT',
    subscriptionPolicy: 'OPTIONAL',
    required: false,
    selected: true,
    favorite: false,
    displayOrder: 2,
    version: 1,
    subscriptionVersion: 1,
    capabilities: {
      canViewDetails: true,
      canCreateEvents: true,
      canEditCalendar: false,
      canManageSharing: false,
      canDeleteCalendar: false,
      canUnsubscribe: true,
    },
  },
] as const satisfies readonly CalendarSummary[];

export const CALENDAR_SHARES_FIXTURE = [
  {
    grantId: 'calendar-grant-minseo',
    principalType: 'PERSON',
    principalPersonPublicId: 'person-minseo-kim',
    principalGroupRef: null,
    principalDisplayName: 'Minseo Kim',
    accessLevel: 'VIEW_DETAILS',
    canViewPrivate: false,
    validUntil: null,
    lifecycleState: 'ACTIVE',
    version: 1,
  },
] as const satisfies readonly CalendarShare[];

export const CALENDAR_TRASH_FIXTURE = [
  {
    eventId: 'calendar-event-trashed',
    calendarId: 'calendar-personal',
    calendarName: 'My calendar',
    calendarColor: '#2764C4',
    title: 'Archived planning review',
    startsAt: '2026-08-09T01:00:00Z',
    endsAt: '2026-08-09T01:45:00Z',
    deletedAt: '2026-08-10T03:00:00Z',
    purgeAfter: '2026-09-09T03:00:00Z',
    legalHold: false,
    deletionReason: 'No longer required',
    importance: 'HIGH',
    version: 4,
    capabilities: {
      canViewDetails: true,
      canEdit: false,
      canDelete: false,
      canRestore: true,
      canRespond: false,
      canStar: false,
    },
  },
] as const satisfies readonly CalendarTrashedEvent[];

export const COMPANY_CALENDARS_FIXTURE = [
  {
    calendarId: 'calendar-company',
    key: 'COMPANY',
    name: 'Company calendar',
    nameKo: '회사 캘린더',
    nameEn: 'Company calendar',
    color: '#7C3AED',
    upcomingEventCount: 1,
    trashedEventCount: 1,
    version: 2,
  },
] as const satisfies readonly CompanyCalendar[];

export const COMPANY_CALENDAR_EVENTS_FIXTURE = [
  {
    eventId: 'calendar-company-town-hall',
    calendarId: 'calendar-company',
    title: 'Company town hall',
    description: 'Quarterly company-wide update.',
    type: 'MEETING',
    startsAt: '2026-09-01T01:00:00Z',
    endsAt: '2026-09-01T02:00:00Z',
    timeZone: 'Asia/Seoul',
    allDay: false,
    location: 'Seoul HQ · Auditorium',
    conferenceUrl: null,
    status: 'CONFIRMED',
    visibility: 'DEFAULT',
    recurrence: 'NONE',
    recurrenceInterval: 1,
    recurrenceUntil: null,
    responseRequired: false,
    attendees: [],
    importance: 'HIGH',
    deletedAt: null,
    purgeAfter: null,
    legalHold: false,
    capabilities: {
      canViewDetails: true,
      canEdit: true,
      canDelete: true,
      canRestore: false,
      canRespond: false,
      canStar: false,
    },
    version: 3,
  },
] as const satisfies readonly CompanyCalendarEvent[];

export const CALENDAR_HOME_FIXTURE = {
  date: '2026-08-11',
  timeZone: 'Asia/Seoul',
  nextEvent: CALENDAR_EVENT_FIXTURE,
  today: [CALENDAR_EVENT_FIXTURE, CALENDAR_FOCUS_FIXTURE],
  metrics: {
    eventCount: 4,
    meetingMinutes: 135,
    focusMinutes: 150,
    focusTargetMinutes: 240,
    conflictCount: 0,
    awaitingResponseCount: 1,
    availableRoomCount: 7,
  },
  weekLoad: [
    ['2026-08-10', 180, 90, 5, 0, 62],
    ['2026-08-11', 135, 150, 4, 0, 55],
    ['2026-08-12', 240, 60, 6, 1, 78],
    ['2026-08-13', 120, 180, 4, 0, 50],
    ['2026-08-14', 90, 120, 3, 0, 38],
  ].map(([date, meetingMinutes, focusMinutes, eventCount, conflictCount, loadPercent]) => ({
    date: String(date),
    meetingMinutes: Number(meetingMinutes),
    focusMinutes: Number(focusMinutes),
    eventCount: Number(eventCount),
    conflictCount: Number(conflictCount),
    loadPercent: Number(loadPercent),
  })),
  attention: [
    {
      key: 'calendar-response-needed',
      severity: 'MEDIUM',
      title: 'One invitation needs your response',
      description: 'Resolve it before the organizer finalizes the room.',
      eventId: CALENDAR_EVENT_FIXTURE.eventId,
      actionPath: '/calendar/schedule',
    },
  ],
  generatedAt: '2026-08-11T00:20:00Z',
} satisfies CalendarHome;

export const CALENDAR_ADMIN_FIXTURE = {
  activeResources: 18,
  resourcesInMaintenance: 1,
  bookingsThisWeek: 94,
  pendingBookings: 1,
  eventsThisWeek: 436,
  conflictedUsers: 3,
  policy: {
    weekStart: 1,
    workingDayStart: '09:00',
    workingDayEnd: '18:00',
    defaultEventMinutes: 30,
    minimumEventMinutes: 15,
    maximumEventMinutes: 480,
    maximumAdvanceDays: 180,
    defaultBufferMinutes: 10,
    weeklyFocusTargetMinutes: 240,
    dailyMeetingLimitMinutes: 300,
    enforceMeetingAgenda: true,
    allowExternalAttendees: true,
    version: 4,
  },
  resources: [...CALENDAR_RESOURCES_FIXTURE],
  generatedAt: '2026-08-11T00:20:00Z',
} satisfies CalendarAdminOverview;

export const CALENDAR_BOOKINGS_FIXTURE = [
  {
    bookingId: 'calendar-booking-studio-12',
    eventId: 'calendar-event-town-hall',
    resourceId: 'calendar-resource-studio-12',
    resourceName: 'Collaboration studio 12',
    eventTitle: 'Quarterly people town hall',
    startsAt: '2026-08-13T05:00:00Z',
    endsAt: '2026-08-13T07:00:00Z',
    organizerName: 'Minseo Kim',
    organizerEmail: 'minseo.kim@example.invalid',
    status: 'PENDING',
    requestedBy: 2,
    decisionNote: null,
    decidedAt: null,
    decidedBy: null,
    version: 1,
  },
] satisfies CalendarBooking[];

export const CALENDAR_AVAILABILITY_FIXTURE = {
  participants: [{ personPublicId: 'person-minseo-kim', busyMinutes: 180, availableSlotCount: 4 }],
  suggestions: [
    {
      startsAt: '2026-08-11T07:00:00Z',
      endsAt: '2026-08-11T07:30:00Z',
      score: 96,
      reasonCode: 'ALL_REQUIRED_AVAILABLE_WITHIN_WORKING_HOURS',
      reason: 'All participants are available and focus time is preserved.',
    },
  ],
  generatedAt: '2026-08-11T00:20:00Z',
} satisfies CalendarAvailability;
