type WidenCopy<T> = { [K in keyof T]: T[K] extends string ? string : WidenCopy<T[K]> };

export const DWAION_ROUTINE_COPY_KO = {
  eyebrow: '승인형 개인 AI 확장',
  title: '내 AI 루틴: 지능형 자동화 및 조건형 실행 거버넌스',
  description:
    '허용한 출처와 시간을 정의하고 드라이런, 예약 실행, 실패 복구와 완료 영수증을 한곳에서 관리합니다.',
  create: '새 루틴 생성',
  loading: '루틴을 불러오는 중입니다',
  errorTitle: '루틴을 불러오지 못했습니다',
  permissionTitle: '루틴을 볼 권한이 없습니다',
  permissionDescription: '현재 계정의 DWAI·ON 루틴 사용 권한을 확인해 주세요.',
  emptyTitle: '아직 만든 루틴이 없습니다',
  emptyDescription: '첫 루틴을 만들고 출처·분석·전달 동의를 확인한 뒤 드라이런으로 검증하세요.',
  retry: '다시 시도',
  partial: '일부 루틴의 최신 상태를 확인하지 못했습니다.',
  commandFailed: '요청을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.',
  close: '상세 닫기',
  separator: '·',
  revisionPrefix: '리비전 ',
  status: { DRAFT: '검증 준비', ACTIVE: '활성', PAUSED: '일시 중지', ARCHIVED: '보관됨' },
  cadence: { DAILY: '매일', WEEKDAYS: '평일', WEEKLY: '매주' },
  proposalOnly: '검증 전용',
  proposalOnlyHelp:
    '드라이런은 현재 권한과 출처 연결, 다음 예정 시각만 검증합니다. 업무 변경·예약 실행·제안 생성은 수행하지 않습니다.',
  schedulerUnavailable: '예약 실행 엔진은 아직 연결되지 않았습니다.',
  schedulerUnavailableHelp:
    '실행 공급자가 준비되지 않았습니다. 저장과 드라이런은 가능하지만 활성화와 실제 실행은 차단됩니다.',
  engineLabel: '실행 계약',
  engineUnavailable: '예약 엔진 미연결',
  notificationUnavailable: '알림 전달 미지원',
  filtersLabel: '루틴 상태 필터',
  searchLabel: '루틴 검색',
  searchPlaceholder: '이름, 목적, 출처 검색',
  filters: {
    ALL: '전체',
    SCHEDULED: '스케줄',
    WEBHOOK: '이벤트',
    READY: '검증 준비',
    ATTENTION: '재확인 필요',
    PAUSED: '일시 중지',
  },
  selected: '선택됨',
  statusReview: '상태 검토',
  contractTitle: '6단계 안전 검증 및 동의 체인',
  contractSteps: {
    purpose: '명확한 목적 정의',
    source: '참조 범위 격리',
    trigger: '실행 스케줄 및 정책',
    handoff: '결과물 안전 격리',
    guardrail: '안전 한도 및 오류 대책',
    consent: '사용자 명시 동의',
  },
  contractValues: {
    triggerPreview: '저장된 시간은 다음 시각 미리보기에만 사용됩니다.',
    handoffUnavailable: '제안 생성·전달 API가 연결되지 않아 결과물을 생성하지 않습니다.',
    guardrail: 'DRY_RUN_ONLY · 외부 쓰기 0건',
    consentComplete: '세 동의 범위가 모두 활성화되었습니다.',
    consentIncomplete: '동의 또는 재동의가 필요합니다.',
  },
  dryRunMetrics: {
    sources: '검증 출처',
    records: '업무 본문 분석',
    proposals: '생성 제안',
  },
  metrics: {
    total: '등록한 루틴',
    totalDetail: '내 개인 루틴',
    ready: '검증 준비',
    readyDetail: '동의 완료 초안',
    attention: '재확인 필요',
    attentionDetail: '동의 또는 상태 확인',
    paused: '일시 중지',
    pausedDetail: '드라이런 중지',
  },
  schedule: '실행 일정',
  sources: '허용한 정보 출처',
  sourceLabels: { WORK_ITEM: '업무 항목', MAIL: '메일', CALENDAR: '일정' },
  consent: '동의 체인',
  consentLabels: {
    SOURCE_ACCESS: '출처 조회 동의',
    ANALYSIS: 'AI 분석 동의',
    PROPOSAL_DELIVERY: '제안함 전달 동의',
  },
  consentStates: {
    UNSET: '확인 필요',
    DISABLED: '사용 안 함',
    ENABLED: '동의함',
    RECONSENT_REQUIRED: '재동의 필요',
  },
  dryRun: '미리 점검',
  dryRunning: '점검 중',
  dryRunTitle: '최근 미리 점검',
  dryRunOutcomes: { VALIDATED: '권한과 출처 연결 검증 완료' },
  dryRunEvidence: '검증한 출처 {{count}}개 · 업무 본문 분석 0건 · 제안 생성 0건',
  nextPreview: '다음 예정 시각 미리보기',
  edit: '설정 편집',
  pause: '일시 중지',
  resume: '다시 시작',
  pauseTitle: '루틴을 일시 중지할까요?',
  pauseDescription: '중지하는 동안에는 드라이런을 실행할 수 없습니다.',
  resumeTitle: '드라이런 상태로 되돌릴까요?',
  resumeDescription: '예약 실행 없이 드라이런을 다시 사용할 수 있는 초안 상태로 전환합니다.',
  archive: '보관',
  archiveTitle: '이 루틴을 보관할까요?',
  archiveDescription: '보관한 루틴은 다시 수정하거나 드라이런할 수 없습니다.',
  cancel: '취소',
  confirm: '확인',
  revisionConflict: '다른 곳에서 설정이 변경되었습니다. 최신 내용을 다시 불러와 주세요.',
  conflictTitle: '활성화 파이프라인 중단: 원격 리비전 충돌',
  conflictDescription:
    '서버 최신본과 현재 편집본이 다릅니다. 서버 원본을 다시 불러오거나 저장된 스냅샷에서 새 리비전으로 롤백하세요.',
  discardAndRefresh: '서버 최신본 적용',
  forkVersion: '새 버전으로 분기 저장',
  semanticMerge: '필드별 선택적 병합',
  conflictStrategyUnavailable:
    '분기·병합 거버넌스 API가 구성되기 전까지 새 버전으로의 저장은 차단됩니다.',
  editorTitle: '내 AI 루틴 편집기',
  editorDescription:
    '트리거, 에이전트·출처 경계, 전달 경로, 안전 정책과 복구 예산을 검토한 뒤 버전으로 저장합니다.',
  triggerSection: '1. 루틴 식별 및 실행 시점',
  triggerType: '트리거 오케스트레이션 유형',
  scheduledTrigger: 'Schedule Cron (정주기)',
  webhookTrigger: 'Event Trigger (비동기 웹훅)',
  webhookUnavailable: '웹훅 실행 공급자가 구성되지 않아 이 트리거를 선택할 수 없습니다.',
  webhookEventType: '웹훅 이벤트 유형',
  webhookEventTypeHelp: '예: ERP.LEDGER_CLOSE. 비밀값을 포함하지 않는 대문자 이벤트 키입니다.',
  webhookEndpointReference: '웹훅 엔드포인트 참조',
  webhookEndpointReferenceHelp:
    '실제 비밀 URL이나 토큰 대신 등록된 엔드포인트의 안전한 참조만 입력합니다.',
  webhookDefinitionInvalid: '이벤트 유형 또는 엔드포인트 참조 형식을 확인하세요.',
  bindingSection: '2. 에이전트 및 그라운딩 소스',
  agentKernel: '바인딩 대상 에이전트 커널',
  agentKernelValue: 'DWAI Core Agent Pool · 승인된 개인 루틴 커널',
  allowedSources: '허용 출처',
  blockedBoundaries: '차단 경계',
  blockedBoundaryValue: '개인 DM · 미검증 웹 크롤링 · 미등록 개인 스토리지',
  deliverySection: '3. 산출물 전달 경로 및 실행 안전 정책',
  deliveryPipeline: '결과 전달 파이프라인 (복수 선택)',
  proposalDelivery: 'AI 제안함 라우팅 · /dwaion/proposals',
  notificationDelivery: '알림 센터 · 인앱 배너',
  wormDelivery: 'WORM 볼트 영구 포크',
  zeroWriteGuard: 'Zero-Write Guard',
  zeroWriteGuardHelp: '루틴 실행은 승인 없는 외부 쓰기를 수행하지 않습니다.',
  budgetSection: '4. 비용 및 연산 예산 가드레일',
  changeSection: '5. 변경 검토, 시뮬레이션 및 승인',
  semanticDiff: '시맨틱 버전 변경 요약',
  semanticDiffUnchanged: '저장된 버전과 비교해 변경된 설정이 없습니다.',
  semanticDiffCount: '변경 {{count}}건',
  changeLabels: {
    IDENTITY: '이름·목적',
    TRIGGER: '트리거·실행 시점',
    SOURCES: '허용 출처',
    DELIVERY_AND_CONSENT: '전달·동의·복구',
    BUDGET_AND_RECOVERY: '예산·재시도',
  },
  dryRunEditor: 'Dry-run 재실행',
  dryRunDirtyHelp: '변경 내용을 저장한 뒤 새 리비전으로 Dry-run을 실행할 수 있습니다.',
  makerChecker: '변경 승인 요청 (Maker-Checker)',
  engineSwitch: '엔진 교체',
  approvalActions: '승인 및 엔진 전환',
  capabilityReady: '서버 정책에 의해 구성됨',
  capabilityAvailable: '사용 가능',
  capabilityUnavailable: '미구성',
  executionBudget: '실행 예산 한도',
  executionBudgetHelp: '월 실행 횟수와 실행별 토큰·시간 한도를 초과하면 안전하게 중단합니다.',
  executionBudgetInvalid: '허용 범위 안의 실행 예산을 입력하세요.',
  maximumRuns: '월 최대 실행 횟수',
  maximumTokens: '실행당 최대 토큰',
  maximumMinutes: '실행당 최대 시간(분)',
  recoveryPolicy: '재시도·복구·알림 정책',
  recoveryPolicyInvalid: '허용 범위 안의 재시도 정책을 입력하세요.',
  maximumAttempts: '최대 시도 횟수',
  initialBackoff: '첫 재시도 대기(초)',
  backoffMultiplier: '대기 배수',
  notifyOnPartial: '부분 완료 시 알림',
  notifyOnFailure: '실패 시 알림',
  notifyOnRecovery: '복구 완료 시 알림',
  compensationEnabled: '실패 시 보상 처리 허용',
  compensationStrategy: '보상 전략',
  compensationStrategies: {
    REVOKE_PENDING_HANDOFFS: '미완료 인계 회수',
    PROVIDER_MANAGED: '실행 공급자 관리',
  },
  activate: '루틴 활성화',
  deactivate: '예약 실행 중지',
  runNow: '지금 실행',
  activationUnavailable: '실행 공급자가 준비되지 않아 활성화할 수 없습니다.',
  runHistory: '최근 실제 실행',
  runWorkbenchTitle: '선택 실행 추적 및 복구 워크벤치',
  runWorkbenchDescription:
    '실제 실행 원장에서 5단계 DAG, 예산, 승인 게이트, 전달과 보상 상태를 확인합니다.',
  executionDagTitle: '5단계 실행 DAG',
  runStages: {
    trigger: '트리거 접수 및 원장 생성',
    authorization: '실행 시점 권한 재검증',
    evidence: '허용 출처 근거 수집',
    approval: '제안·승인 게이트 생성',
    delivery: '알림·영수증 전달',
  },
  runAuthorizationPending: '실행 시점 재인증 결과는 종료 영수증이 생성되면 확정됩니다.',
  runEvidence: '근거',
  runTokens: '사용 토큰',
  runLatency: '실행 지연',
  runAttempts: '시도/최대',
  runProposals: '제안',
  runApprovalGates: '승인 게이트',
  runNotification: '알림 상태',
  zeroWriteEvidence: 'Zero-Write 검증',
  externalWrites: '외부 쓰기',
  receiptFingerprint: '결과 무결성 SHA-256',
  zeroWriteReceiptPending:
    '외부 쓰기 0건은 종료 영수증으로만 확정합니다. 현재 실행은 영수증 대기 중입니다.',
  traceLedgerTitle: '트레이스·감사 원장',
  runIdentifier: '실행 ID',
  runVersion: '원장 버전',
  runUpdatedAt: '최종 업데이트',
  runReceiptIdentifier: '영수증 ID',
  runReceiptPending: '종료 영수증 대기 중',
  idempotencyEvidence: '멱등성 증거',
  idempotencyUnavailable:
    '공개 조회 계약은 commandId를 노출하지 않습니다. 불변 run ID와 version으로 재조회합니다.',
  noRecoveryActionRequired: '추가 복구 명령이 필요하지 않습니다.',
  noRuns: '아직 실제 실행 기록이 없습니다.',
  retryRun: '실패 실행 재시도',
  cancelRun: '안전하게 취소',
  compensateRun: '보상 처리 시작',
  runCommandSaved: '실행 명령을 기록했습니다.',
  activated: '루틴 예약 실행을 활성화했습니다.',
  deactivated: '루틴 예약 실행을 중지했습니다.',
  runTriggered: '검증된 트리거로 실행을 시작했습니다.',
  actualReceipt: '완료 영수증',
  authorizationRevision: '실행 시점 권한 결정 리비전',
  authorizedSources: '실행 시점 허용 출처',
  advancedRuntimeTitle: '실행 진단과 복구 도구',
  advancedRuntimeDescription:
    '실제 실행 기록과 런타임 공급자 상태에 따라 사용 가능 여부가 결정됩니다.',
  serverEvidenceTitle: '서버 버전·건전성·감사 증거',
  serverEvidenceDescription:
    '변경 원장, 현재 건전성, 롤백 영수증과 원본 텔레메트리를 서버 기록으로 확인합니다.',
  healthState: { HEALTHY: '정상', DEGRADED: '저하', BLOCKED: '차단' },
  workerState: '실행 워커',
  scheduleState: '트리거 최신 상태',
  consentState: '동의 체인',
  current: '최신',
  stale: '재확인 필요',
  configured: '구성됨',
  notConfigured: '미구성',
  versionHistoryTitle: '버전 변경 이력',
  noVersionHistory: '아직 서버 버전 원장이 없습니다.',
  rollbackVersion: '이 리비전으로 롤백',
  rollbackTitle: '선택한 서버 스냅샷으로 롤백할까요?',
  rollbackDescription:
    '현재 리비전을 덮어쓰지 않고 선택한 스냅샷에서 새 리비전을 생성합니다. 영수증으로 결속됩니다.',
  rollbackComplete: '롤백 리비전과 무결성 영수증이 생성되었습니다.',
  rollbackReceipt: '최근 롤백 영수증',
  telemetryDownloaded: '서버 텔레메트리 원본을 다운로드했습니다.',
  telemetryFailed: '서버 텔레메트리를 다운로드하지 못했습니다.',
  evidenceLoading: '서버 실행 증거를 불러오는 중입니다.',
  evidenceFailed: '서버 버전 또는 건전성 증거를 불러오지 못했습니다.',
  versionAudit: '버전 변경 이력(Audit Log)',
  healthCheck: '전체 건전성 진단',
  snapshotRollback: '스냅샷 롤백 보기',
  oauthReauthorize: 'OAuth 재인증 토큰 갱신',
  temporaryLimit: '임시 한도 증액 요청',
  escalate: '담당자에게 긴급 전달 (Escalate)',
  skipQuarantined: '격리 건 제외 후 계속 (Skip & Continue)',
  jsonlDownload: '로그 원본 다운로드 (JSONL)',
  printReport: '실행 리포트 인쇄',
  runtimeEvidenceReady: '현재 서버 실행 기록과 capability 응답을 사용합니다.',
  runtimeEvidenceUnavailable: '서버 감사·진단·스냅샷·원본 로그 API가 준비되면 사용할 수 있습니다.',
  runtimeActionUnavailable: '런타임 공급자가 이 복구 작업을 제공하지 않습니다.',
  name: '루틴 이름',
  nameHelp: '업무 목적이 드러나는 이름을 입력하세요.',
  details: '목적',
  detailsHelp: '분석하려는 업무 목적을 구체적으로 입력하세요.',
  cadenceLabel: '반복 주기',
  localTime: '실행 시간',
  timeZone: '기준 타임존',
  activeFrom: '시작일',
  activeUntil: '루틴 보증 만료일',
  dateOrderError: '종료일은 시작일보다 빠를 수 없습니다.',
  weekDays: '실행 요일',
  weekDayRequired: '매주 루틴은 요일을 하나 이상 선택해야 합니다.',
  quietHours: '방해 금지 시간대 (Quiet Hours)',
  quietStart: '방해 금지 시작',
  quietEnd: '방해 금지 종료',
  quietHoursHelp: '두 시간을 모두 입력하면 다음 예정 시각 계산에만 반영됩니다.',
  weekdayLabels: ['월', '화', '수', '목', '금', '토', '일'],
  sourceSelection: '분석할 정보 출처',
  unavailableSource: '현재 계정에서 사용할 수 없는 출처입니다.',
  consentHelp: '세 단계는 저장 후 각각 별도 감사 명령으로 기록됩니다.',
  save: '초안 임시 저장',
  saving: '저장 중',
  saved: '루틴 설정을 저장했습니다.',
  lifecycleSaved: '루틴 상태를 변경했습니다.',
  archived: '루틴을 보관했습니다.',
  validationComplete: '권한과 출처 연결을 검증했습니다.',
} as const;

export const DWAION_ROUTINE_COPY_EN: DwaionRoutineCopy = {
  eyebrow: 'Consent-led personal AI extension',
  title: 'My AI routines: governed automation and conditional execution',
  description:
    'Define approved sources and timing, then manage validation, scheduled execution, recovery, and completion receipts.',
  create: 'Create new routine',
  loading: 'Loading routines',
  errorTitle: 'Routines could not be loaded',
  permissionTitle: 'You do not have access to routines',
  permissionDescription: 'Check your current DWAI·ON routine permission.',
  emptyTitle: 'No routines yet',
  emptyDescription: 'Create a routine, confirm each consent, and validate it with a dry run.',
  retry: 'Retry',
  partial: 'Some routine state could not be verified.',
  commandFailed: 'The request could not be completed. Try again shortly.',
  close: 'Close details',
  separator: '·',
  revisionPrefix: 'Revision ',
  status: { DRAFT: 'Ready to validate', ACTIVE: 'Active', PAUSED: 'Paused', ARCHIVED: 'Archived' },
  cadence: { DAILY: 'Daily', WEEKDAYS: 'Weekdays', WEEKLY: 'Weekly' },
  proposalOnly: 'Validation only',
  proposalOnlyHelp:
    'A dry run validates access, source binding, and the next preview time. It does not change work, schedule execution, or create proposals.',
  schedulerUnavailable: 'Scheduled execution is not connected yet.',
  schedulerUnavailableHelp:
    'The execution provider is not ready. Saving and dry runs remain available, while activation and real execution are blocked.',
  engineLabel: 'Execution contract',
  engineUnavailable: 'Scheduler not connected',
  notificationUnavailable: 'Notifications unavailable',
  filtersLabel: 'Routine status filters',
  searchLabel: 'Search routines',
  searchPlaceholder: 'Search name, objective, or source',
  filters: {
    ALL: 'All',
    SCHEDULED: 'Schedule',
    WEBHOOK: 'Event',
    READY: 'Ready',
    ATTENTION: 'Needs review',
    PAUSED: 'Paused',
  },
  selected: 'Selected',
  statusReview: 'Review state',
  contractTitle: 'Six-step safety and consent chain',
  contractSteps: {
    purpose: 'Purpose binding',
    source: 'Access isolation',
    trigger: 'Execution schedule and policy',
    handoff: 'Safe result boundary',
    guardrail: 'Safety guardrails',
    consent: 'Explicit user consent',
  },
  contractValues: {
    triggerPreview: 'Saved timing is used only to preview the next occurrence.',
    handoffUnavailable:
      'Proposal generation and delivery are not connected, so no result is created.',
    guardrail: 'DRY_RUN_ONLY · 0 external writes',
    consentComplete: 'All three consent scopes are enabled.',
    consentIncomplete: 'Consent or re-consent is required.',
  },
  dryRunMetrics: {
    sources: 'Sources checked',
    records: 'Business records read',
    proposals: 'Proposals created',
  },
  metrics: {
    total: 'Saved routines',
    totalDetail: 'Your personal routines',
    ready: 'Ready to validate',
    readyDetail: 'Drafts with full consent',
    attention: 'Needs review',
    attentionDetail: 'Consent or lifecycle check',
    paused: 'Paused',
    pausedDetail: 'Dry runs stopped',
  },
  schedule: 'Schedule preview',
  sources: 'Approved sources',
  sourceLabels: { WORK_ITEM: 'Work items', MAIL: 'Mail', CALENDAR: 'Calendar' },
  consent: 'Consent chain',
  consentLabels: {
    SOURCE_ACCESS: 'Source access consent',
    ANALYSIS: 'AI analysis consent',
    PROPOSAL_DELIVERY: 'Proposal delivery consent',
  },
  consentStates: {
    UNSET: 'Review required',
    DISABLED: 'Disabled',
    ENABLED: 'Consented',
    RECONSENT_REQUIRED: 'Re-consent required',
  },
  dryRun: 'Run validation',
  dryRunning: 'Validating',
  dryRunTitle: 'Latest validation',
  dryRunOutcomes: { VALIDATED: 'Access and source binding validated' },
  dryRunEvidence: 'Validated {{count}} sources · 0 business records analyzed · 0 proposals created',
  nextPreview: 'Next scheduled-time preview',
  edit: 'Edit settings',
  pause: 'Pause',
  resume: 'Resume dry runs',
  pauseTitle: 'Pause this routine?',
  pauseDescription: 'Dry runs are unavailable while the routine is paused.',
  resumeTitle: 'Return to dry-run state?',
  resumeDescription: 'This returns to draft state without enabling scheduled execution.',
  archive: 'Archive',
  archiveTitle: 'Archive this routine?',
  archiveDescription: 'An archived routine cannot be edited or dry-run again.',
  cancel: 'Cancel',
  confirm: 'Confirm',
  revisionConflict: 'This routine changed elsewhere. Refresh before trying again.',
  conflictTitle: 'Activation pipeline stopped: remote revision conflict',
  conflictDescription:
    'The server version changed while this routine was being edited. Reload the canonical server state or create a new revision from a governed snapshot.',
  discardAndRefresh: 'Apply latest server version',
  forkVersion: 'Save as a forked version',
  semanticMerge: 'Inspect field-level semantic merge',
  conflictStrategyUnavailable:
    'Fork and merge remain blocked until the governed version-resolution API is configured.',
  editorTitle: 'My AI routine editor',
  editorDescription:
    'Review the trigger, agent and source boundaries, delivery, safety, and recovery budget before saving a version.',
  triggerSection: '1. Routine identity and trigger',
  triggerType: 'Trigger orchestration type',
  scheduledTrigger: 'Schedule cron',
  webhookTrigger: 'Event trigger (webhook)',
  webhookUnavailable: 'The webhook execution provider is not configured for this trigger.',
  webhookEventType: 'Webhook event type',
  webhookEventTypeHelp: 'For example ERP.LEDGER_CLOSE. Use a secret-free uppercase event key.',
  webhookEndpointReference: 'Webhook endpoint reference',
  webhookEndpointReferenceHelp:
    'Enter only a registered safe reference, never a secret URL or access token.',
  webhookDefinitionInvalid: 'Check the event type and endpoint reference format.',
  bindingSection: '2. Agent and grounding sources',
  agentKernel: 'Bound agent kernel',
  agentKernelValue: 'DWAI Core Agent Pool · governed personal routine kernel',
  allowedSources: 'Allowed sources',
  blockedBoundaries: 'Blocked boundaries',
  blockedBoundaryValue: 'Private DMs · unverified web crawling · unregistered personal storage',
  deliverySection: '3. Delivery and execution safety policy',
  deliveryPipeline: 'Result delivery pipeline (multiple selection)',
  proposalDelivery: 'AI proposal inbox routing · /dwaion/proposals',
  notificationDelivery: 'Notification center · in-app banner',
  wormDelivery: 'Permanent WORM vault fork',
  zeroWriteGuard: 'Zero-write guard',
  zeroWriteGuardHelp: 'Routine execution never performs an unapproved external write.',
  budgetSection: '4. Cost and compute budget guardrails',
  changeSection: '5. Change review, simulation, and approval',
  semanticDiff: 'Semantic version change summary',
  semanticDiffUnchanged: 'No setting differs from the saved version.',
  semanticDiffCount: 'Changes: {{count}}',
  changeLabels: {
    IDENTITY: 'Name and objective',
    TRIGGER: 'Trigger and timing',
    SOURCES: 'Allowed sources',
    DELIVERY_AND_CONSENT: 'Delivery, consent, and recovery',
    BUDGET_AND_RECOVERY: 'Budget and retry',
  },
  dryRunEditor: 'Re-run dry-run',
  dryRunDirtyHelp: 'Save the changes before validating the new revision with a dry-run.',
  makerChecker: 'Request change approval (maker-checker)',
  engineSwitch: 'Switch engine',
  approvalActions: 'Approval and engine switching',
  capabilityReady: 'Configured by server policy',
  capabilityAvailable: 'Available',
  capabilityUnavailable: 'Not configured',
  executionBudget: 'Execution budget',
  executionBudgetHelp: 'Runs stop safely when monthly, token, or elapsed-time limits are reached.',
  executionBudgetInvalid: 'Enter execution budgets within the supported range.',
  maximumRuns: 'Maximum runs per month',
  maximumTokens: 'Maximum tokens per run',
  maximumMinutes: 'Maximum minutes per run',
  recoveryPolicy: 'Retry, recovery, and notification policy',
  recoveryPolicyInvalid: 'Enter a retry policy within the supported range.',
  maximumAttempts: 'Maximum attempts',
  initialBackoff: 'Initial backoff (seconds)',
  backoffMultiplier: 'Backoff multiplier',
  notifyOnPartial: 'Notify on partial completion',
  notifyOnFailure: 'Notify on failure',
  notifyOnRecovery: 'Notify after recovery',
  compensationEnabled: 'Allow compensation after failure',
  compensationStrategy: 'Compensation strategy',
  compensationStrategies: {
    REVOKE_PENDING_HANDOFFS: 'Revoke pending handoffs',
    PROVIDER_MANAGED: 'Provider-managed recovery',
  },
  activate: 'Activate routine',
  deactivate: 'Stop scheduled execution',
  runNow: 'Run now',
  activationUnavailable: 'The execution provider is not ready, so activation is blocked.',
  runHistory: 'Recent real executions',
  runWorkbenchTitle: 'Selected run trace and recovery workbench',
  runWorkbenchDescription:
    'Inspect the five-stage DAG, budgets, approval gates, delivery, and compensation from the real execution ledger.',
  executionDagTitle: 'Five-stage execution DAG',
  runStages: {
    trigger: 'Trigger accepted and ledger created',
    authorization: 'Execution-time authorization revalidated',
    evidence: 'Authorized evidence collected',
    approval: 'Proposal and approval gates created',
    delivery: 'Notification and receipt delivered',
  },
  runAuthorizationPending:
    'The execution-time authorization decision is finalized only in a terminal receipt.',
  runEvidence: 'Evidence',
  runTokens: 'Tokens used',
  runLatency: 'Elapsed time',
  runAttempts: 'Attempt/maximum',
  runProposals: 'Proposals',
  runApprovalGates: 'Approval gates',
  runNotification: 'Notification state',
  zeroWriteEvidence: 'Zero-write evidence',
  externalWrites: 'External writes',
  receiptFingerprint: 'Result integrity SHA-256',
  zeroWriteReceiptPending:
    'Zero external writes are final only after the terminal receipt is issued. This run is awaiting that receipt.',
  traceLedgerTitle: 'Trace and audit ledger',
  runIdentifier: 'Run ID',
  runVersion: 'Ledger version',
  runUpdatedAt: 'Last updated',
  runReceiptIdentifier: 'Receipt ID',
  runReceiptPending: 'Terminal receipt pending',
  idempotencyEvidence: 'Idempotency evidence',
  idempotencyUnavailable:
    'The public read contract does not expose commandId. Re-query the immutable run ID and version.',
  noRecoveryActionRequired: 'No additional recovery command is required.',
  noRuns: 'There are no real execution records yet.',
  retryRun: 'Retry failed run',
  cancelRun: 'Cancel safely',
  compensateRun: 'Start compensation',
  runCommandSaved: 'The execution command was recorded.',
  activated: 'Scheduled routine execution is active.',
  deactivated: 'Scheduled routine execution was stopped.',
  runTriggered: 'The governed trigger started a run.',
  actualReceipt: 'Completion receipt',
  authorizationRevision: 'Execution-time authorization revision',
  authorizedSources: 'Execution-time authorized sources',
  advancedRuntimeTitle: 'Run diagnostics and recovery tools',
  advancedRuntimeDescription:
    'Availability follows the live run record and runtime provider state.',
  serverEvidenceTitle: 'Server version, health, and audit evidence',
  serverEvidenceDescription:
    'Inspect the server change ledger, current health, rollback receipt, and raw telemetry.',
  healthState: { HEALTHY: 'Healthy', DEGRADED: 'Degraded', BLOCKED: 'Blocked' },
  workerState: 'Execution worker',
  scheduleState: 'Trigger currency',
  consentState: 'Consent chain',
  current: 'Current',
  stale: 'Review required',
  configured: 'Configured',
  notConfigured: 'Not configured',
  versionHistoryTitle: 'Version history',
  noVersionHistory: 'No server version ledger is available yet.',
  rollbackVersion: 'Roll back to this revision',
  rollbackTitle: 'Roll back from the selected server snapshot?',
  rollbackDescription:
    'The current revision remains immutable. A new revision is created from the selected snapshot and bound to a receipt.',
  rollbackComplete: 'A rollback revision and integrity receipt were created.',
  rollbackReceipt: 'Latest rollback receipt',
  telemetryDownloaded: 'The raw server telemetry was downloaded.',
  telemetryFailed: 'The server telemetry could not be downloaded.',
  evidenceLoading: 'Loading server execution evidence.',
  evidenceFailed: 'Server version or health evidence could not be loaded.',
  versionAudit: 'Version history (audit log)',
  healthCheck: 'Run full health check',
  snapshotRollback: 'View snapshot rollback',
  oauthReauthorize: 'Refresh OAuth authorization',
  temporaryLimit: 'Request temporary limit increase',
  escalate: 'Escalate to operator',
  skipQuarantined: 'Skip quarantined items and continue',
  jsonlDownload: 'Download raw log (JSONL)',
  printReport: 'Print run report',
  runtimeEvidenceReady: 'Uses the current server run record and capability response.',
  runtimeEvidenceUnavailable:
    'Available after the server audit, diagnostics, snapshot, and raw-log APIs are configured.',
  runtimeActionUnavailable: 'The runtime provider does not offer this recovery operation.',
  name: 'Routine name',
  nameHelp: 'Use a name that explains the work purpose.',
  details: 'Objective',
  detailsHelp: 'Describe the work analysis objective.',
  cadenceLabel: 'Cadence',
  localTime: 'Local time',
  timeZone: 'Reference time zone',
  activeFrom: 'Start date',
  activeUntil: 'Routine assurance expiry',
  dateOrderError: 'The end date cannot precede the start date.',
  weekDays: 'Week days',
  weekDayRequired: 'Select at least one day for a weekly routine.',
  quietHours: 'Quiet hours',
  quietStart: 'Quiet hours start',
  quietEnd: 'Quiet hours end',
  quietHoursHelp: 'Both times affect only the next-time preview.',
  weekdayLabels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  sourceSelection: 'Sources to validate',
  unavailableSource: 'This source is not available to the current account.',
  consentHelp: 'Each consent is recorded as a separate audited command after save.',
  save: 'Save draft',
  saving: 'Saving',
  saved: 'Routine settings saved.',
  lifecycleSaved: 'Routine state updated.',
  archived: 'Routine archived.',
  validationComplete: 'Access and source binding validated.',
};

export type DwaionRoutineCopy = WidenCopy<typeof DWAION_ROUTINE_COPY_KO>;
