type WidenCopy<T> = { [K in keyof T]: T[K] extends string ? string : WidenCopy<T[K]> };

export const DWAION_ROUTINE_COPY_KO = {
  eyebrow: '승인형 개인 AI 확장',
  title: '나의 AI 루틴',
  description:
    '허용한 출처와 시간을 정의하고 안전하게 미리 검증합니다. 현재 버전은 예약 실행이나 제안 전달 없이 드라이런만 지원합니다.',
  create: '루틴 만들기',
  loading: '루틴을 불러오는 중입니다',
  errorTitle: '루틴을 불러오지 못했습니다',
  permissionTitle: '루틴을 볼 권한이 없습니다',
  permissionDescription: '현재 계정의 DWAI·ON 루틴 사용 권한을 확인해 주세요.',
  emptyTitle: '아직 만든 루틴이 없습니다',
  emptyDescription: '첫 루틴을 만들고 출처·분석·전달 동의를 확인한 뒤 드라이런으로 검증하세요.',
  retry: '다시 시도',
  partial: '일부 루틴의 최신 상태를 확인하지 못했습니다.',
  commandFailed: '요청을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.',
  close: '상세 닫기',
  separator: '·',
  revisionPrefix: '리비전 ',
  status: { DRAFT: '드라이런 가능', PAUSED: '일시 중지', ARCHIVED: '보관됨' },
  cadence: { DAILY: '매일', WEEKDAYS: '평일', WEEKLY: '매주' },
  proposalOnly: '검증 전용',
  proposalOnlyHelp:
    '드라이런은 현재 권한과 출처 연결, 다음 예정 시각만 검증합니다. 업무 변경·예약 실행·제안 생성은 수행하지 않습니다.',
  schedulerUnavailable: '예약 실행 엔진은 아직 연결되지 않았습니다.',
  schedulerUnavailableHelp:
    '저장한 시간은 다음 실행 시각을 미리 확인하는 용도입니다. 백그라운드 실행이나 알림 전달은 수행하지 않습니다.',
  metrics: {
    total: '등록한 루틴',
    totalDetail: '내 개인 루틴',
    ready: '검증 준비',
    readyDetail: '동의 완료 초안',
    attention: '재확인 필요',
    attentionDetail: '동의 또는 상태 확인',
    paused: '일시 중지',
    pausedDetail: '드라이런 중지',
  },
  schedule: '실행 일정',
  sources: '허용한 정보 출처',
  sourceLabels: { WORK_ITEM: '업무 항목', MAIL: '메일', CALENDAR: '일정' },
  consent: '동의 체인',
  consentLabels: {
    SOURCE_ACCESS: '출처 조회 동의',
    ANALYSIS: 'AI 분석 동의',
    PROPOSAL_DELIVERY: '제안함 전달 동의',
  },
  consentStates: {
    UNSET: '확인 필요',
    DISABLED: '사용 안 함',
    ENABLED: '동의함',
    RECONSENT_REQUIRED: '재동의 필요',
  },
  dryRun: '미리 점검',
  dryRunning: '점검 중',
  dryRunTitle: '최근 미리 점검',
  dryRunOutcomes: { VALIDATED: '권한과 출처 연결 검증 완료' },
  dryRunEvidence: '검증한 출처 {{count}}개 · 업무 본문 분석 0건 · 제안 생성 0건',
  nextPreview: '다음 예정 시각 미리보기',
  edit: '설정 편집',
  pause: '일시 중지',
  resume: '다시 시작',
  pauseTitle: '루틴을 일시 중지할까요?',
  pauseDescription: '중지하는 동안에는 드라이런을 실행할 수 없습니다.',
  resumeTitle: '드라이런 상태로 되돌릴까요?',
  resumeDescription: '예약 실행 없이 드라이런을 다시 사용할 수 있는 초안 상태로 전환합니다.',
  archive: '보관',
  archiveTitle: '이 루틴을 보관할까요?',
  archiveDescription: '보관한 루틴은 다시 수정하거나 드라이런할 수 없습니다.',
  cancel: '취소',
  confirm: '확인',
  revisionConflict: '다른 곳에서 설정이 변경되었습니다. 최신 내용을 다시 불러와 주세요.',
  editorTitle: '루틴 설정',
  editorDescription: '출처, 시간, 동의 범위를 확인한 뒤 제안 전용 루틴을 저장합니다.',
  name: '루틴 이름',
  nameHelp: '업무 목적이 드러나는 이름을 입력하세요.',
  details: '목적',
  detailsHelp: '분석하려는 업무 목적을 구체적으로 입력하세요.',
  cadenceLabel: '반복 주기',
  localTime: '실행 시간',
  timeZone: '시간대',
  activeFrom: '시작일',
  activeUntil: '종료일',
  dateOrderError: '종료일은 시작일보다 빠를 수 없습니다.',
  weekDays: '실행 요일',
  weekDayRequired: '매주 루틴은 요일을 하나 이상 선택해야 합니다.',
  quietHours: '방해 금지 시간 미리보기',
  quietStart: '방해 금지 시작',
  quietEnd: '방해 금지 종료',
  quietHoursHelp: '두 시간을 모두 입력하면 다음 예정 시각 계산에만 반영됩니다.',
  weekdayLabels: ['월', '화', '수', '목', '금', '토', '일'],
  sourceSelection: '분석할 정보 출처',
  unavailableSource: '현재 계정에서 사용할 수 없는 출처입니다.',
  consentHelp: '세 단계는 저장 후 각각 별도 감사 명령으로 기록됩니다.',
  save: '루틴 저장',
  saving: '저장 중',
  saved: '루틴 설정을 저장했습니다.',
  lifecycleSaved: '루틴 상태를 변경했습니다.',
  archived: '루틴을 보관했습니다.',
  validationComplete: '권한과 출처 연결을 검증했습니다.',
} as const;

export const DWAION_ROUTINE_COPY_EN: DwaionRoutineCopy = {
  eyebrow: 'Consent-led personal AI extension',
  title: 'My AI routines',
  description:
    'Define approved sources and timing, then validate them safely. This release supports dry runs only, without scheduled execution or proposal delivery.',
  create: 'Create routine',
  loading: 'Loading routines',
  errorTitle: 'Routines could not be loaded',
  permissionTitle: 'You do not have access to routines',
  permissionDescription: 'Check your current DWAI·ON routine permission.',
  emptyTitle: 'No routines yet',
  emptyDescription: 'Create a routine, confirm each consent, and validate it with a dry run.',
  retry: 'Retry',
  partial: 'Some routine state could not be verified.',
  commandFailed: 'The request could not be completed. Try again shortly.',
  close: 'Close details',
  separator: '·',
  revisionPrefix: 'Revision ',
  status: { DRAFT: 'Dry-run ready', PAUSED: 'Paused', ARCHIVED: 'Archived' },
  cadence: { DAILY: 'Daily', WEEKDAYS: 'Weekdays', WEEKLY: 'Weekly' },
  proposalOnly: 'Validation only',
  proposalOnlyHelp:
    'A dry run validates access, source binding, and the next preview time. It does not change work, schedule execution, or create proposals.',
  schedulerUnavailable: 'Scheduled execution is not connected yet.',
  schedulerUnavailableHelp:
    'Saved timing is used only to preview the next occurrence. No background execution or notification delivery occurs.',
  metrics: {
    total: 'Saved routines',
    totalDetail: 'Your personal routines',
    ready: 'Ready to validate',
    readyDetail: 'Drafts with full consent',
    attention: 'Needs review',
    attentionDetail: 'Consent or lifecycle check',
    paused: 'Paused',
    pausedDetail: 'Dry runs stopped',
  },
  schedule: 'Schedule preview',
  sources: 'Approved sources',
  sourceLabels: { WORK_ITEM: 'Work items', MAIL: 'Mail', CALENDAR: 'Calendar' },
  consent: 'Consent chain',
  consentLabels: {
    SOURCE_ACCESS: 'Source access consent',
    ANALYSIS: 'AI analysis consent',
    PROPOSAL_DELIVERY: 'Proposal delivery consent',
  },
  consentStates: {
    UNSET: 'Review required',
    DISABLED: 'Disabled',
    ENABLED: 'Consented',
    RECONSENT_REQUIRED: 'Re-consent required',
  },
  dryRun: 'Run validation',
  dryRunning: 'Validating',
  dryRunTitle: 'Latest validation',
  dryRunOutcomes: { VALIDATED: 'Access and source binding validated' },
  dryRunEvidence: 'Validated {{count}} sources · 0 business records analyzed · 0 proposals created',
  nextPreview: 'Next scheduled-time preview',
  edit: 'Edit settings',
  pause: 'Pause',
  resume: 'Resume dry runs',
  pauseTitle: 'Pause this routine?',
  pauseDescription: 'Dry runs are unavailable while the routine is paused.',
  resumeTitle: 'Return to dry-run state?',
  resumeDescription: 'This returns to draft state without enabling scheduled execution.',
  archive: 'Archive',
  archiveTitle: 'Archive this routine?',
  archiveDescription: 'An archived routine cannot be edited or dry-run again.',
  cancel: 'Cancel',
  confirm: 'Confirm',
  revisionConflict: 'This routine changed elsewhere. Refresh before trying again.',
  editorTitle: 'Routine settings',
  editorDescription: 'Review source, time, and consent boundaries before saving.',
  name: 'Routine name',
  nameHelp: 'Use a name that explains the work purpose.',
  details: 'Objective',
  detailsHelp: 'Describe the work analysis objective.',
  cadenceLabel: 'Cadence',
  localTime: 'Local time',
  timeZone: 'Time zone',
  activeFrom: 'Start date',
  activeUntil: 'End date',
  dateOrderError: 'The end date cannot precede the start date.',
  weekDays: 'Week days',
  weekDayRequired: 'Select at least one day for a weekly routine.',
  quietHours: 'Quiet-hours preview',
  quietStart: 'Quiet hours start',
  quietEnd: 'Quiet hours end',
  quietHoursHelp: 'Both times affect only the next-time preview.',
  weekdayLabels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  sourceSelection: 'Sources to validate',
  unavailableSource: 'This source is not available to the current account.',
  consentHelp: 'Each consent is recorded as a separate audited command after save.',
  save: 'Save routine',
  saving: 'Saving',
  saved: 'Routine settings saved.',
  lifecycleSaved: 'Routine state updated.',
  archived: 'Routine archived.',
  validationComplete: 'Access and source binding validated.',
};

export type DwaionRoutineCopy = WidenCopy<typeof DWAION_ROUTINE_COPY_KO>;
