-- HRIS-PER physical DDL blueprint for PostgreSQL.
-- Target runtime: dwp-people-server/hris/performance.
-- This is a reviewed module blueprint, not an allocated Flyway migration number.
-- No source DDL was copied. All cross-context references are opaque public UUIDs.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE SCHEMA IF NOT EXISTS hris_performance;
SET search_path TO hris_performance, public;

CREATE TABLE prf_cycles (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    cycle_key VARCHAR(100) NOT NULL,
    display_name VARCHAR(240) NOT NULL,
    lifecycle_state VARCHAR(24) NOT NULL,
    active_version_no INTEGER,
    aggregate_version BIGINT NOT NULL DEFAULT 0,
    retention_policy_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID NOT NULL,
    CONSTRAINT uk_prf_cycles_tenant_id UNIQUE (tenant_id, cycle_id),
    CONSTRAINT uk_prf_cycles_key UNIQUE (tenant_id, cycle_key),
    CONSTRAINT ck_prf_cycles_state CHECK (lifecycle_state IN ('DRAFT','VALIDATED','PUBLISHED','ACTIVE','CLOSED','RETIRED')),
    CONSTRAINT ck_prf_cycles_version CHECK (aggregate_version >= 0 AND (active_version_no IS NULL OR active_version_no > 0))
);

CREATE TABLE prf_cycle_versions (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_version_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    cycle_id UUID NOT NULL,
    version_no INTEGER NOT NULL,
    version_state VARCHAR(20) NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ,
    timezone_id VARCHAR(80) NOT NULL,
    policy_version_id UUID NOT NULL,
    population_rule_version_id UUID,
    publication_approval_ref UUID,
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    content_hash CHAR(64) NOT NULL,
    published_at TIMESTAMPTZ,
    published_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    CONSTRAINT uk_prf_cycle_versions_tenant_id UNIQUE (tenant_id, cycle_version_id),
    CONSTRAINT uk_prf_cycle_versions_no UNIQUE (tenant_id, cycle_id, version_no),
    CONSTRAINT fk_prf_cycle_versions_cycle FOREIGN KEY (tenant_id, cycle_id)
        REFERENCES prf_cycles(tenant_id, cycle_id),
    CONSTRAINT ck_prf_cycle_versions_state CHECK (version_state IN ('DRAFT','VALIDATED','PUBLISHED','SUPERSEDED','RETIRED')),
    CONSTRAINT ck_prf_cycle_versions_period CHECK (effective_to IS NULL OR effective_from < effective_to),
    CONSTRAINT ck_prf_cycle_versions_hash CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    EXCLUDE USING gist (
        tenant_id WITH =,
        cycle_id WITH =,
        tstzrange(effective_from, COALESCE(effective_to, 'infinity'::timestamptz), '[)') WITH &&
    ) WHERE (version_state = 'PUBLISHED')
);

CREATE TABLE prf_cycle_stages (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    cycle_version_id UUID NOT NULL,
    stage_key VARCHAR(80) NOT NULL,
    stage_type VARCHAR(32) NOT NULL,
    sequence_no INTEGER NOT NULL,
    opens_at TIMESTAMPTZ NOT NULL,
    closes_at TIMESTAMPTZ NOT NULL,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    stage_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uk_prf_cycle_stages_tenant_id UNIQUE (tenant_id, stage_id),
    CONSTRAINT uk_prf_cycle_stages_key UNIQUE (tenant_id, cycle_version_id, stage_key),
    CONSTRAINT uk_prf_cycle_stages_seq UNIQUE (tenant_id, cycle_version_id, sequence_no),
    CONSTRAINT fk_prf_cycle_stages_version FOREIGN KEY (tenant_id, cycle_version_id)
        REFERENCES prf_cycle_versions(tenant_id, cycle_version_id),
    CONSTRAINT ck_prf_cycle_stages_sequence CHECK (sequence_no > 0),
    CONSTRAINT ck_prf_cycle_stages_period CHECK (opens_at < closes_at)
);

CREATE TABLE prf_templates (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    template_key VARCHAR(100) NOT NULL,
    template_type VARCHAR(32) NOT NULL,
    display_name VARCHAR(240) NOT NULL,
    lifecycle_state VARCHAR(20) NOT NULL,
    aggregate_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID NOT NULL,
    CONSTRAINT uk_prf_templates_tenant_id UNIQUE (tenant_id, template_id),
    CONSTRAINT uk_prf_templates_key UNIQUE (tenant_id, template_key),
    CONSTRAINT ck_prf_templates_type CHECK (template_type IN ('GOAL','REVIEW','FEEDBACK','CHECKIN','APPEAL')),
    CONSTRAINT ck_prf_templates_state CHECK (lifecycle_state IN ('DRAFT','PUBLISHED','RETIRED')),
    CONSTRAINT ck_prf_templates_version CHECK (aggregate_version >= 0)
);

CREATE TABLE prf_template_versions (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_version_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    template_id UUID NOT NULL,
    version_no INTEGER NOT NULL,
    version_state VARCHAR(20) NOT NULL,
    schema_version VARCHAR(30) NOT NULL,
    response_schema JSONB NOT NULL,
    visibility_policy JSONB NOT NULL,
    scoring_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    content_hash CHAR(64) NOT NULL,
    published_at TIMESTAMPTZ,
    published_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    CONSTRAINT uk_prf_template_versions_tenant_id UNIQUE (tenant_id, template_version_id),
    CONSTRAINT uk_prf_template_versions_no UNIQUE (tenant_id, template_id, version_no),
    CONSTRAINT fk_prf_template_versions_template FOREIGN KEY (tenant_id, template_id)
        REFERENCES prf_templates(tenant_id, template_id),
    CONSTRAINT ck_prf_template_versions_state CHECK (version_state IN ('DRAFT','VALIDATED','PUBLISHED','SUPERSEDED','RETIRED')),
    CONSTRAINT ck_prf_template_versions_hash CHECK (content_hash ~ '^[0-9a-f]{64}$')
);

CREATE TABLE prf_template_items (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_item_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    template_version_id UUID NOT NULL,
    item_key VARCHAR(100) NOT NULL,
    parent_item_id UUID,
    item_type VARCHAR(30) NOT NULL,
    sequence_no INTEGER NOT NULL,
    weight NUMERIC(9,6),
    item_schema JSONB NOT NULL,
    CONSTRAINT uk_prf_template_items_tenant_id UNIQUE (tenant_id, template_item_id),
    CONSTRAINT uk_prf_template_items_key UNIQUE (tenant_id, template_version_id, item_key),
    CONSTRAINT fk_prf_template_items_version FOREIGN KEY (tenant_id, template_version_id)
        REFERENCES prf_template_versions(tenant_id, template_version_id),
    CONSTRAINT fk_prf_template_items_parent FOREIGN KEY (tenant_id, parent_item_id)
        REFERENCES prf_template_items(tenant_id, template_item_id),
    CONSTRAINT ck_prf_template_items_sequence CHECK (sequence_no > 0),
    CONSTRAINT ck_prf_template_items_weight CHECK (weight IS NULL OR weight BETWEEN 0 AND 1)
);

CREATE TABLE prf_rubric_levels (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rubric_level_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    template_version_id UUID NOT NULL,
    scale_key VARCHAR(80) NOT NULL,
    level_key VARCHAR(80) NOT NULL,
    sequence_no INTEGER NOT NULL,
    numeric_value NUMERIC(18,6) NOT NULL,
    label_i18n JSONB NOT NULL,
    CONSTRAINT uk_prf_rubric_levels_tenant_id UNIQUE (tenant_id, rubric_level_id),
    CONSTRAINT uk_prf_rubric_levels_key UNIQUE (tenant_id, template_version_id, scale_key, level_key),
    CONSTRAINT fk_prf_rubric_levels_template FOREIGN KEY (tenant_id, template_version_id)
        REFERENCES prf_template_versions(tenant_id, template_version_id),
    CONSTRAINT ck_prf_rubric_levels_sequence CHECK (sequence_no > 0)
);

CREATE TABLE prf_population_rules (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    population_rule_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    scope_type VARCHAR(24) NOT NULL,
    scope_public_id UUID,
    scope_key TEXT GENERATED ALWAYS AS (
        scope_type || ':' || COALESCE(scope_public_id::text, 'GLOBAL')
    ) STORED,
    rule_key VARCHAR(100) NOT NULL,
    version_no INTEGER NOT NULL,
    rule_state VARCHAR(20) NOT NULL,
    rule_schema_version VARCHAR(30) NOT NULL,
    rule_definition JSONB NOT NULL,
    content_hash CHAR(64) NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    CONSTRAINT uk_prf_population_rules_tenant_id UNIQUE (tenant_id, population_rule_id),
    CONSTRAINT uk_prf_population_rules_version UNIQUE (tenant_id, scope_key, rule_key, version_no),
    CONSTRAINT ck_prf_population_rules_state CHECK (rule_state IN ('DRAFT','VALIDATED','PUBLISHED','SUPERSEDED')),
    CONSTRAINT ck_prf_population_rules_scope CHECK (
        (scope_type = 'TENANT' AND scope_public_id IS NULL)
        OR (scope_type IN ('LEGAL_ENTITY','ORG_TREE') AND scope_public_id IS NOT NULL)
    ),
    CONSTRAINT ck_prf_population_rules_period CHECK (effective_to IS NULL OR effective_from < effective_to),
    CONSTRAINT ck_prf_population_rules_hash CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_prf_population_rules_publication_lineage CHECK (
        (rule_state IN ('PUBLISHED','SUPERSEDED') AND published_at IS NOT NULL)
        OR (rule_state IN ('DRAFT','VALIDATED') AND published_at IS NULL)
    ),
    CONSTRAINT ex_prf_population_rules_ever_published_period EXCLUDE USING gist (
        tenant_id WITH =,
        scope_key WITH =,
        rule_key WITH =,
        tstzrange(effective_from, COALESCE(effective_to, 'infinity'::timestamptz), '[)') WITH &&
    ) WHERE (published_at IS NOT NULL)
);

CREATE OR REPLACE FUNCTION prf_guard_population_rule_publication_lineage() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.published_at IS NOT NULL THEN
        IF NEW.published_at IS DISTINCT FROM OLD.published_at
           OR NEW.scope_type IS DISTINCT FROM OLD.scope_type
           OR NEW.scope_public_id IS DISTINCT FROM OLD.scope_public_id
           OR NEW.rule_key IS DISTINCT FROM OLD.rule_key
           OR NEW.version_no IS DISTINCT FROM OLD.version_no
           OR NEW.rule_schema_version IS DISTINCT FROM OLD.rule_schema_version
           OR NEW.rule_definition IS DISTINCT FROM OLD.rule_definition
           OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
           OR NEW.effective_from IS DISTINCT FROM OLD.effective_from THEN
            RAISE EXCEPTION 'PER_POPULATION_RULE_PUBLISHED_LINEAGE_IMMUTABLE' USING ERRCODE = '55000';
        END IF;
        IF NEW.effective_to IS DISTINCT FROM OLD.effective_to
           AND NOT (
               OLD.effective_to IS NULL
               AND NEW.effective_to IS NOT NULL
               AND NEW.effective_to > OLD.effective_from
           ) THEN
            RAISE EXCEPTION 'PER_POPULATION_RULE_PERIOD_REWRITE_FORBIDDEN' USING ERRCODE = '55000';
        END IF;
    ELSIF NEW.rule_state IN ('PUBLISHED','SUPERSEDED') THEN
        NEW.published_at := COALESCE(NEW.published_at, CURRENT_TIMESTAMP);
    ELSIF NEW.published_at IS NOT NULL THEN
        RAISE EXCEPTION 'PER_POPULATION_RULE_MARKER_WITHOUT_PUBLISHED_STATE' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_prf_population_rule_publication_lineage
    BEFORE INSERT OR UPDATE ON prf_population_rules
    FOR EACH ROW EXECUTE FUNCTION prf_guard_population_rule_publication_lineage();

CREATE TABLE prf_population_freezes (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    population_freeze_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    cycle_version_id UUID NOT NULL,
    population_rule_id UUID NOT NULL,
    workforce_snapshot_id UUID NOT NULL,
    workforce_snapshot_revision BIGINT NOT NULL,
    freeze_state VARCHAR(20) NOT NULL,
    participant_count INTEGER NOT NULL DEFAULT 0,
    reviewer_assignment_count INTEGER NOT NULL DEFAULT 0,
    content_hash CHAR(64),
    aggregate_version BIGINT NOT NULL DEFAULT 0,
    frozen_at TIMESTAMPTZ,
    frozen_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    CONSTRAINT uk_prf_population_freezes_tenant_id UNIQUE (tenant_id, population_freeze_id),
    CONSTRAINT uk_prf_population_freezes_cycle UNIQUE (tenant_id, cycle_version_id),
    CONSTRAINT fk_prf_population_freezes_cycle FOREIGN KEY (tenant_id, cycle_version_id)
        REFERENCES prf_cycle_versions(tenant_id, cycle_version_id),
    CONSTRAINT fk_prf_population_freezes_rule FOREIGN KEY (tenant_id, population_rule_id)
        REFERENCES prf_population_rules(tenant_id, population_rule_id),
    CONSTRAINT ck_prf_population_freezes_state CHECK (freeze_state IN ('DRAFT','PREVIEWED','FROZEN','SUPERSEDED')),
    CONSTRAINT ck_prf_population_freezes_counts CHECK (participant_count >= 0 AND reviewer_assignment_count >= 0),
    CONSTRAINT ck_prf_population_freezes_revision CHECK (workforce_snapshot_revision >= 0 AND aggregate_version >= 0)
);

CREATE TABLE prf_participants (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    population_freeze_id UUID NOT NULL,
    worker_public_id UUID NOT NULL,
    assignment_public_id UUID NOT NULL,
    organization_public_id UUID,
    manager_worker_public_id UUID,
    participant_state VARCHAR(20) NOT NULL,
    exception_reason_code VARCHAR(80),
    snapshot_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_prf_participants_tenant_id UNIQUE (tenant_id, participant_id),
    CONSTRAINT uk_prf_participants_worker UNIQUE (tenant_id, population_freeze_id, worker_public_id),
    CONSTRAINT fk_prf_participants_freeze FOREIGN KEY (tenant_id, population_freeze_id)
        REFERENCES prf_population_freezes(tenant_id, population_freeze_id),
    CONSTRAINT ck_prf_participants_state CHECK (participant_state IN ('INCLUDED','EXCLUDED','EXEMPTED','WITHDRAWN')),
    CONSTRAINT ck_prf_participants_exception CHECK (
        (participant_state = 'INCLUDED' AND exception_reason_code IS NULL)
        OR (participant_state <> 'INCLUDED' AND exception_reason_code IS NOT NULL)
    )
);

CREATE TABLE prf_reviewer_assignments (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewer_assignment_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    participant_id UUID NOT NULL,
    reviewer_worker_public_id UUID NOT NULL,
    reviewer_assignment_public_id UUID,
    reviewer_type VARCHAR(30) NOT NULL,
    stage_key VARCHAR(80) NOT NULL,
    anonymity_mode VARCHAR(24) NOT NULL DEFAULT 'IDENTIFIED',
    assignment_state VARCHAR(20) NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_prf_reviewer_assignments_tenant_id UNIQUE (tenant_id, reviewer_assignment_id),
    CONSTRAINT uk_prf_reviewer_assignments_slot UNIQUE (tenant_id, participant_id, reviewer_worker_public_id, reviewer_type, stage_key),
    CONSTRAINT fk_prf_reviewer_assignments_participant FOREIGN KEY (tenant_id, participant_id)
        REFERENCES prf_participants(tenant_id, participant_id),
    CONSTRAINT ck_prf_reviewer_assignments_type CHECK (reviewer_type IN ('SELF','MANAGER','SECOND_MANAGER','THIRD_MANAGER','PEER','DIRECT_REPORT','EXTERNAL','REFEREE')),
    CONSTRAINT ck_prf_reviewer_assignments_anonymity CHECK (anonymity_mode IN ('IDENTIFIED','MASKED','ANONYMOUS_AGGREGATE')),
    CONSTRAINT ck_prf_reviewer_assignments_state CHECK (assignment_state IN ('ASSIGNED','ACCEPTED','DECLINED','REASSIGNED','COMPLETED','CANCELLED'))
);

CREATE TABLE prf_goals (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    cycle_version_id UUID NOT NULL,
    owner_type VARCHAR(20) NOT NULL,
    owner_public_id UUID NOT NULL,
    goal_state VARCHAR(20) NOT NULL,
    current_revision_no INTEGER NOT NULL,
    aggregate_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID NOT NULL,
    CONSTRAINT uk_prf_goals_tenant_id UNIQUE (tenant_id, goal_id),
    CONSTRAINT fk_prf_goals_cycle FOREIGN KEY (tenant_id, cycle_version_id)
        REFERENCES prf_cycle_versions(tenant_id, cycle_version_id),
    CONSTRAINT ck_prf_goals_owner CHECK (owner_type IN ('WORKER','ORGANIZATION','TEAM')),
    CONSTRAINT ck_prf_goals_state CHECK (goal_state IN ('DRAFT','SUBMITTED','APPROVED','ACTIVE','COMPLETED','CANCELLED')),
    CONSTRAINT ck_prf_goals_revision CHECK (current_revision_no > 0 AND aggregate_version >= 0)
);

CREATE TABLE prf_goal_revisions (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_revision_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    goal_id UUID NOT NULL,
    revision_no INTEGER NOT NULL,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    measurement_schema JSONB NOT NULL,
    weight NUMERIC(9,6) NOT NULL,
    progress NUMERIC(9,6) NOT NULL DEFAULT 0,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    change_reason VARCHAR(500),
    content_hash CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    CONSTRAINT uk_prf_goal_revisions_tenant_id UNIQUE (tenant_id, goal_revision_id),
    CONSTRAINT uk_prf_goal_revisions_no UNIQUE (tenant_id, goal_id, revision_no),
    CONSTRAINT fk_prf_goal_revisions_goal FOREIGN KEY (tenant_id, goal_id)
        REFERENCES prf_goals(tenant_id, goal_id),
    CONSTRAINT ck_prf_goal_revisions_values CHECK (weight BETWEEN 0 AND 1 AND progress BETWEEN 0 AND 1 AND period_start <= period_end),
    CONSTRAINT ck_prf_goal_revisions_hash CHECK (content_hash ~ '^[0-9a-f]{64}$')
);

CREATE TABLE prf_goal_alignments (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_alignment_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    child_goal_id UUID NOT NULL,
    parent_goal_id UUID NOT NULL,
    alignment_type VARCHAR(20) NOT NULL,
    contribution_weight NUMERIC(9,6),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    CONSTRAINT uk_prf_goal_alignments_tenant_id UNIQUE (tenant_id, goal_alignment_id),
    CONSTRAINT uk_prf_goal_alignments_edge UNIQUE (tenant_id, child_goal_id, parent_goal_id),
    CONSTRAINT fk_prf_goal_alignments_child FOREIGN KEY (tenant_id, child_goal_id)
        REFERENCES prf_goals(tenant_id, goal_id),
    CONSTRAINT fk_prf_goal_alignments_parent FOREIGN KEY (tenant_id, parent_goal_id)
        REFERENCES prf_goals(tenant_id, goal_id),
    CONSTRAINT ck_prf_goal_alignments_self CHECK (child_goal_id <> parent_goal_id),
    CONSTRAINT ck_prf_goal_alignments_weight CHECK (contribution_weight IS NULL OR contribution_weight BETWEEN 0 AND 1)
);

CREATE TABLE prf_reviews (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    cycle_version_id UUID NOT NULL,
    participant_id UUID NOT NULL,
    reviewer_assignment_id UUID NOT NULL,
    template_version_id UUID NOT NULL,
    review_state VARCHAR(20) NOT NULL,
    due_at TIMESTAMPTZ,
    aggregate_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_prf_reviews_tenant_id UNIQUE (tenant_id, review_id),
    CONSTRAINT uk_prf_reviews_assignment UNIQUE (tenant_id, reviewer_assignment_id),
    CONSTRAINT fk_prf_reviews_cycle FOREIGN KEY (tenant_id, cycle_version_id)
        REFERENCES prf_cycle_versions(tenant_id, cycle_version_id),
    CONSTRAINT fk_prf_reviews_participant FOREIGN KEY (tenant_id, participant_id)
        REFERENCES prf_participants(tenant_id, participant_id),
    CONSTRAINT fk_prf_reviews_reviewer FOREIGN KEY (tenant_id, reviewer_assignment_id)
        REFERENCES prf_reviewer_assignments(tenant_id, reviewer_assignment_id),
    CONSTRAINT fk_prf_reviews_template FOREIGN KEY (tenant_id, template_version_id)
        REFERENCES prf_template_versions(tenant_id, template_version_id),
    CONSTRAINT ck_prf_reviews_state CHECK (review_state IN ('NOT_STARTED','IN_PROGRESS','SUBMITTED','RETURNED','COMPLETED','CANCELLED')),
    CONSTRAINT ck_prf_reviews_version CHECK (aggregate_version >= 0)
);

CREATE TABLE prf_review_submissions (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_submission_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    review_id UUID NOT NULL,
    submission_no INTEGER NOT NULL,
    submission_state VARCHAR(20) NOT NULL,
    template_content_hash CHAR(64) NOT NULL,
    overall_score NUMERIC(18,6),
    calculation_trace JSONB NOT NULL DEFAULT '{}'::jsonb,
    submitted_at TIMESTAMPTZ,
    submitted_by UUID,
    return_reason VARCHAR(1000),
    content_hash CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_prf_review_submissions_tenant_id UNIQUE (tenant_id, review_submission_id),
    CONSTRAINT uk_prf_review_submissions_no UNIQUE (tenant_id, review_id, submission_no),
    CONSTRAINT fk_prf_review_submissions_review FOREIGN KEY (tenant_id, review_id)
        REFERENCES prf_reviews(tenant_id, review_id),
    CONSTRAINT ck_prf_review_submissions_state CHECK (submission_state IN ('DRAFT_SNAPSHOT','SUBMITTED','RETURNED','SUPERSEDED')),
    CONSTRAINT ck_prf_review_submissions_hash CHECK (template_content_hash ~ '^[0-9a-f]{64}$' AND content_hash ~ '^[0-9a-f]{64}$')
);

CREATE TABLE prf_review_answers (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_answer_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    review_submission_id UUID NOT NULL,
    item_key VARCHAR(100) NOT NULL,
    answer_value JSONB NOT NULL,
    numeric_score NUMERIC(18,6),
    field_visibility VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_prf_review_answers_tenant_id UNIQUE (tenant_id, review_answer_id),
    CONSTRAINT uk_prf_review_answers_item UNIQUE (tenant_id, review_submission_id, item_key),
    CONSTRAINT fk_prf_review_answers_submission FOREIGN KEY (tenant_id, review_submission_id)
        REFERENCES prf_review_submissions(tenant_id, review_submission_id),
    CONSTRAINT ck_prf_review_answers_visibility CHECK (field_visibility IN ('SUBJECT_AFTER_PUBLISH','REVIEWER_ONLY','OPERATOR_PRIVATE','CALIBRATOR_PRIVATE','AUDIT_ONLY'))
);

CREATE TABLE prf_feedback_requests (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_request_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    cycle_version_id UUID NOT NULL,
    subject_worker_public_id UUID NOT NULL,
    template_version_id UUID NOT NULL,
    anonymity_mode VARCHAR(24) NOT NULL,
    minimum_release_count INTEGER NOT NULL,
    request_state VARCHAR(20) NOT NULL,
    aggregate_version BIGINT NOT NULL DEFAULT 0,
    opens_at TIMESTAMPTZ NOT NULL,
    closes_at TIMESTAMPTZ NOT NULL,
    released_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    CONSTRAINT uk_prf_feedback_requests_tenant_id UNIQUE (tenant_id, feedback_request_id),
    CONSTRAINT fk_prf_feedback_requests_cycle FOREIGN KEY (tenant_id, cycle_version_id)
        REFERENCES prf_cycle_versions(tenant_id, cycle_version_id),
    CONSTRAINT fk_prf_feedback_requests_template FOREIGN KEY (tenant_id, template_version_id)
        REFERENCES prf_template_versions(tenant_id, template_version_id),
    CONSTRAINT ck_prf_feedback_requests_anonymity CHECK (anonymity_mode IN ('IDENTIFIED','MASKED','ANONYMOUS_AGGREGATE')),
    CONSTRAINT ck_prf_feedback_requests_threshold CHECK (minimum_release_count >= 1),
    CONSTRAINT ck_prf_feedback_requests_state CHECK (request_state IN ('DRAFT','OPEN','CLOSED','AGGREGATED','RELEASED','CANCELLED')),
    CONSTRAINT ck_prf_feedback_requests_period CHECK (opens_at < closes_at)
);

CREATE TABLE prf_feedback_assignments (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_assignment_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    feedback_request_id UUID NOT NULL,
    provider_worker_public_id UUID NOT NULL,
    relationship_type VARCHAR(30) NOT NULL,
    assignment_state VARCHAR(20) NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_prf_feedback_assignments_tenant_id UNIQUE (tenant_id, feedback_assignment_id),
    CONSTRAINT uk_prf_feedback_assignments_provider UNIQUE (tenant_id, feedback_request_id, provider_worker_public_id),
    CONSTRAINT fk_prf_feedback_assignments_request FOREIGN KEY (tenant_id, feedback_request_id)
        REFERENCES prf_feedback_requests(tenant_id, feedback_request_id),
    CONSTRAINT ck_prf_feedback_assignments_state CHECK (assignment_state IN ('ASSIGNED','SUBMITTED','DECLINED','CANCELLED'))
);

CREATE TABLE prf_feedback_responses (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_response_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    feedback_assignment_id UUID NOT NULL,
    response_payload JSONB NOT NULL,
    content_hash CHAR(64) NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_prf_feedback_responses_tenant_id UNIQUE (tenant_id, feedback_response_id),
    CONSTRAINT uk_prf_feedback_responses_assignment UNIQUE (tenant_id, feedback_assignment_id),
    CONSTRAINT fk_prf_feedback_responses_assignment FOREIGN KEY (tenant_id, feedback_assignment_id)
        REFERENCES prf_feedback_assignments(tenant_id, feedback_assignment_id),
    CONSTRAINT ck_prf_feedback_responses_hash CHECK (content_hash ~ '^[0-9a-f]{64}$')
);

CREATE TABLE prf_checkins (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkin_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    cycle_version_id UUID,
    subject_worker_public_id UUID NOT NULL,
    manager_worker_public_id UUID NOT NULL,
    checkin_state VARCHAR(20) NOT NULL,
    scheduled_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    agenda JSONB NOT NULL DEFAULT '{}'::jsonb,
    shared_note_object_id UUID,
    private_note_object_id UUID,
    acknowledgement_at TIMESTAMPTZ,
    aggregate_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    CONSTRAINT uk_prf_checkins_tenant_id UNIQUE (tenant_id, checkin_id),
    CONSTRAINT fk_prf_checkins_cycle FOREIGN KEY (tenant_id, cycle_version_id)
        REFERENCES prf_cycle_versions(tenant_id, cycle_version_id),
    CONSTRAINT ck_prf_checkins_state CHECK (checkin_state IN ('DRAFT','SCHEDULED','COMPLETED','ACKNOWLEDGED','CANCELLED'))
);

CREATE TABLE prf_calibration_sessions (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calibration_session_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    cycle_version_id UUID NOT NULL,
    population_freeze_id UUID NOT NULL,
    calibration_state VARCHAR(20) NOT NULL,
    owner_user_id UUID NOT NULL,
    approval_ref UUID,
    aggregate_version BIGINT NOT NULL DEFAULT 0,
    baseline_hash CHAR(64) NOT NULL,
    submitted_at TIMESTAMPTZ,
    approved_at TIMESTAMPTZ,
    locked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_prf_calibration_sessions_tenant_id UNIQUE (tenant_id, calibration_session_id),
    CONSTRAINT uk_prf_calibration_sessions_cycle UNIQUE (tenant_id, cycle_version_id, population_freeze_id),
    CONSTRAINT fk_prf_calibration_sessions_cycle FOREIGN KEY (tenant_id, cycle_version_id)
        REFERENCES prf_cycle_versions(tenant_id, cycle_version_id),
    CONSTRAINT fk_prf_calibration_sessions_population FOREIGN KEY (tenant_id, population_freeze_id)
        REFERENCES prf_population_freezes(tenant_id, population_freeze_id),
    CONSTRAINT ck_prf_calibration_sessions_state CHECK (calibration_state IN ('DRAFT','READY','IN_SESSION','SUBMITTED','APPROVED','LOCKED','CANCELLED')),
    CONSTRAINT ck_prf_calibration_sessions_hash CHECK (baseline_hash ~ '^[0-9a-f]{64}$')
);

CREATE TABLE prf_calibration_adjustments (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calibration_adjustment_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    calibration_session_id UUID NOT NULL,
    participant_id UUID NOT NULL,
    sequence_no INTEGER NOT NULL,
    previous_value NUMERIC(18,6) NOT NULL,
    adjusted_value NUMERIC(18,6) NOT NULL,
    previous_grade VARCHAR(80),
    adjusted_grade VARCHAR(80),
    reason_code VARCHAR(80) NOT NULL,
    reason_text VARCHAR(1000) NOT NULL,
    distribution_impact JSONB NOT NULL,
    adjusted_by UUID NOT NULL,
    adjusted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_prf_calibration_adjustments_tenant_id UNIQUE (tenant_id, calibration_adjustment_id),
    CONSTRAINT uk_prf_calibration_adjustments_seq UNIQUE (tenant_id, calibration_session_id, participant_id, sequence_no),
    CONSTRAINT fk_prf_calibration_adjustments_session FOREIGN KEY (tenant_id, calibration_session_id)
        REFERENCES prf_calibration_sessions(tenant_id, calibration_session_id),
    CONSTRAINT fk_prf_calibration_adjustments_participant FOREIGN KEY (tenant_id, participant_id)
        REFERENCES prf_participants(tenant_id, participant_id),
    CONSTRAINT ck_prf_calibration_adjustments_sequence CHECK (sequence_no > 0),
    CONSTRAINT ck_prf_calibration_adjustments_change CHECK (previous_value <> adjusted_value OR previous_grade IS DISTINCT FROM adjusted_grade)
);

CREATE TABLE prf_result_sets (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_set_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    cycle_version_id UUID NOT NULL,
    result_version_no INTEGER NOT NULL,
    result_state VARCHAR(20) NOT NULL,
    rule_version VARCHAR(80) NOT NULL,
    source_snapshot_hash CHAR(64) NOT NULL,
    calculation_hash CHAR(64) NOT NULL,
    approval_ref UUID,
    aggregate_version BIGINT NOT NULL DEFAULT 0,
    calculated_at TIMESTAMPTZ NOT NULL,
    validated_at TIMESTAMPTZ,
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    CONSTRAINT uk_prf_result_sets_tenant_id UNIQUE (tenant_id, result_set_id),
    CONSTRAINT uk_prf_result_sets_version UNIQUE (tenant_id, cycle_version_id, result_version_no),
    CONSTRAINT fk_prf_result_sets_cycle FOREIGN KEY (tenant_id, cycle_version_id)
        REFERENCES prf_cycle_versions(tenant_id, cycle_version_id),
    CONSTRAINT ck_prf_result_sets_state CHECK (result_state IN ('COMPUTED','VALIDATED','APPROVED','PUBLISHED','CORRECTED','SUPERSEDED')),
    CONSTRAINT ck_prf_result_sets_hash CHECK (source_snapshot_hash ~ '^[0-9a-f]{64}$' AND calculation_hash ~ '^[0-9a-f]{64}$')
);

CREATE TABLE prf_results (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    result_set_id UUID NOT NULL,
    participant_id UUID NOT NULL,
    final_score NUMERIC(18,6),
    final_grade VARCHAR(80),
    component_values JSONB NOT NULL,
    visibility_state VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    correction_of_result_id UUID,
    correction_reason VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_prf_results_tenant_id UNIQUE (tenant_id, result_id),
    CONSTRAINT uk_prf_results_participant UNIQUE (tenant_id, result_set_id, participant_id),
    CONSTRAINT fk_prf_results_set FOREIGN KEY (tenant_id, result_set_id)
        REFERENCES prf_result_sets(tenant_id, result_set_id),
    CONSTRAINT fk_prf_results_participant FOREIGN KEY (tenant_id, participant_id)
        REFERENCES prf_participants(tenant_id, participant_id),
    CONSTRAINT fk_prf_results_correction FOREIGN KEY (tenant_id, correction_of_result_id)
        REFERENCES prf_results(tenant_id, result_id),
    CONSTRAINT ck_prf_results_visibility CHECK (visibility_state IN ('PRIVATE','APPROVED','PUBLISHED','WITHHELD')),
    CONSTRAINT ck_prf_results_correction CHECK (
        (correction_of_result_id IS NULL AND correction_reason IS NULL)
        OR (correction_of_result_id IS NOT NULL AND correction_reason IS NOT NULL)
    )
);

CREATE TABLE prf_result_publications (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    result_set_id UUID NOT NULL,
    publication_state VARCHAR(20) NOT NULL,
    population_hash CHAR(64) NOT NULL,
    approval_ref UUID NOT NULL,
    step_up_evidence_ref UUID NOT NULL,
    requested_by UUID NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ,
    failure_code VARCHAR(100),
    CONSTRAINT uk_prf_result_publications_tenant_id UNIQUE (tenant_id, publication_id),
    CONSTRAINT uk_prf_result_publications_set UNIQUE (tenant_id, result_set_id),
    CONSTRAINT fk_prf_result_publications_set FOREIGN KEY (tenant_id, result_set_id)
        REFERENCES prf_result_sets(tenant_id, result_set_id),
    CONSTRAINT ck_prf_result_publications_state CHECK (publication_state IN ('REQUESTED','APPROVED','PUBLISHING','PUBLISHED','FAILED','CANCELLED')),
    CONSTRAINT ck_prf_result_publications_hash CHECK (population_hash ~ '^[0-9a-f]{64}$')
);

CREATE TABLE prf_appeals (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appeal_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    result_id UUID NOT NULL,
    appellant_worker_public_id UUID NOT NULL,
    appeal_state VARCHAR(20) NOT NULL,
    category_code VARCHAR(80) NOT NULL,
    statement TEXT NOT NULL,
    assigned_reviewer_user_id UUID,
    resolution_code VARCHAR(80),
    aggregate_version BIGINT NOT NULL DEFAULT 0,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    CONSTRAINT uk_prf_appeals_tenant_id UNIQUE (tenant_id, appeal_id),
    CONSTRAINT fk_prf_appeals_result FOREIGN KEY (tenant_id, result_id)
        REFERENCES prf_results(tenant_id, result_id),
    CONSTRAINT ck_prf_appeals_state CHECK (appeal_state IN ('OPEN','UNDER_REVIEW','UPHELD','REJECTED','CLOSED','WITHDRAWN'))
);

CREATE TABLE prf_appeal_events (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appeal_event_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    appeal_id UUID NOT NULL,
    sequence_no BIGINT NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    from_state VARCHAR(20),
    to_state VARCHAR(20) NOT NULL,
    reason TEXT,
    actor_user_id UUID NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_prf_appeal_events_tenant_id UNIQUE (tenant_id, appeal_event_id),
    CONSTRAINT uk_prf_appeal_events_seq UNIQUE (tenant_id, appeal_id, sequence_no),
    CONSTRAINT fk_prf_appeal_events_appeal FOREIGN KEY (tenant_id, appeal_id)
        REFERENCES prf_appeals(tenant_id, appeal_id),
    CONSTRAINT ck_prf_appeal_events_sequence CHECK (sequence_no > 0)
);

CREATE TABLE prf_evidence_refs (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_ref_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id UUID NOT NULL,
    evidence_type VARCHAR(50) NOT NULL,
    object_id UUID NOT NULL,
    content_hash CHAR(64) NOT NULL,
    classification VARCHAR(30) NOT NULL,
    purpose_code VARCHAR(80) NOT NULL,
    retention_policy_id UUID NOT NULL,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    CONSTRAINT uk_prf_evidence_refs_tenant_id UNIQUE (tenant_id, evidence_ref_id),
    CONSTRAINT uk_prf_evidence_refs_object UNIQUE (tenant_id, aggregate_type, aggregate_id, object_id),
    CONSTRAINT ck_prf_evidence_refs_hash CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_prf_evidence_refs_class CHECK (classification IN ('INTERNAL','CONFIDENTIAL','RESTRICTED','HIGHLY_RESTRICTED'))
);

CREATE TABLE prf_command_receipts (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_receipt_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    command_type VARCHAR(120) NOT NULL,
    aggregate_type VARCHAR(60) NOT NULL,
    aggregate_id UUID,
    actor_user_id UUID NOT NULL,
    request_hash CHAR(64) NOT NULL,
    originating_action VARCHAR(160) NOT NULL,
    subject_principal_public_id UUID NOT NULL,
    population_scope_digest CHAR(64) NOT NULL,
    field_policy_revision BIGINT NOT NULL,
    purpose_code VARCHAR(80) NOT NULL,
    authorization_revision BIGINT NOT NULL,
    originating_context_sealed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    originating_context_digest CHAR(64) NOT NULL,
    receipt_state VARCHAR(24) NOT NULL,
    result_ref UUID,
    response_code INTEGER,
    error_code VARCHAR(100),
    retry_of_receipt_id UUID,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT uk_prf_command_receipts_tenant_id UNIQUE (tenant_id, command_receipt_id),
    CONSTRAINT uk_prf_command_receipts_key UNIQUE
        (tenant_id, subject_principal_public_id, originating_action, idempotency_key),
    CONSTRAINT fk_prf_command_receipts_retry FOREIGN KEY (tenant_id, retry_of_receipt_id)
        REFERENCES prf_command_receipts(tenant_id, command_receipt_id),
    CONSTRAINT ck_prf_command_receipts_hash CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_prf_command_receipts_auth_revisions CHECK
        (field_policy_revision > 0 AND authorization_revision > 0),
    CONSTRAINT ck_prf_command_receipts_population_digest CHECK
        (population_scope_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_prf_command_receipts_context_digest CHECK
        (originating_context_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_prf_command_receipts_state CHECK (receipt_state IN ('ACCEPTED','RUNNING','SUCCEEDED','FAILED','RESULT_UNKNOWN','QUARANTINED'))
);

CREATE OR REPLACE FUNCTION prf_guard_command_receipt_originating_auth()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'PER command receipt cannot be deleted';
    END IF;
    IF ROW(NEW.tenant_id, NEW.command_type, NEW.idempotency_key,
           NEW.request_hash, NEW.actor_user_id,
           NEW.originating_action, NEW.subject_principal_public_id,
           NEW.population_scope_digest, NEW.field_policy_revision,
           NEW.purpose_code, NEW.authorization_revision,
           NEW.originating_context_sealed_at, NEW.originating_context_digest)
       IS DISTINCT FROM
       ROW(OLD.tenant_id, OLD.command_type, OLD.idempotency_key,
           OLD.request_hash, OLD.actor_user_id,
           OLD.originating_action, OLD.subject_principal_public_id,
           OLD.population_scope_digest, OLD.field_policy_revision,
           OLD.purpose_code, OLD.authorization_revision,
           OLD.originating_context_sealed_at, OLD.originating_context_digest) THEN
        RAISE EXCEPTION 'PER command receipt originating authorization and caller-bound idempotency context is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_prf_command_receipt_originating_auth
    BEFORE UPDATE OR DELETE ON prf_command_receipts
    FOR EACH ROW EXECUTE FUNCTION prf_guard_command_receipt_originating_auth();

CREATE TABLE prf_inbox_receipts (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbox_receipt_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    event_id UUID NOT NULL,
    event_type VARCHAR(160) NOT NULL,
    schema_version VARCHAR(30) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    processing_state VARCHAR(20) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    first_received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ,
    last_error_code VARCHAR(100),
    CONSTRAINT uk_prf_inbox_receipts_tenant_id UNIQUE (tenant_id, inbox_receipt_id),
    CONSTRAINT uk_prf_inbox_receipts_event UNIQUE (tenant_id, event_id),
    CONSTRAINT ck_prf_inbox_receipts_hash CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_prf_inbox_receipts_state CHECK (processing_state IN ('RECEIVED','PROCESSING','PROCESSED','FAILED','QUARANTINED')),
    CONSTRAINT ck_prf_inbox_receipts_attempts CHECK (attempts >= 0)
);

CREATE TABLE prf_outbox_events (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_event_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    event_id UUID NOT NULL,
    event_type VARCHAR(160) NOT NULL,
    schema_version VARCHAR(30) NOT NULL,
    aggregate_type VARCHAR(60) NOT NULL,
    aggregate_id UUID NOT NULL,
    aggregate_version BIGINT NOT NULL,
    payload JSONB NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    correlation_id UUID NOT NULL,
    causation_id UUID,
    occurred_at TIMESTAMPTZ NOT NULL,
    publish_state VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ,
    CONSTRAINT uk_prf_outbox_events_tenant_id UNIQUE (tenant_id, outbox_event_id),
    CONSTRAINT uk_prf_outbox_events_event UNIQUE (tenant_id, event_id),
    CONSTRAINT uk_prf_outbox_events_version UNIQUE (tenant_id, aggregate_type, aggregate_id, aggregate_version, event_type),
    CONSTRAINT ck_prf_outbox_events_hash CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_prf_outbox_events_state CHECK (publish_state IN ('PENDING','PUBLISHING','PUBLISHED','FAILED','QUARANTINED')),
    CONSTRAINT ck_prf_outbox_events_attempts CHECK (attempts >= 0 AND aggregate_version >= 0)
);

CREATE TABLE prf_import_runs (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_run_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    import_type VARCHAR(60) NOT NULL,
    schema_version VARCHAR(30) NOT NULL,
    source_object_id UUID NOT NULL,
    source_content_hash CHAR(64) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    mapping_version VARCHAR(80),
    run_state VARCHAR(24) NOT NULL,
    total_count INTEGER NOT NULL DEFAULT 0,
    accepted_count INTEGER NOT NULL DEFAULT 0,
    rejected_count INTEGER NOT NULL DEFAULT 0,
    applied_count INTEGER NOT NULL DEFAULT 0,
    reconciliation_hash CHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID NOT NULL,
    completed_at TIMESTAMPTZ,
    CONSTRAINT uk_prf_import_runs_tenant_id UNIQUE (tenant_id, import_run_id),
    CONSTRAINT uk_prf_import_runs_key UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT ck_prf_import_runs_hash CHECK (source_content_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_prf_import_runs_state CHECK (run_state IN ('RECEIVED','VALIDATING','VALIDATED','APPLYING','APPLIED','PARTIAL','REJECTED','FAILED','QUARANTINED')),
    CONSTRAINT ck_prf_import_runs_counts CHECK (
        total_count >= 0 AND accepted_count >= 0 AND rejected_count >= 0 AND applied_count >= 0
        AND accepted_count + rejected_count <= total_count
        AND applied_count <= accepted_count
    )
);

CREATE TABLE prf_import_row_issues (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_row_issue_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    import_run_id UUID NOT NULL,
    row_no INTEGER NOT NULL,
    field_key VARCHAR(120),
    issue_code VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    detail_token VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_prf_import_row_issues_tenant_id UNIQUE (tenant_id, import_row_issue_id),
    CONSTRAINT uk_prf_import_row_issues_row UNIQUE (tenant_id, import_run_id, row_no, issue_code, field_key),
    CONSTRAINT fk_prf_import_row_issues_run FOREIGN KEY (tenant_id, import_run_id)
        REFERENCES prf_import_runs(tenant_id, import_run_id),
    CONSTRAINT ck_prf_import_row_issues_row CHECK (row_no > 0),
    CONSTRAINT ck_prf_import_row_issues_severity CHECK (severity IN ('INFO','WARNING','ERROR','FATAL'))
);

CREATE INDEX ix_prf_cycles_state ON prf_cycles(tenant_id, lifecycle_state, updated_at DESC);
CREATE INDEX ix_prf_cycle_versions_effective ON prf_cycle_versions(tenant_id, effective_from, effective_to);
CREATE INDEX ix_prf_stages_window ON prf_cycle_stages(tenant_id, opens_at, closes_at);
CREATE INDEX ix_prf_participants_worker ON prf_participants(tenant_id, worker_public_id, population_freeze_id);
CREATE INDEX ix_prf_reviewer_work ON prf_reviewer_assignments(tenant_id, reviewer_worker_public_id, assignment_state, stage_key);
CREATE INDEX ix_prf_goals_owner ON prf_goals(tenant_id, owner_public_id, goal_state, updated_at DESC);
CREATE INDEX ix_prf_reviews_state ON prf_reviews(tenant_id, review_state, due_at);
CREATE INDEX ix_prf_feedback_subject ON prf_feedback_requests(tenant_id, subject_worker_public_id, request_state);
CREATE INDEX ix_prf_checkins_subject ON prf_checkins(tenant_id, subject_worker_public_id, scheduled_at DESC);
CREATE INDEX ix_prf_calibration_state ON prf_calibration_sessions(tenant_id, calibration_state, created_at DESC);
CREATE INDEX ix_prf_result_sets_state ON prf_result_sets(tenant_id, result_state, calculated_at DESC);
CREATE INDEX ix_prf_results_participant ON prf_results(tenant_id, participant_id, created_at DESC);
CREATE INDEX ix_prf_appeals_state ON prf_appeals(tenant_id, appeal_state, opened_at DESC);
CREATE INDEX ix_prf_command_receipts_state ON prf_command_receipts(tenant_id, receipt_state, created_at DESC);
CREATE INDEX ix_prf_inbox_work ON prf_inbox_receipts(tenant_id, processing_state, first_received_at);
CREATE INDEX ix_prf_outbox_work ON prf_outbox_events(tenant_id, publish_state, next_attempt_at);
CREATE INDEX ix_prf_import_runs_state ON prf_import_runs(tenant_id, run_state, created_at DESC);

-- Row-level security is defense in depth. The application PEP remains authoritative.
-- API/worker roles are NOINHERIT, NOSUPERUSER and NOBYPASSRLS. The audited migration/
-- maintenance role owns tables. DWP transaction scope sets dwp.tenant_id after SET LOCAL
-- ROLE and the pool must reset both before reuse.
DO $$
DECLARE
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'prf_cycles','prf_cycle_versions','prf_cycle_stages','prf_templates','prf_template_versions',
        'prf_template_items','prf_rubric_levels','prf_population_rules','prf_population_freezes',
        'prf_participants','prf_reviewer_assignments','prf_goals','prf_goal_revisions',
        'prf_goal_alignments','prf_reviews','prf_review_submissions','prf_review_answers',
        'prf_feedback_requests','prf_feedback_assignments','prf_feedback_responses','prf_checkins',
        'prf_calibration_sessions','prf_calibration_adjustments','prf_result_sets','prf_results',
        'prf_result_publications','prf_appeals','prf_appeal_events','prf_evidence_refs',
        'prf_command_receipts','prf_inbox_receipts','prf_outbox_events','prf_import_runs','prf_import_row_issues'
    ] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
        EXECUTE format(
            'CREATE POLICY %I ON %I USING (tenant_id = NULLIF(current_setting(''dwp.tenant_id'', true), '''')::BIGINT) WITH CHECK (tenant_id = NULLIF(current_setting(''dwp.tenant_id'', true), '''')::BIGINT)',
            table_name || '_tenant_policy', table_name
        );
    END LOOP;
END $$;

-- Immutability is enforced in application commands and by restricting UPDATE/DELETE grants.
-- The migration must grant INSERT/SELECT only on submission, adjustment, event and receipt tables
-- to the application role; controlled correction commands insert successor rows.
-- Partition prf_review_answers and prf_outbox_events by tenant hash or occurred month only after
-- measured volume crosses the reviewed threshold; partitioning is not guessed before load tests.
