export function deepResearchCopy(language: 'ko' | 'en') {
  if (language === 'ko') {
    return {
      eyebrow: 'DEEP RESEARCH · READ-ONLY',
      title: 'Deep Research 심층 조사',
      description:
        '목표, 허용 소스, 검증 기준과 실행 한도를 확정한 뒤 근거 중심 조사를 시작합니다.',
      back: '대화로 돌아가기',
      objective: '1. 연구 목표와 성공 조건',
      goal: '조사 목표',
      goalHint: '의사결정에 필요한 결과와 범위를 구체적으로 적어주세요.',
      question: '핵심 연구 질문',
      questionHint: '검증할 질문을 한 문장으로 적어주세요.',
      criteria: '성공 기준',
      criteriaHint: '한 줄에 하나씩 입력하세요.',
      sources: '2. 허용 및 제외 소스 범위',
      deliverables: '3. 최종 산출물',
      requireAll: '허용한 모든 소스가 확인되어야 완료로 판정',
      limits: '실행 및 자원 한도',
      minutes: '최대 실행 시간(분)',
      sourceLimit: '최대 소스 수',
      tokenLimit: '최대 토큰',
      guardTitle: 'Zero-Write 실행 보장',
      guardBody:
        '조사 엔진은 읽기 권한만 사용합니다. 저장·공유·업무 인계는 완료 후 별도 검토 명령으로 실행됩니다.',
      save: '검증된 계획 저장',
      saving: '계획 저장 중…',
      start: '심층 조사 시작',
      starting: '조사 시작 중…',
      reset: '계획 초기화',
      planReady: '실행 가능한 계획입니다.',
      planDraft: '계획이 임시 저장되었습니다. 서버 검증을 통과해야 실행할 수 있습니다.',
      unsaved: '저장 후 변경된 내용이 있습니다. 다시 검증해 저장해야 실행할 수 있습니다.',
      errors: {
        GOAL: '조사 목표를 10자 이상 입력하세요.',
        QUESTION: '핵심 연구 질문을 10자 이상 입력하세요.',
        CRITERIA: '성공 기준을 한 개 이상 입력하세요.',
        DELIVERABLE: '최종 산출물을 한 개 이상 선택하세요.',
        SOURCE: '허용할 소스를 한 개 이상 선택하세요.',
        BUDGET: '실행 한도를 허용 범위 안의 정수로 입력하세요.',
      },
      operationFailed:
        '서버가 요청을 완료하지 못했습니다. 같은 요청 ID로 안전하게 다시 시도할 수 있습니다.',
      runTitle: '실시간 심층 조사 실행',
      runId: '실행 ID',
      steps: '완료 단계',
      discovered: '발견 소스',
      verified: '검증 인용',
      failedSources: '확인하지 못한 소스',
      recovery: '복구 안내',
      pause: '일시 중지',
      resume: '조사 재개',
      exclude: '문제 소스를 제외하고 계속',
      reprobe: '소스 권한 재확인',
      extend: '실행 한도 15분 연장',
      cancel: '안전 취소',
      retry: '다시 불러오기',
      loading: '조사 실행 상태를 확인하고 있습니다.',
      report: '검증 완료 보고서',
      viewFullscreen: '보고서 전체 화면',
      closeFullscreen: '전체 화면 닫기',
      evidence: '출처 증거',
      noEvidence: '검증된 인용이 없습니다.',
      outputs: '후속 업무 연결',
      outputHint: '각 명령은 실제 서버 작업 상태와 receipt를 그대로 표시합니다.',
      deliveryRequiresCompletion: '검증 완료 영수증이 발급된 뒤 사용할 수 있습니다.',
      deliveryCapabilityLoading: '서버 기능 상태를 확인하고 있습니다.',
      receipt: '완료 영수증',
      copyReceipt: '영수증 ID 복사',
      copiedReceipt: '복사됨',
      openDeliveryTarget: '대상 업무 열기',
      receiptFingerprint: '영수증 핑거프린트',
      receiptIssuedAt: '발급 시각',
      receiptLedgerDetail: '원장 세부 링크',
      receiptDetailUnavailable: '미제공 — 현재 서버 계약에서 반환되지 않음',
      noReceipt: '아직 완료 영수증이 발급되지 않았습니다.',
      deliveryQueued: '후속 작업이 접수되었습니다.',
      evidenceActions: '검증 결과와 복구 작업',
      evidenceActionsHelp: '현재 실행 응답과 receipt로 가능한 작업만 활성화됩니다.',
      rawDownload: '원시 데이터셋 추출 (JSON)',
      pdfDownload: '공식 리포트 내보내기 (PDF)',
      receiptDownload: '영수증 다운로드',
      auditLedger: '실행 원장 감사기록',
      saveFork: '새 버전으로 분기 저장',
      mergeLatest: '서버 최신본과 병합',
      keepLocal: '로컬 초안 유지',
      sensitivity: '시나리오 민감도 재계산',
      cacheFallback: '캐시 fallback 사용',
      actualRunEvidence: '현재 서버 실행 응답에서 검증된 증거를 사용합니다.',
      serverDownloadReady: '권한과 감사 기록이 적용되는 서버 다운로드를 사용합니다.',
      providerActionUnavailable:
        '현재 실행 계약이 이 작업을 제공하지 않습니다. 복구 안내에 따라 범위를 조정해 주세요.',
      deliveryDialog: {
        handoffTitle: '검증 결과를 결재 업무로 인계',
        shareTitle: '검증 결과를 팀에 공유',
        providerReceiptHelp:
          '실제 대상 시스템이 요청과 결과 해시가 일치하는 영수증을 반환한 경우에만 완료됩니다.',
        approvalTarget: '결재 대상 또는 승인 그룹',
        requestTitle: '결재 요청 제목',
        requestReason: '인계 사유와 요청 내용',
        requestMetadataHelp: '현재 조사 실행 ID와 출처 정보가 요청 메타데이터에 함께 기록됩니다.',
        recipients: '수신자 ID',
        recipientsHelp:
          '여러 수신자는 쉼표 또는 줄바꿈으로 구분하세요. 수신자 또는 팀 중 하나는 필수입니다.',
        teamId: '팀 ID',
        permission: '공유 권한',
        permissionView: '보기',
        permissionComment: '보기 및 댓글',
        expiresAt: '공유 만료 시각',
        expiryHelp: '5분 이후부터 90일 이내의 만료 시각을 지정하세요.',
        validationError: '필수 대상과 요청 정보를 올바르게 입력하세요.',
        cancel: '취소',
        submitHandoff: '결재 인계 요청',
        submitShare: '팀 공유 요청',
      },
      states: {
        QUEUED: '대기 중',
        RUNNING: '실행 중',
        PAUSED: '일시 중지',
        PARTIAL: '부분 완료',
        CONFLICT: '충돌 확인 필요',
        CANCELLING: '취소 중',
        CANCELLED: '취소됨',
        FAILED: '실패',
        COMPLETED: '검증 완료',
      },
      deliverableLabels: {
        REPORT: '상세 보고서',
        EXECUTIVE_SUMMARY: '경영진 요약',
        COMPARISON: '비교 분석표',
        SOURCE_MAP: '출처 맵',
      },
      sourceLabels: {
        WORK_ITEM: '통합 업무',
        MAIL: '메일',
        CALENDAR: '캘린더',
        ARTIFACT: '팀 산출물',
        APPROVAL_REQUEST: '전자결재 요청',
      },
      deliveryLabels: {
        ARTIFACT: '산출물로 저장',
        PROPOSAL: 'AI 제안 생성',
        EXPORT: '파일 내보내기',
        HANDOFF: '업무 앱으로 인계',
        SHARE: '팀에 공유',
        ROUTINE: '정기 루틴 등록',
      },
    } as const;
  }
  return {
    eyebrow: 'DEEP RESEARCH · READ-ONLY',
    title: 'Deep Research',
    description:
      'Confirm the objective, allowed sources, success criteria, and limits before evidence-led research begins.',
    back: 'Back to conversation',
    objective: '1. Objective and success criteria',
    goal: 'Research objective',
    goalHint: 'Describe the decision and scope.',
    question: 'Key research question',
    questionHint: 'State the question to verify.',
    criteria: 'Success criteria',
    criteriaHint: 'Enter one per line.',
    sources: '2. Allowed and excluded sources',
    deliverables: '3. Deliverables',
    requireAll: 'Require every allowed source before completion',
    limits: 'Execution and resource limits',
    minutes: 'Maximum minutes',
    sourceLimit: 'Maximum sources',
    tokenLimit: 'Maximum tokens',
    guardTitle: 'Zero-write execution guarantee',
    guardBody:
      'Research runs with read-only access. Saving, sharing, and handoff require separate reviewed commands after completion.',
    save: 'Save validated plan',
    saving: 'Saving plan…',
    start: 'Launch deep research',
    starting: 'Starting research…',
    reset: 'Reset plan',
    planReady: 'This plan is ready to run.',
    planDraft: 'The draft is saved. It must pass server validation before launch.',
    unsaved: 'This plan has unsaved changes. Save and validate it before launch.',
    errors: {
      GOAL: 'Enter at least 10 characters for the objective.',
      QUESTION: 'Enter at least 10 characters for the question.',
      CRITERIA: 'Add at least one success criterion.',
      DELIVERABLE: 'Choose at least one deliverable.',
      SOURCE: 'Allow at least one source.',
      BUDGET: 'Enter integer limits within the allowed ranges.',
    },
    operationFailed:
      'The server did not complete the request. You can retry safely with the same request identity.',
    runTitle: 'Live deep research run',
    runId: 'Run ID',
    steps: 'Completed steps',
    discovered: 'Discovered sources',
    verified: 'Verified citations',
    failedSources: 'Unavailable sources',
    recovery: 'Recovery guidance',
    pause: 'Pause',
    resume: 'Resume',
    exclude: 'Exclude source and continue',
    reprobe: 'Re-probe source access',
    extend: 'Extend by 15 minutes',
    cancel: 'Safe cancel',
    retry: 'Reload',
    loading: 'Loading the research run.',
    report: 'Verified report',
    viewFullscreen: 'View report full screen',
    closeFullscreen: 'Close full screen',
    evidence: 'Source evidence',
    noEvidence: 'No verified citations are available.',
    outputs: 'Next action handoff',
    outputHint: 'Each command shows the real server state and receipt.',
    deliveryRequiresCompletion: 'Available after a verified completion receipt is issued.',
    deliveryCapabilityLoading: 'Checking the server capability state.',
    receipt: 'Completion receipt',
    copyReceipt: 'Copy receipt ID',
    copiedReceipt: 'Copied',
    openDeliveryTarget: 'Open target',
    receiptFingerprint: 'Receipt fingerprint',
    receiptIssuedAt: 'Issued at',
    receiptLedgerDetail: 'Ledger detail link',
    receiptDetailUnavailable: 'Unavailable — not returned by the current server contract',
    noReceipt: 'A completion receipt has not been issued.',
    deliveryQueued: 'The follow-up job was accepted.',
    evidenceActions: 'Verified output and recovery actions',
    evidenceActionsHelp: 'Only actions backed by the current run response and receipt are enabled.',
    rawDownload: 'Extract raw dataset (JSON)',
    pdfDownload: 'Export official report (PDF)',
    receiptDownload: 'Download receipt',
    auditLedger: 'Open execution audit ledger',
    saveFork: 'Save as a new fork',
    mergeLatest: 'Merge latest server version',
    keepLocal: 'Keep local draft',
    sensitivity: 'Recalculate scenario sensitivity',
    cacheFallback: 'Use cached fallback',
    actualRunEvidence: 'Uses evidence verified in the current server run response.',
    serverDownloadReady: 'Uses the permission-checked, audited server download.',
    providerActionUnavailable:
      'The current run contract does not provide this operation. Follow the recovery guidance to adjust scope.',
    deliveryDialog: {
      handoffTitle: 'Handoff verified result for approval',
      shareTitle: 'Share verified result with the team',
      providerReceiptHelp:
        'Completion requires a target-system receipt bound to this request and result digest.',
      approvalTarget: 'Approval target or group',
      requestTitle: 'Approval request title',
      requestReason: 'Handoff reason and request details',
      requestMetadataHelp: 'The research run ID and source are recorded with the request metadata.',
      recipients: 'Recipient IDs',
      recipientsHelp:
        'Separate recipients with commas or new lines. A recipient or team is required.',
      teamId: 'Team ID',
      permission: 'Share permission',
      permissionView: 'View',
      permissionComment: 'View and comment',
      expiresAt: 'Share expiry',
      expiryHelp: 'Choose an expiry between five minutes and 90 days from now.',
      validationError: 'Enter valid required targets and request details.',
      cancel: 'Cancel',
      submitHandoff: 'Request approval handoff',
      submitShare: 'Request team share',
    },
    states: {
      QUEUED: 'Queued',
      RUNNING: 'Running',
      PAUSED: 'Paused',
      PARTIAL: 'Partial',
      CONFLICT: 'Conflict',
      CANCELLING: 'Cancelling',
      CANCELLED: 'Cancelled',
      FAILED: 'Failed',
      COMPLETED: 'Verified',
    },
    deliverableLabels: {
      REPORT: 'Detailed report',
      EXECUTIVE_SUMMARY: 'Executive summary',
      COMPARISON: 'Comparison',
      SOURCE_MAP: 'Source map',
    },
    sourceLabels: {
      WORK_ITEM: 'Work',
      MAIL: 'Mail',
      CALENDAR: 'Calendar',
      ARTIFACT: 'Team artifacts',
      APPROVAL_REQUEST: 'Approval requests',
    },
    deliveryLabels: {
      ARTIFACT: 'Save as artifact',
      PROPOSAL: 'Create AI proposal',
      EXPORT: 'Export file',
      HANDOFF: 'Handoff to work app',
      SHARE: 'Share with team',
      ROUTINE: 'Create recurring routine',
    },
  } as const;
}
