import { useTranslation } from 'react-i18next';
import { resolveSupportedLocale } from '@dwp-frontend/shared-i18n';

const COPY = {
  ko: {
    refresh: '새로고침',
    retry: '다시 시도',
    loading: '운영 데이터를 불러오는 중입니다.',
    unavailableTitle: '운영 데이터를 확인할 수 없습니다',
    unavailableDescription:
      '관리 API가 아직 연결되지 않았거나 현재 범위에서 사용할 수 없습니다. 연결 상태와 권한을 확인한 뒤 다시 시도하세요.',
    notConfigured: '설정 필요',
    partial: '부분 가용',
    unavailable: '사용 불가',
    live: '실시간 운영 데이터',
    generatedAt: '마지막 생성',
    command: {
      authorityUnavailable:
        '현재 관리자 범위의 보안 권한을 검증할 수 없어 명령 실행을 차단했습니다.',
      reason: '변경 사유',
      reasonHelp: '감사자가 판단할 수 있도록 10자 이상 입력하세요.',
      ticket: '티켓 또는 사건 번호',
      evidence: '증거 참조',
      evidenceHelp: '쉼표로 구분된 감사 이벤트, 평가 실행, 문서 참조를 입력하세요.',
      acknowledgement: '영향 범위와 복구 방법을 검토했습니다.',
      submit: '승인 요청',
      submitting: '명령을 등록하는 중',
      cancel: '닫기',
      title: 'Governed Command 검토',
      reviewExisting: '승인 대기 명령 검토',
      description: '변경 전후, 영향 범위, 사유와 증거를 확인한 뒤 Maker-Checker 승인을 요청합니다.',
      pendingApproval: 'Checker 승인 대기',
      approve: '승인',
      reject: '거절',
      cancelCommand: '실행 취소',
      retryCommand: '재시도',
      rollback: '롤백',
      refreshStatus: '상태 새로고침',
      receipt: '완료 영수증',
      noReceipt: '실제 업무 완료 영수증이 아직 발급되지 않았습니다.',
      transitionReason: '결정 또는 후속 조치 사유',
      transitionEvidence: '결정 증거 참조',
      failed: '명령을 처리하지 못했습니다. 문제 세부정보와 복구 안내를 확인하세요.',
      statusFailed: '최신 명령 상태를 검증하지 못했습니다. 기존 상태를 완료로 간주하지 않습니다.',
      transitionConflict:
        '다른 결정이 먼저 기록되어 명령 version이 바뀌었습니다. 최신 상태를 다시 검토하세요.',
      conflict: '대상 버전이 변경되었습니다. 최신 상태를 다시 불러온 뒤 변경 내용을 재검토하세요.',
      reconcile: '최신 버전 다시 불러오기',
      queueUnavailable:
        '승인 대기 명령을 검증할 수 없습니다. 목록을 비어 있는 것으로 간주하지 않습니다.',
    },
    models: {
      eyebrow: 'A-01 · AI Control Plane',
      title: '모델 및 라우팅',
      description:
        'Provider, 모델, 업무별 라우팅, 예산과 장애 복구를 하나의 운영 경계에서 관리합니다.',
      providers: 'Provider 및 모델 상태',
      policies: '업무 라우팅 정책',
      simulator: '라우팅 시뮬레이터',
      approvals: '승인 대기',
      canaries: 'Canary',
      emergency: '긴급 중단',
      recovery: '서비스 복구',
      updatePolicy: '정책 변경',
      startCanary: 'Canary 시작',
      rollback: '이전 버전 복구',
      approvalQueue: 'Checker 승인함',
      approvalQueueDescription:
        'Maker가 제출한 변경 전후, 영향, 복구 계획과 증거를 검토하고 독립적으로 결정합니다.',
      approvalQueueEmpty: '현재 검증된 승인 대기 명령이 없습니다.',
      reviewCommand: '승인 명령 검토',
    },
    agents: {
      title: 'Builder · 평가 · 배포 Governance',
      description:
        'Prompt diff, source/tool binding, memory policy와 평가 결과를 검토한 뒤 승격·롤백합니다.',
      promote: '승격 요청',
      rollback: '롤백',
      kill: 'Kill switch',
    },
    connectors: {
      title: 'Connector · ACL 운영',
      description: '소유자와 범위, 저장소, 그룹 매핑, secret, sync 및 삭제 수명주기를 운영합니다.',
      create: 'Connector 추가',
      probe: 'ACL Probe',
      sync: '동기화',
      reindex: '재색인',
      rotate: 'Secret 교체',
      reduce: '범위 축소',
      revoke: '회수',
      delete: '삭제',
    },
    evaluation: {
      title: '지속 평가 및 Production Monitoring',
      description:
        'Dataset, PII 검토, 버전 고정 비교 실행과 운영 Drift를 release Gate 증거로 연결합니다.',
      importDataset: 'Dataset 가져오기',
      compare: '비교 실행',
      attachEvidence: 'Gate 증거 연결',
    },
    incidents: {
      title: 'AI Incident Workbench',
      description: '영향부터 확인하고 격리, replay, 보상, 검증, 재개 승인과 사후보고를 수행합니다.',
      contain: 'Containment',
      quarantine: 'Run 격리',
      replay: 'Replay',
      compensate: '보상 실행',
      recover: '복구 승인',
      close: '사고 종료',
    },
    outcomes: {
      title: 'Outcome · Quality · Cost',
      description:
        '분모와 freshness, privacy threshold를 보존하며 성과·품질·비용과 개선 Backlog를 연결합니다.',
      export: '집계 내보내기',
      simulate: '비용 시뮬레이션',
      createBacklog: 'Backlog 생성',
      backlog: 'Backlog 변경',
      budget: '예산 정책 변경',
    },
  },
  en: {
    refresh: 'Refresh',
    retry: 'Retry',
    loading: 'Loading operational data.',
    unavailableTitle: 'Operational data is unavailable',
    unavailableDescription:
      'The management API is not connected or is unavailable for this scope. Check the connection and authority, then retry.',
    notConfigured: 'Configuration required',
    partial: 'Partially available',
    unavailable: 'Unavailable',
    live: 'Live operational data',
    generatedAt: 'Generated',
    command: {
      authorityUnavailable:
        'Command execution is blocked because secure authority for this management scope cannot be verified.',
      reason: 'Change reason',
      reasonHelp: 'Enter at least 10 characters so an auditor can assess the decision.',
      ticket: 'Ticket or incident',
      evidence: 'Evidence references',
      evidenceHelp:
        'Enter audit events, evaluation runs, or document references separated by commas.',
      acknowledgement: 'I reviewed the impact and recovery plan.',
      submit: 'Request approval',
      submitting: 'Registering command',
      cancel: 'Close',
      title: 'Governed command review',
      reviewExisting: 'Review pending command',
      description:
        'Review the before/after state, impact, reason, and evidence before requesting Maker-Checker approval.',
      pendingApproval: 'Awaiting checker approval',
      approve: 'Approve',
      reject: 'Reject',
      cancelCommand: 'Cancel execution',
      retryCommand: 'Retry',
      rollback: 'Rollback',
      refreshStatus: 'Refresh status',
      receipt: 'Completion receipt',
      noReceipt: 'No verified domain completion receipt has been issued yet.',
      transitionReason: 'Decision or follow-up reason',
      transitionEvidence: 'Decision evidence references',
      failed: 'The command failed. Review the problem and recovery guidance.',
      statusFailed:
        'The latest command state could not be verified. The last known state is not treated as complete.',
      transitionConflict:
        'Another decision changed the command version. Refresh and review the latest state before acting.',
      conflict: 'The target version changed. Reload the latest state and review the diff again.',
      reconcile: 'Reload latest version',
      queueUnavailable:
        'The pending command queue could not be verified. It is not treated as empty.',
    },
    models: {
      eyebrow: 'A-01 · AI Control Plane',
      title: 'Models & routing',
      description:
        'Operate providers, models, workload routing, budgets, and recovery within one governed boundary.',
      providers: 'Provider and model health',
      policies: 'Workload routing policies',
      simulator: 'Routing simulator',
      approvals: 'Pending approval',
      canaries: 'Canaries',
      emergency: 'Emergency stop',
      recovery: 'Recover service',
      updatePolicy: 'Change policy',
      startCanary: 'Start canary',
      rollback: 'Restore previous version',
      approvalQueue: 'Checker approval inbox',
      approvalQueueDescription:
        'Independently review the submitted diff, impact, recovery plan, and evidence.',
      approvalQueueEmpty: 'There are no verified commands awaiting approval.',
      reviewCommand: 'Review approval command',
    },
    agents: {
      title: 'Builder, evaluation & rollout governance',
      description:
        'Review prompt diffs, source/tool bindings, memory policy, and evaluations before promotion or rollback.',
      promote: 'Request promotion',
      rollback: 'Rollback',
      kill: 'Kill switch',
    },
    connectors: {
      title: 'Connector & ACL operations',
      description:
        'Operate ownership, scope, repositories, group mapping, secrets, sync, and deletion lifecycle.',
      create: 'Add connector',
      probe: 'ACL probe',
      sync: 'Sync',
      reindex: 'Reindex',
      rotate: 'Rotate secret',
      reduce: 'Reduce scope',
      revoke: 'Revoke',
      delete: 'Delete',
    },
    evaluation: {
      title: 'Continuous evaluation & production monitoring',
      description:
        'Connect datasets, PII review, pinned comparisons, and production drift to release-gate evidence.',
      importDataset: 'Import dataset',
      compare: 'Run comparison',
      attachEvidence: 'Attach gate evidence',
    },
    incidents: {
      title: 'AI incident workbench',
      description:
        'Assess impact, contain, quarantine, replay, compensate, validate, approve recovery, and close.',
      contain: 'Contain',
      quarantine: 'Quarantine run',
      replay: 'Replay',
      compensate: 'Compensate',
      recover: 'Approve recovery',
      close: 'Close incident',
    },
    outcomes: {
      title: 'Outcome, quality & cost',
      description:
        'Connect outcome, quality, cost, and the improvement backlog with denominators, freshness, and privacy thresholds.',
      export: 'Export aggregate',
      simulate: 'Simulate cost',
      createBacklog: 'Create backlog',
      backlog: 'Update backlog',
      budget: 'Change budget policy',
    },
  },
} as const;

export function useDwaionAdminAdvancementCopy() {
  const { t, i18n } = useTranslation('admin');
  const locale = resolveSupportedLocale(i18n.resolvedLanguage, i18n.language);
  return {
    ...COPY[locale],
    ui: {
      common: {
        revisionPrefix: t('dwaionAdvancement.common.revisionPrefix'),
        versionSeparator: t('dwaionAdvancement.common.versionSeparator'),
        checksumPrefix: t('dwaionAdvancement.common.checksumPrefix'),
        checksumSeparator: t('dwaionAdvancement.common.checksumSeparator'),
        sampleSizePrefix: t('dwaionAdvancement.common.sampleSizePrefix'),
        projected: t('dwaionAdvancement.common.projected'),
        modelsUnit: t('dwaionAdvancement.common.modelsUnit'),
        runsUnit: t('dwaionAdvancement.common.runsUnit'),
      },
      agents: {
        allowedWork: t('dwaionAdvancement.agents.allowedWork'),
        prohibitedWork: t('dwaionAdvancement.agents.prohibitedWork'),
        semanticVersionDiff: t('dwaionAdvancement.agents.semanticVersionDiff'),
        inputSchema: t('dwaionAdvancement.agents.inputSchema'),
        outputSchema: t('dwaionAdvancement.agents.outputSchema'),
        sourceBindings: t('dwaionAdvancement.agents.sourceBindings'),
        toolBindings: t('dwaionAdvancement.agents.toolBindings'),
        pinnedRolloutContract: t('dwaionAdvancement.agents.pinnedRolloutContract'),
        modelRoute: t('dwaionAdvancement.agents.modelRoute'),
        memoryPolicy: t('dwaionAdvancement.agents.memoryPolicy'),
        pinnedEvaluationEvidence: t('dwaionAdvancement.agents.pinnedEvaluationEvidence'),
        canaryTrafficPercent: t('dwaionAdvancement.agents.canaryTrafficPercent'),
        sandboxEvaluation: t('dwaionAdvancement.agents.sandboxEvaluation'),
        governanceEvidenceSummary: t('dwaionAdvancement.agents.governanceEvidenceSummary'),
        saveGovernedDraft: t('dwaionAdvancement.agents.saveGovernedDraft'),
        signEvaluationCertificate: t('dwaionAdvancement.agents.signEvaluationCertificate'),
      },
      connectors: {
        operationDescription: t('dwaionAdvancement.connectors.operationDescription'),
        repositoryScope: t('dwaionAdvancement.connectors.repositoryScope'),
        principalSamples: t('dwaionAdvancement.connectors.principalSamples'),
        syncMode: t('dwaionAdvancement.connectors.syncMode'),
        staleIndexHandling: t('dwaionAdvancement.connectors.staleIndexHandling'),
        newSecretReference: t('dwaionAdvancement.connectors.newSecretReference'),
        credentialOverlapMinutes: t('dwaionAdvancement.connectors.credentialOverlapMinutes'),
        reducedTenantScope: t('dwaionAdvancement.connectors.reducedTenantScope'),
        excludedRepositories: t('dwaionAdvancement.connectors.excludedRepositories'),
        groupMappingSource: t('dwaionAdvancement.connectors.groupMappingSource'),
        inFlightSync: t('dwaionAdvancement.connectors.inFlightSync'),
        revokeAt: t('dwaionAdvancement.connectors.revokeAt'),
        retentionEvidence: t('dwaionAdvancement.connectors.retentionEvidence'),
        syncStatus: t('dwaionAdvancement.connectors.syncStatus'),
        aclCoverage: t('dwaionAdvancement.connectors.aclCoverage'),
        repositories: t('dwaionAdvancement.connectors.repositories'),
        lastSync: t('dwaionAdvancement.connectors.lastSync'),
        name: t('dwaionAdvancement.connectors.name'),
        providerType: t('dwaionAdvancement.connectors.providerType'),
        owner: t('dwaionAdvancement.connectors.owner'),
        tenantScope: t('dwaionAdvancement.connectors.tenantScope'),
        region: t('dwaionAdvancement.connectors.region'),
        includeRepositories: t('dwaionAdvancement.connectors.includeRepositories'),
        excludeRepositories: t('dwaionAdvancement.connectors.excludeRepositories'),
        secretReference: t('dwaionAdvancement.connectors.secretReference'),
        retentionDays: t('dwaionAdvancement.connectors.retentionDays'),
        deletionPolicy: t('dwaionAdvancement.connectors.deletionPolicy'),
        lifecycleOperations: t('dwaionAdvancement.connectors.lifecycleOperations'),
        lifecycleOperationsDescription: t(
          'dwaionAdvancement.connectors.lifecycleOperationsDescription'
        ),
      },
      emergency: {
        affectedScope: t('dwaionAdvancement.emergency.affectedScope'),
        providerModelScope: t('dwaionAdvancement.emergency.providerModelScope'),
        verifiedFallbackRoute: t('dwaionAdvancement.emergency.verifiedFallbackRoute'),
        inFlightJobs: t('dwaionAdvancement.emergency.inFlightJobs'),
        validationEvidence: t('dwaionAdvancement.emergency.validationEvidence'),
        canaryTrafficPercent: t('dwaionAdvancement.emergency.canaryTrafficPercent'),
        validationMinutes: t('dwaionAdvancement.emergency.validationMinutes'),
        failureThreshold: t('dwaionAdvancement.emergency.failureThreshold'),
        automaticRestopCriteria: t('dwaionAdvancement.emergency.automaticRestopCriteria'),
      },
      evaluation: {
        datasetImport: t('dwaionAdvancement.evaluation.datasetImport'),
        datasetImportDescription: t('dwaionAdvancement.evaluation.datasetImportDescription'),
        name: t('dwaionAdvancement.evaluation.name'),
        owner: t('dwaionAdvancement.evaluation.owner'),
        format: t('dwaionAdvancement.evaluation.format'),
        checksum: t('dwaionAdvancement.evaluation.checksum'),
        schemaMapping: t('dwaionAdvancement.evaluation.schemaMapping'),
        piiHandling: t('dwaionAdvancement.evaluation.piiHandling'),
        pinnedComparison: t('dwaionAdvancement.evaluation.pinnedComparison'),
        pinnedComparisonDescription: t('dwaionAdvancement.evaluation.pinnedComparisonDescription'),
        dataset: t('dwaionAdvancement.evaluation.dataset'),
        eligibilityReviewDescription: t(
          'dwaionAdvancement.evaluation.eligibilityReviewDescription'
        ),
        decision: t('dwaionAdvancement.evaluation.decision'),
        evidenceReferences: t('dwaionAdvancement.evaluation.evidenceReferences'),
        reviewerNote: t('dwaionAdvancement.evaluation.reviewerNote'),
        summaryLabel: t('dwaionAdvancement.evaluation.summaryLabel'),
        safetySimulation: t('dwaionAdvancement.evaluation.safetySimulation'),
        productionDriftReview: t('dwaionAdvancement.evaluation.productionDriftReview'),
        anonymizedSample: t('dwaionAdvancement.evaluation.anonymizedSample'),
        feedbackEvidence: t('dwaionAdvancement.evaluation.feedbackEvidence'),
        recommendation: t('dwaionAdvancement.evaluation.recommendation'),
        requestRawEvidence: t('dwaionAdvancement.evaluation.requestRawEvidence'),
        reviewPii: t('dwaionAdvancement.evaluation.reviewPii'),
        releaseGateOperations: t('dwaionAdvancement.evaluation.releaseGateOperations'),
        releaseGateOperationsDescription: t(
          'dwaionAdvancement.evaluation.releaseGateOperationsDescription'
        ),
      },
      incidents: {
        operationDescription: t('dwaionAdvancement.incidents.operationDescription'),
        isolationScope: t('dwaionAdvancement.incidents.isolationScope'),
        verifiedFallbackRoute: t('dwaionAdvancement.incidents.verifiedFallbackRoute'),
        inFlightHandling: t('dwaionAdvancement.incidents.inFlightHandling'),
        correlationId: t('dwaionAdvancement.incidents.correlationId'),
        owner: t('dwaionAdvancement.incidents.owner'),
        runIdsSelector: t('dwaionAdvancement.incidents.runIdsSelector'),
        quarantineReason: t('dwaionAdvancement.incidents.quarantineReason'),
        sourceRunIds: t('dwaionAdvancement.incidents.sourceRunIds'),
        verifiedCheckpoint: t('dwaionAdvancement.incidents.verifiedCheckpoint'),
        inputReusePolicy: t('dwaionAdvancement.incidents.inputReusePolicy'),
        idempotencyScope: t('dwaionAdvancement.incidents.idempotencyScope'),
        targetRunIds: t('dwaionAdvancement.incidents.targetRunIds'),
        domainAction: t('dwaionAdvancement.incidents.domainAction'),
        compensationPolicy: t('dwaionAdvancement.incidents.compensationPolicy'),
        compensationOwner: t('dwaionAdvancement.incidents.compensationOwner'),
        validationEvidence: t('dwaionAdvancement.incidents.validationEvidence'),
        canaryTrafficPercent: t('dwaionAdvancement.incidents.canaryTrafficPercent'),
        validationMinutes: t('dwaionAdvancement.incidents.validationMinutes'),
        automaticRequarantineCriteria: t(
          'dwaionAdvancement.incidents.automaticRequarantineCriteria'
        ),
        falsePositive: t('dwaionAdvancement.incidents.falsePositive'),
        incidentTicket: t('dwaionAdvancement.incidents.incidentTicket'),
        communicationsEvidence: t('dwaionAdvancement.incidents.communicationsEvidence'),
        postmortemReference: t('dwaionAdvancement.incidents.postmortemReference'),
        resolutionSummary: t('dwaionAdvancement.incidents.resolutionSummary'),
        summaryLabel: t('dwaionAdvancement.incidents.summaryLabel'),
        affectedRuns: t('dwaionAdvancement.incidents.affectedRuns'),
        affectedUsers: t('dwaionAdvancement.incidents.affectedUsers'),
        opened: t('dwaionAdvancement.incidents.opened'),
        immutableTimeline: t('dwaionAdvancement.incidents.immutableTimeline'),
        replayExplanation: t('dwaionAdvancement.incidents.replayExplanation'),
        responseOperations: t('dwaionAdvancement.incidents.responseOperations'),
        responseOperationsDescription: t(
          'dwaionAdvancement.incidents.responseOperationsDescription'
        ),
      },
      outcomes: {
        costSimulation: t('dwaionAdvancement.outcomes.costSimulation'),
        costSimulationDescription: t('dwaionAdvancement.outcomes.costSimulationDescription'),
        workloadVolume: t('dwaionAdvancement.outcomes.workloadVolume'),
        averageInputTokens: t('dwaionAdvancement.outcomes.averageInputTokens'),
        averageOutputTokens: t('dwaionAdvancement.outcomes.averageOutputTokens'),
        currentRoute: t('dwaionAdvancement.outcomes.currentRoute'),
        candidateRoute: t('dwaionAdvancement.outcomes.candidateRoute'),
        qualityFloor: t('dwaionAdvancement.outcomes.qualityFloor'),
        latencyLimit: t('dwaionAdvancement.outcomes.latencyLimit'),
        costLimit: t('dwaionAdvancement.outcomes.costLimit'),
        expectedEffect: t('dwaionAdvancement.outcomes.expectedEffect'),
        risksAssumptions: t('dwaionAdvancement.outcomes.risksAssumptions'),
        improvementBacklog: t('dwaionAdvancement.outcomes.improvementBacklog'),
        improvementBacklogDescription: t(
          'dwaionAdvancement.outcomes.improvementBacklogDescription'
        ),
        title: t('dwaionAdvancement.outcomes.title'),
        ownerTeam: t('dwaionAdvancement.outcomes.ownerTeam'),
        priority: t('dwaionAdvancement.outcomes.priority'),
        metricEvidence: t('dwaionAdvancement.outcomes.metricEvidence'),
        state: t('dwaionAdvancement.outcomes.state'),
        problemCluster: t('dwaionAdvancement.outcomes.problemCluster'),
        targetValue: t('dwaionAdvancement.outcomes.targetValue'),
        linkedRelease: t('dwaionAdvancement.outcomes.linkedRelease'),
        tokenBudgetPolicy: t('dwaionAdvancement.outcomes.tokenBudgetPolicy'),
        tokenBudgetDescription: t('dwaionAdvancement.outcomes.tokenBudgetDescription'),
        scope: t('dwaionAdvancement.outcomes.scope'),
        budgetTokens: t('dwaionAdvancement.outcomes.budgetTokens'),
        enforcement: t('dwaionAdvancement.outcomes.enforcement'),
        enforcementActive: t('dwaionAdvancement.outcomes.enforcementActive'),
        enforcementStaged: t('dwaionAdvancement.outcomes.enforcementStaged'),
        enforcementDisabledWarning: t('dwaionAdvancement.outcomes.enforcementDisabledWarning'),
        enforcementDisabledRecovery: t('dwaionAdvancement.outcomes.enforcementDisabledRecovery'),
        drillDownScope: t('dwaionAdvancement.outcomes.drillDownScope'),
        organization: t('dwaionAdvancement.outcomes.organization'),
        workType: t('dwaionAdvancement.outcomes.workType'),
        applyScope: t('dwaionAdvancement.outcomes.applyScope'),
        summaryLabel: t('dwaionAdvancement.outcomes.summaryLabel'),
        cohortsDenominators: t('dwaionAdvancement.outcomes.cohortsDenominators'),
        tokenBudgets: t('dwaionAdvancement.outcomes.tokenBudgets'),
        deliveryOperations: t('dwaionAdvancement.outcomes.deliveryOperations'),
        deliveryOperationsDescription: t(
          'dwaionAdvancement.outcomes.deliveryOperationsDescription'
        ),
      },
      models: {
        summaryLabel: t('dwaionAdvancement.models.summaryLabel'),
        p95: t('dwaionAdvancement.models.p95'),
        success: t('dwaionAdvancement.models.success'),
        primaryModel: t('dwaionAdvancement.models.primaryModel'),
        fallbackModel: t('dwaionAdvancement.models.fallbackModel'),
        budgetAction: t('dwaionAdvancement.models.budgetAction'),
        dailyBudget: t('dwaionAdvancement.models.dailyBudget'),
        modalities: t('dwaionAdvancement.models.modalities'),
        agentScope: t('dwaionAdvancement.models.agentScope'),
        inFlightJobs: t('dwaionAdvancement.models.inFlightJobs'),
        workloadConstraints: t('dwaionAdvancement.models.workloadConstraints'),
        emergencyControl: t('dwaionAdvancement.models.emergencyControl'),
        requesterRole: t('dwaionAdvancement.models.requesterRole'),
        agentId: t('dwaionAdvancement.models.agentId'),
        dataClassification: t('dwaionAdvancement.models.dataClassification'),
        modality: t('dwaionAdvancement.models.modality'),
        estimatedTokens: t('dwaionAdvancement.models.estimatedTokens'),
        latestSimulationResult: t('dwaionAdvancement.models.latestSimulationResult'),
        targetPrefix: t('dwaionAdvancement.models.targetPrefix'),
        latencyFallbackSeparator: t('dwaionAdvancement.models.latencyFallbackSeparator'),
        controlOperations: t('dwaionAdvancement.models.controlOperations'),
        controlOperationsDescription: t('dwaionAdvancement.models.controlOperationsDescription'),
      },
      modelRegistry: {
        providerRegistryTitle: t('dwaionAdvancement.modelRegistry.providerRegistryTitle'),
        providerRegistryDescription: t(
          'dwaionAdvancement.modelRegistry.providerRegistryDescription'
        ),
        providerRegistryLabel: t('dwaionAdvancement.modelRegistry.providerRegistryLabel'),
        providerModel: t('dwaionAdvancement.modelRegistry.providerModel'),
        modalityLimit: t('dwaionAdvancement.modelRegistry.modalityLimit'),
        contextUnit: t('dwaionAdvancement.modelRegistry.contextUnit'),
        allowedData: t('dwaionAdvancement.modelRegistry.allowedData'),
        governanceRegion: t('dwaionAdvancement.modelRegistry.governanceRegion'),
        credential: t('dwaionAdvancement.modelRegistry.credential'),
        runtime: t('dwaionAdvancement.modelRegistry.runtime'),
        routingMatrixTitle: t('dwaionAdvancement.modelRegistry.routingMatrixTitle'),
        routingMatrixDescription: t('dwaionAdvancement.modelRegistry.routingMatrixDescription'),
        failClosed: t('dwaionAdvancement.modelRegistry.failClosed'),
      },
      command: {
        submittedReviewRecord: t('dwaionAdvancement.command.submittedReviewRecord'),
        recoveryPlan: t('dwaionAdvancement.command.recoveryPlan'),
        domainReceipt: t('dwaionAdvancement.command.domainReceipt'),
      },
    },
  };
}
