import { defineProductManifest } from '../../components/product-manifest';
import {
  HCM_MANAGEMENT_NAVIGATION,
  HCM_OPERATIONS_NAVIGATION,
  HCM_PERSONAL_NAVIGATION,
  HCM_TEAM_NAVIGATION,
} from './hcm-navigation';

export const HCM_PRODUCT_MANIFEST = defineProductManifest({
  id: 'hcm',
  appKey: 'APP.HCM',
  basePath: '/hr',
  surfaces: [
    {
      id: 'hcm.personal',
      plane: 'work',
      labelKey: 'navigation.groups.hcm.personal',
      taskKinds: ['work'],
      routeMatchers: [
        { kind: 'exact', path: '/hr/home' },
        { kind: 'exact', path: '/hr/me' },
        { kind: 'exact', path: '/hr/time' },
        { kind: 'exact', path: '/hr/absence' },
        { kind: 'exact', path: '/hr/benefits' },
        { kind: 'exact', path: '/hr/pay' },
        { kind: 'exact', path: '/hr/talent' },
        { kind: 'exact', path: '/hr/services' },
        { kind: 'exact', path: '/hr/directory' },
        { kind: 'exact', path: '/hr/organization' },
      ],
      indexPath: '/hr/home',
      navigation: HCM_PERSONAL_NAVIGATION,
      entryAccess: {
        type: 'policy',
        accessPolicyKey: 'hcm.personal-access.v1',
        requiresProductEntitlement: false,
      },
      supportedScopeKinds: ['SELF'],
      shellProfile: 'product-work',
    },
    {
      id: 'hcm.team',
      plane: 'work',
      labelKey: 'navigation.groups.hcm.team',
      taskKinds: ['team'],
      routeMatchers: [{ kind: 'prefix', path: '/hr/team' }],
      indexPath: '/hr/team',
      navigation: HCM_TEAM_NAVIGATION,
      entryAccess: {
        type: 'policy',
        accessPolicyKey: 'hcm.team-access.v1',
        requiresProductEntitlement: false,
      },
      supportedScopeKinds: ['TEAM', 'ORG_UNIT'],
      shellProfile: 'product-work',
    },
    {
      id: 'hcm.operations',
      plane: 'management',
      labelKey: 'navigation.groups.hcm.operate',
      taskKinds: ['operations'],
      routeMatchers: [{ kind: 'prefix', path: '/hr/operations' }],
      indexPath: '/hr/operations',
      navigation: HCM_OPERATIONS_NAVIGATION,
      entryAccess: {
        type: 'policy',
        accessPolicyKey: 'hcm.operations-access.v1',
        requiresProductEntitlement: false,
      },
      supportedScopeKinds: ['ORG_UNIT', 'LEGAL_ENTITY'],
      shellProfile: 'product-management',
      returnSurfaceId: 'hcm.personal',
    },
    {
      id: 'hcm.management',
      plane: 'management',
      labelKey: 'navigation.groups.hcm.foundation',
      taskKinds: ['operations', 'administration'],
      routeMatchers: [
        { kind: 'exact', path: '/hr/manage' },
        { kind: 'prefix', path: '/hr/design' },
        { kind: 'prefix', path: '/hr/data' },
      ],
      indexPath: '/hr/manage',
      navigation: HCM_MANAGEMENT_NAVIGATION,
      entryAccess: {
        type: 'capability',
        entryCapabilityMode: 'ANY',
        requiredCapabilityContractKeys: [
          'hcm.org-design.read',
          'hcm.reference.read',
          'hcm.integration.read',
          'hcm.controlled-export.read',
        ],
        requiresProductEntitlement: false,
      },
      supportedScopeKinds: ['RESOURCE_SET', 'RESOURCE', 'LEGAL_ENTITY', 'POLICY_NODE'],
      shellProfile: 'product-management',
      returnSurfaceId: 'hcm.personal',
    },
  ],
});
