/**
 * Synapse Remote 라우트 경로 상수
 * 백엔드 Menu Tree API의 path와 동일하게 유지한다.
 * 메뉴 클릭 시 item.path로 이동하므로 여기 정의된 path와 BE path가 일치해야 한다.
 */
export const SYNAPSE_ROUTES = {
  ROOT: '/synapse',
  DASHBOARD: '/synapse',
  AUTONOMY: '/synapse/autonomy',
  CASES: '/synapse/cases',
  CASE_DETAIL: '/synapse/cases/:id',
  ANOMALIES: '/synapse/anomalies',
  OPTIMIZATION: '/synapse/optimization',
  ACTIONS: '/synapse/actions',
  ARCHIVE: '/synapse/archive',
  DOCUMENTS: '/synapse/documents',
  DOCUMENT_DETAIL: '/synapse/documents/:bukrs/:belnr/:gjahr',
  OPEN_ITEMS: '/synapse/open-items',
  ENTITIES: '/synapse/entities',
  ENTITY_DETAIL: '/synapse/entities/:id',
  LINEAGE: '/synapse/lineage',
  RAG: '/synapse/rag',
  RAG_DOCUMENT_DETAIL: '/synapse/rag/:docId',
  POLICIES: '/synapse/policies',
  POLICY_PROFILE_DETAIL: '/synapse/policies/:profileId',
  GUARDRAILS: '/synapse/guardrails',
  DICTIONARY: '/synapse/dictionary',
  FEEDBACK: '/synapse/feedback',
  RECONCILIATION: '/synapse/reconciliation',
  RECON_RUN_DETAIL: '/synapse/reconciliation/:runId',
  ACTION_RECON: '/synapse/action-recon',
  AUDIT: '/synapse/audit',
  ANALYTICS: '/synapse/analytics',
  GOVERNANCE: '/synapse/governance',
  AGENT_CONFIG: '/synapse/agent-config',
  INTEGRATIONS: '/synapse/integrations',
  ADMIN: '/synapse/admin',
} as const;

/** Route path만 (React Router path 패턴용, 선행 슬래시 없이 사용 가능) */
export const SYNAPSE_ROUTE_PATHS = {
  ROOT: 'synapse',
  DASHBOARD: 'synapse',
  AUTONOMY: 'synapse/autonomy',
  CASES: 'synapse/cases',
  CASE_DETAIL: 'synapse/cases/:id',
  ANOMALIES: 'synapse/anomalies',
  OPTIMIZATION: 'synapse/optimization',
  ACTIONS: 'synapse/actions',
  ARCHIVE: 'synapse/archive',
  DOCUMENTS: 'synapse/documents',
  DOCUMENT_DETAIL: 'synapse/documents/:id',
  OPEN_ITEMS: 'synapse/open-items',
  ENTITIES: 'synapse/entities',
  ENTITY_DETAIL: 'synapse/entities/:id',
  LINEAGE: 'synapse/lineage',
  RAG: 'synapse/rag',
  POLICIES: 'synapse/policies',
  GUARDRAILS: 'synapse/guardrails',
  DICTIONARY: 'synapse/dictionary',
  FEEDBACK: 'synapse/feedback',
  RECONCILIATION: 'synapse/reconciliation',
  ACTION_RECON: 'synapse/action-recon',
  AUDIT: 'synapse/audit',
  ANALYTICS: 'synapse/analytics',
  GOVERNANCE: 'synapse/governance',
  AGENT_CONFIG: 'synapse/agent-config',
  INTEGRATIONS: 'synapse/integrations',
  ADMIN: 'synapse/admin',
} as const;
