-- SYS G2 dwp-auth-server service-local physical migration blueprint.
-- AUTHORITATIVE SERVICE BOUNDARY: execute only in the dwp-auth-server database.
-- The catalog file g2-physical-schema.sql is retained for review parity and is not an executable migration.
-- Requires PostgreSQL pgcrypto/gen_random_uuid() from the governed Auth database baseline.
-- Integration Control assigns the final Flyway version; this file contains no Platform-owned table or FK.

BEGIN;

CREATE TABLE sys_product_access_package_catalog (
    package_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    product_key VARCHAR(80) NOT NULL,
    package_code VARCHAR(120) NOT NULL,
    catalog_version INTEGER NOT NULL CHECK (catalog_version > 0),
    lifecycle_state VARCHAR(24) NOT NULL CHECK (lifecycle_state IN ('DRAFT','ACTIVE','RETIRED')),
    risk_level VARCHAR(16) NOT NULL CHECK (risk_level IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    app_resource_key VARCHAR(120) NOT NULL,
    display_name_key VARCHAR(240) NOT NULL,
    description_key VARCHAR(240) NOT NULL,
    definition_digest CHAR(64) NOT NULL CHECK (definition_digest ~ '^[0-9a-f]{64}$'),
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activated_by UUID,
    activated_at TIMESTAMPTZ,
    retired_by UUID,
    retired_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    CONSTRAINT uq_sys_product_access_package_public UNIQUE (public_id),
    CONSTRAINT uq_sys_product_access_package_version UNIQUE (product_key, package_code, catalog_version),
    CONSTRAINT uq_sys_product_access_package_identity UNIQUE (package_id, public_id, catalog_version),
    CONSTRAINT ck_sys_product_access_package_four_eyes CHECK (
        activated_by IS NULL OR activated_by <> created_by
    ),
    CONSTRAINT ck_sys_product_access_package_lifecycle CHECK (
        (lifecycle_state = 'DRAFT'
            AND activated_by IS NULL AND activated_at IS NULL
            AND retired_by IS NULL AND retired_at IS NULL)
        OR (lifecycle_state = 'ACTIVE'
            AND activated_by IS NOT NULL AND activated_at IS NOT NULL
            AND retired_by IS NULL AND retired_at IS NULL)
        OR (lifecycle_state = 'RETIRED'
            AND activated_by IS NOT NULL AND activated_at IS NOT NULL
            AND retired_by IS NOT NULL AND retired_at IS NOT NULL)
    )
);

CREATE TABLE sys_product_access_package_roles (
    package_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT NOT NULL,
    role_code VARCHAR(160) NOT NULL,
    ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sys_product_access_package_role UNIQUE (package_id, role_code),
    CONSTRAINT uq_sys_product_access_package_role_ordinal UNIQUE (package_id, ordinal),
    CONSTRAINT fk_sys_product_access_package_role_package FOREIGN KEY (package_id)
        REFERENCES sys_product_access_package_catalog(package_id)
);

CREATE TABLE sys_product_access_package_conflicts (
    conflict_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_key VARCHAR(80) NOT NULL,
    rule_code VARCHAR(160) NOT NULL,
    rule_version INTEGER NOT NULL CHECK (rule_version > 0),
    left_subject_type VARCHAR(24) NOT NULL CHECK (left_subject_type IN ('PACKAGE','ROLE','DUTY','PACKAGE_SET')),
    left_subject_code VARCHAR(2000) NOT NULL,
    right_subject_type VARCHAR(24) NOT NULL CHECK (right_subject_type IN ('PACKAGE','ROLE','DUTY')),
    right_subject_code VARCHAR(160) NOT NULL,
    scope_dimensions VARCHAR(1000) NOT NULL,
    time_overlap_required BOOLEAN NOT NULL DEFAULT TRUE,
    enforcement_mode VARCHAR(16) NOT NULL CHECK (enforcement_mode IN ('BLOCK','WARN')),
    lifecycle_state VARCHAR(16) NOT NULL CHECK (lifecycle_state IN ('DRAFT','ACTIVE','RETIRED')),
    definition_digest CHAR(64) NOT NULL CHECK (definition_digest ~ '^[0-9a-f]{64}$'),
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activated_by UUID,
    activated_at TIMESTAMPTZ,
    retired_by UUID,
    retired_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_product_access_package_conflict UNIQUE (product_key, rule_code, rule_version),
    CONSTRAINT ck_sys_product_access_package_conflict_four_eyes CHECK (
        activated_by IS NULL OR activated_by <> created_by
    ),
    CONSTRAINT ck_sys_product_access_package_conflict_lifecycle CHECK (
        (lifecycle_state = 'DRAFT'
            AND activated_by IS NULL AND activated_at IS NULL
            AND retired_by IS NULL AND retired_at IS NULL)
        OR (lifecycle_state = 'ACTIVE'
            AND activated_by IS NOT NULL AND activated_at IS NOT NULL
            AND retired_by IS NULL AND retired_at IS NULL)
        OR (lifecycle_state = 'RETIRED'
            AND activated_by IS NOT NULL AND activated_at IS NOT NULL
            AND retired_by IS NOT NULL AND retired_at IS NOT NULL)
    )
);

CREATE TABLE com_product_access_package_assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    package_id BIGINT NOT NULL REFERENCES sys_product_access_package_catalog(package_id),
    package_public_id UUID NOT NULL,
    package_catalog_version INTEGER NOT NULL CHECK (package_catalog_version > 0),
    principal_type VARCHAR(16) NOT NULL CHECK (principal_type IN ('USER','GROUP','SERVICE')),
    principal_public_id UUID NOT NULL,
    scope_fingerprint CHAR(64) NOT NULL CHECK (scope_fingerprint ~ '^[0-9a-f]{64}$'),
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    lifecycle_state VARCHAR(32) NOT NULL CHECK (lifecycle_state IN (
        'DRAFT','PENDING_APPROVAL','APPROVED','PENDING_PROJECTION','ACTIVE',
        'DEGRADED','SUSPENDED','EXPIRED','REVOKED','REJECTED')),
    justification VARCHAR(2000) NOT NULL,
    review_due_at TIMESTAMPTZ,
    source_kind VARCHAR(24) NOT NULL CHECK (source_kind IN ('DIRECT','GROUP','SCIM','DELEGATION','BREAK_GLASS')),
    source_reference VARCHAR(240),
    authored_by UUID NOT NULL,
    approved_by UUID,
    approved_at TIMESTAMPTZ,
    activated_by UUID,
    activated_at TIMESTAMPTZ,
    revoked_by UUID,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    CONSTRAINT uq_com_product_access_assignment_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_com_product_access_assignment_tenant_id UNIQUE (tenant_id, assignment_id),
    CONSTRAINT fk_com_product_access_assignment_package FOREIGN KEY (package_id, package_public_id, package_catalog_version)
        REFERENCES sys_product_access_package_catalog(package_id, public_id, catalog_version),
    CONSTRAINT ck_com_product_access_assignment_period CHECK (valid_to IS NULL OR valid_from < valid_to),
    CONSTRAINT ck_com_product_access_assignment_four_eyes CHECK (
        approved_by IS NULL OR approved_by <> authored_by
    ),
    CONSTRAINT ck_com_product_access_assignment_approval_state CHECK (
        lifecycle_state NOT IN ('APPROVED','PENDING_PROJECTION','ACTIVE','DEGRADED','SUSPENDED','EXPIRED','REVOKED')
        OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)
    ),
    CONSTRAINT ck_com_product_access_assignment_activation_state CHECK (
        lifecycle_state NOT IN ('ACTIVE','DEGRADED','SUSPENDED','EXPIRED','REVOKED')
        OR (activated_by IS NOT NULL AND activated_at IS NOT NULL)
    ),
    CONSTRAINT ck_com_product_access_assignment_revocation_state CHECK (
        lifecycle_state <> 'REVOKED' OR (revoked_by IS NOT NULL AND revoked_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_com_product_access_assignment_exact
    ON com_product_access_package_assignments (
        tenant_id, package_id, principal_type, principal_public_id,
        scope_fingerprint, valid_from, COALESCE(valid_to, 'infinity'::timestamptz)
    )
    WHERE lifecycle_state NOT IN ('REVOKED','REJECTED','EXPIRED');

CREATE INDEX idx_com_product_access_assignment_effective
    ON com_product_access_package_assignments (tenant_id, principal_type, principal_public_id, lifecycle_state, valid_from, valid_to);
CREATE INDEX idx_com_product_access_assignment_review
    ON com_product_access_package_assignments (tenant_id, review_due_at, lifecycle_state)
    WHERE lifecycle_state IN ('ACTIVE','DEGRADED','SUSPENDED');

CREATE TABLE com_product_access_package_policy_refs (
    policy_ref_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    assignment_id BIGINT NOT NULL,
    policy_owner VARCHAR(80) NOT NULL,
    policy_public_id UUID NOT NULL,
    policy_revision BIGINT NOT NULL CHECK (policy_revision >= 0),
    policy_digest CHAR(64) NOT NULL CHECK (policy_digest ~ '^[0-9a-f]{64}$'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_com_product_access_policy_ref UNIQUE (tenant_id, assignment_id, policy_owner, policy_public_id),
    CONSTRAINT fk_com_product_access_policy_assignment FOREIGN KEY (tenant_id, assignment_id)
        REFERENCES com_product_access_package_assignments(tenant_id, assignment_id)
);

CREATE TABLE com_product_access_package_projection_status (
    projection_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    assignment_id BIGINT NOT NULL,
    projection_owner VARCHAR(80) NOT NULL,
    projection_kind VARCHAR(32) NOT NULL CHECK (projection_kind IN ('APP_GRANT','ATOMIC_ROLES','SCOPE_POLICY','FIELD_POLICY','CACHE_REVISION')),
    expected_revision BIGINT NOT NULL CHECK (expected_revision >= 0),
    applied_revision BIGINT,
    state VARCHAR(24) NOT NULL CHECK (state IN ('PENDING','APPLIED','DRIFTED','FAILED','REVOKED')),
    receipt_public_id UUID,
    error_code VARCHAR(120),
    last_attempt_at TIMESTAMPTZ,
    applied_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_com_product_access_projection UNIQUE (tenant_id, assignment_id, projection_owner, projection_kind),
    CONSTRAINT fk_com_product_access_projection_assignment FOREIGN KEY (tenant_id, assignment_id)
        REFERENCES com_product_access_package_assignments(tenant_id, assignment_id),
    CONSTRAINT ck_com_product_access_projection_applied_evidence CHECK (
        state <> 'APPLIED'
        OR (applied_revision = expected_revision AND receipt_public_id IS NOT NULL AND applied_at IS NOT NULL)
    )
);

CREATE INDEX idx_com_product_access_projection_pending
    ON com_product_access_package_projection_status (state, last_attempt_at)
    WHERE state IN ('PENDING','DRIFTED','FAILED');

CREATE OR REPLACE FUNCTION sys_guard_product_access_package_lifecycle() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.lifecycle_state <> 'DRAFT' THEN
            RAISE EXCEPTION 'PRODUCT_ACCESS_PACKAGE_MUST_START_DRAFT' USING ERRCODE = '55000';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        IF OLD.lifecycle_state <> 'DRAFT' THEN
            RAISE EXCEPTION 'PRODUCT_ACCESS_PACKAGE_HISTORY_CANNOT_BE_DELETED' USING ERRCODE = '55000';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.lifecycle_state = 'RETIRED' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_PACKAGE_RETIREMENT_MONOTONIC' USING ERRCODE = '55000';
    END IF;
    IF OLD.lifecycle_state <> NEW.lifecycle_state AND NOT (
        (OLD.lifecycle_state = 'DRAFT' AND NEW.lifecycle_state = 'ACTIVE')
        OR (OLD.lifecycle_state = 'ACTIVE' AND NEW.lifecycle_state = 'RETIRED')
    ) THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_PACKAGE_INVALID_STATE_TRANSITION' USING ERRCODE = '55000';
    END IF;
    IF OLD.lifecycle_state = 'ACTIVE'
       AND (to_jsonb(NEW) - ARRAY['lifecycle_state','retired_by','retired_at','version'])
           IS DISTINCT FROM
           (to_jsonb(OLD) - ARRAY['lifecycle_state','retired_by','retired_at','version']) THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_PACKAGE_ACTIVE_DEFINITION_IMMUTABLE' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sys_guard_product_access_package_role_mutation() RETURNS trigger AS $$
DECLARE old_package_state VARCHAR(24);
DECLARE new_package_state VARCHAR(24);
BEGIN
    IF TG_OP = 'INSERT' THEN
        SELECT lifecycle_state INTO new_package_state
          FROM sys_product_access_package_catalog
         WHERE package_id = NEW.package_id;
        IF new_package_state IS NOT NULL AND new_package_state <> 'DRAFT' THEN
            RAISE EXCEPTION 'PRODUCT_ACCESS_PACKAGE_ROLE_DRAFT_ONLY' USING ERRCODE = '55000';
        END IF;
        RETURN NEW;
    END IF;
    SELECT lifecycle_state INTO old_package_state
      FROM sys_product_access_package_catalog
     WHERE package_id = OLD.package_id;
    IF TG_OP = 'DELETE' THEN
        IF old_package_state IS DISTINCT FROM 'DRAFT' THEN
            RAISE EXCEPTION 'PRODUCT_ACCESS_PACKAGE_ROLE_DRAFT_ONLY' USING ERRCODE = '55000';
        END IF;
        RETURN OLD;
    END IF;
    SELECT lifecycle_state INTO new_package_state
      FROM sys_product_access_package_catalog
     WHERE package_id = NEW.package_id;
    IF old_package_state IS DISTINCT FROM 'DRAFT'
       OR new_package_state IS DISTINCT FROM 'DRAFT' THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_PACKAGE_ROLE_DRAFT_ONLY' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sys_guard_product_access_package_conflict_lifecycle() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.lifecycle_state <> 'DRAFT' THEN
            RAISE EXCEPTION 'PRODUCT_ACCESS_CONFLICT_MUST_START_DRAFT' USING ERRCODE = '55000';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        IF OLD.lifecycle_state <> 'DRAFT' THEN
            RAISE EXCEPTION 'PRODUCT_ACCESS_CONFLICT_HISTORY_CANNOT_BE_DELETED' USING ERRCODE = '55000';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.lifecycle_state = 'RETIRED' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_CONFLICT_RETIREMENT_MONOTONIC' USING ERRCODE = '55000';
    END IF;
    IF OLD.lifecycle_state <> NEW.lifecycle_state AND NOT (
        (OLD.lifecycle_state = 'DRAFT' AND NEW.lifecycle_state = 'ACTIVE')
        OR (OLD.lifecycle_state = 'ACTIVE' AND NEW.lifecycle_state = 'RETIRED')
    ) THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_CONFLICT_INVALID_STATE_TRANSITION' USING ERRCODE = '55000';
    END IF;
    IF OLD.lifecycle_state = 'ACTIVE'
       AND (to_jsonb(NEW) - ARRAY['lifecycle_state','retired_by','retired_at','version'])
           IS DISTINCT FROM
           (to_jsonb(OLD) - ARRAY['lifecycle_state','retired_by','retired_at','version']) THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_CONFLICT_ACTIVE_DEFINITION_IMMUTABLE' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION com_guard_product_access_assignment_lifecycle() RETURNS trigger AS $$
DECLARE package_state VARCHAR(24);
DECLARE projection_count INTEGER;
DECLARE applied_projection_count INTEGER;
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.lifecycle_state <> 'DRAFT' THEN
            RAISE EXCEPTION 'PRODUCT_ACCESS_ASSIGNMENT_MUST_START_DRAFT' USING ERRCODE = '55000';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_ASSIGNMENT_HISTORY_CANNOT_BE_DELETED' USING ERRCODE = '55000';
    END IF;
    IF OLD.lifecycle_state IN ('REVOKED','EXPIRED','REJECTED') AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_ASSIGNMENT_TERMINAL_STATE_MONOTONIC' USING ERRCODE = '55000';
    END IF;
    IF ROW(NEW.tenant_id, NEW.public_id, NEW.package_id, NEW.package_public_id,
           NEW.package_catalog_version, NEW.principal_type, NEW.principal_public_id,
           NEW.scope_fingerprint, NEW.valid_from, NEW.source_kind, NEW.source_reference,
           NEW.authored_by, NEW.created_at)
       IS DISTINCT FROM
       ROW(OLD.tenant_id, OLD.public_id, OLD.package_id, OLD.package_public_id,
           OLD.package_catalog_version, OLD.principal_type, OLD.principal_public_id,
           OLD.scope_fingerprint, OLD.valid_from, OLD.source_kind, OLD.source_reference,
           OLD.authored_by, OLD.created_at) THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_ASSIGNMENT_IDENTITY_IMMUTABLE' USING ERRCODE = '55000';
    END IF;
    IF NEW.valid_to IS DISTINCT FROM OLD.valid_to
       AND NOT (OLD.valid_to IS NULL AND NEW.valid_to IS NOT NULL AND NEW.valid_to > OLD.valid_from) THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_ASSIGNMENT_PERIOD_REWRITE' USING ERRCODE = '55000';
    END IF;
    IF (OLD.approved_by IS NOT NULL AND ROW(NEW.approved_by, NEW.approved_at)
                                      IS DISTINCT FROM ROW(OLD.approved_by, OLD.approved_at))
       OR (OLD.activated_by IS NOT NULL AND ROW(NEW.activated_by, NEW.activated_at)
                                         IS DISTINCT FROM ROW(OLD.activated_by, OLD.activated_at))
       OR (OLD.revoked_by IS NOT NULL AND ROW(NEW.revoked_by, NEW.revoked_at)
                                       IS DISTINCT FROM ROW(OLD.revoked_by, OLD.revoked_at)) THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_ASSIGNMENT_EVIDENCE_IMMUTABLE' USING ERRCODE = '55000';
    END IF;
    IF OLD.lifecycle_state <> NEW.lifecycle_state AND NOT (
        (OLD.lifecycle_state = 'DRAFT' AND NEW.lifecycle_state = 'PENDING_APPROVAL')
        OR (OLD.lifecycle_state = 'PENDING_APPROVAL' AND NEW.lifecycle_state IN ('DRAFT','APPROVED','REJECTED'))
        OR (OLD.lifecycle_state = 'APPROVED' AND NEW.lifecycle_state IN ('PENDING_PROJECTION','REVOKED','EXPIRED'))
        OR (OLD.lifecycle_state = 'PENDING_PROJECTION' AND NEW.lifecycle_state IN ('ACTIVE','DEGRADED','REVOKED','EXPIRED'))
        OR (OLD.lifecycle_state = 'ACTIVE' AND NEW.lifecycle_state IN ('DEGRADED','SUSPENDED','REVOKED','EXPIRED'))
        OR (OLD.lifecycle_state = 'DEGRADED' AND NEW.lifecycle_state IN ('PENDING_PROJECTION','SUSPENDED','REVOKED','EXPIRED'))
        OR (OLD.lifecycle_state = 'SUSPENDED' AND NEW.lifecycle_state IN ('PENDING_PROJECTION','REVOKED','EXPIRED'))
    ) THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_ASSIGNMENT_INVALID_STATE_TRANSITION' USING ERRCODE = '55000';
    END IF;
    IF NEW.lifecycle_state IN ('PENDING_PROJECTION','ACTIVE') THEN
        SELECT lifecycle_state INTO package_state
          FROM sys_product_access_package_catalog
         WHERE package_id = NEW.package_id;
        IF package_state IS DISTINCT FROM 'ACTIVE' THEN
            RAISE EXCEPTION 'PRODUCT_ACCESS_PACKAGE_NOT_ACTIVE' USING ERRCODE = '55000';
        END IF;
    END IF;
    IF NEW.lifecycle_state = 'ACTIVE' AND OLD.lifecycle_state <> 'ACTIVE' THEN
        SELECT count(*), count(DISTINCT projection_kind) FILTER (
                   WHERE state = 'APPLIED'
                     AND applied_revision = expected_revision
                     AND receipt_public_id IS NOT NULL
                     AND applied_at IS NOT NULL
               )
          INTO projection_count, applied_projection_count
          FROM com_product_access_package_projection_status
         WHERE tenant_id = NEW.tenant_id AND assignment_id = NEW.assignment_id;
        IF projection_count <> 5 OR applied_projection_count <> 5 THEN
            RAISE EXCEPTION 'PRODUCT_ACCESS_PROJECTION_CLOSURE_INCOMPLETE' USING ERRCODE = '55000';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION com_guard_product_access_projection_lifecycle() RETURNS trigger AS $$
DECLARE assignment_state VARCHAR(32);
BEGIN
    IF TG_OP = 'INSERT' THEN
        SELECT lifecycle_state INTO assignment_state
          FROM com_product_access_package_assignments
         WHERE tenant_id = NEW.tenant_id AND assignment_id = NEW.assignment_id;
        IF assignment_state = 'ACTIVE' THEN
            RAISE EXCEPTION 'ACTIVE_PRODUCT_ACCESS_PROJECTION_SET_IMMUTABLE' USING ERRCODE = '55000';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        SELECT lifecycle_state INTO assignment_state
          FROM com_product_access_package_assignments
         WHERE tenant_id = OLD.tenant_id AND assignment_id = OLD.assignment_id;
        IF assignment_state = 'ACTIVE' THEN
            RAISE EXCEPTION 'ACTIVE_PRODUCT_ACCESS_PROJECTION_CANNOT_BE_DELETED' USING ERRCODE = '55000';
        END IF;
        RETURN OLD;
    END IF;
    IF ROW(NEW.tenant_id, NEW.assignment_id, NEW.projection_owner, NEW.projection_kind)
       IS DISTINCT FROM
       ROW(OLD.tenant_id, OLD.assignment_id, OLD.projection_owner, OLD.projection_kind) THEN
        RAISE EXCEPTION 'PRODUCT_ACCESS_PROJECTION_IDENTITY_IMMUTABLE' USING ERRCODE = '55000';
    END IF;
    SELECT lifecycle_state INTO assignment_state
      FROM com_product_access_package_assignments
     WHERE tenant_id = OLD.tenant_id AND assignment_id = OLD.assignment_id;
    IF assignment_state = 'ACTIVE' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'ACTIVE_PRODUCT_ACCESS_PROJECTION_MUST_REMAIN_APPLIED' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_sys_product_access_package_lifecycle
    BEFORE INSERT OR UPDATE OR DELETE ON sys_product_access_package_catalog
    FOR EACH ROW EXECUTE FUNCTION sys_guard_product_access_package_lifecycle();
CREATE TRIGGER tr_sys_product_access_package_role_mutation
    BEFORE INSERT OR UPDATE OR DELETE ON sys_product_access_package_roles
    FOR EACH ROW EXECUTE FUNCTION sys_guard_product_access_package_role_mutation();
CREATE TRIGGER tr_sys_product_access_package_conflict_lifecycle
    BEFORE INSERT OR UPDATE OR DELETE ON sys_product_access_package_conflicts
    FOR EACH ROW EXECUTE FUNCTION sys_guard_product_access_package_conflict_lifecycle();
CREATE TRIGGER tr_com_product_access_assignment_lifecycle
    BEFORE INSERT OR UPDATE OR DELETE ON com_product_access_package_assignments
    FOR EACH ROW EXECUTE FUNCTION com_guard_product_access_assignment_lifecycle();
CREATE TRIGGER tr_com_product_access_projection_lifecycle
    BEFORE INSERT OR UPDATE OR DELETE ON com_product_access_package_projection_status
    FOR EACH ROW EXECUTE FUNCTION com_guard_product_access_projection_lifecycle();

CREATE TABLE com_product_access_command_receipts (
    command_receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    command_type VARCHAR(100) NOT NULL,
    originating_action VARCHAR(120) NOT NULL,
    subject_principal_public_id UUID NOT NULL,
    population_scope_digest CHAR(64) NOT NULL,
    field_policy_revision BIGINT NOT NULL,
    purpose_code VARCHAR(120) NOT NULL,
    authorization_revision BIGINT NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    request_digest CHAR(64) NOT NULL,
    aggregate_public_id UUID,
    aggregate_revision BIGINT,
    status VARCHAR(24) NOT NULL,
    result_ref VARCHAR(500),
    error_code VARCHAR(80),
    correlation_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_com_product_access_command_receipt_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_com_product_access_command_receipt_idem UNIQUE (tenant_id, subject_principal_public_id, originating_action, idempotency_key),
    CONSTRAINT ck_com_product_access_command_receipt_revisions CHECK (field_policy_revision > 0 AND authorization_revision > 0),
    CONSTRAINT ck_com_product_access_command_receipt_population_digest CHECK (population_scope_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_com_product_access_command_receipt_request_digest CHECK (request_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_com_product_access_command_receipt_status CHECK (status IN ('ACCEPTED','RUNNING','SUCCEEDED','REJECTED','FAILED','RESULT_UNKNOWN'))
);

CREATE OR REPLACE FUNCTION com_product_access_guard_command_receipt_seal()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Auth HRIS command receipt cannot be deleted';
    END IF;
    IF ROW(NEW.tenant_id, NEW.command_type, NEW.originating_action,
           NEW.subject_principal_public_id, NEW.population_scope_digest,
           NEW.field_policy_revision, NEW.purpose_code,
           NEW.authorization_revision, NEW.idempotency_key,
           NEW.request_digest, NEW.correlation_id)
       IS DISTINCT FROM
       ROW(OLD.tenant_id, OLD.command_type, OLD.originating_action,
           OLD.subject_principal_public_id, OLD.population_scope_digest,
           OLD.field_policy_revision, OLD.purpose_code,
           OLD.authorization_revision, OLD.idempotency_key,
           OLD.request_digest, OLD.correlation_id) THEN
        RAISE EXCEPTION 'Auth HRIS command receipt authorization and idempotency seal is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_com_product_access_command_receipt_seal
    BEFORE UPDATE OR DELETE ON com_product_access_command_receipts
    FOR EACH ROW EXECUTE FUNCTION com_product_access_guard_command_receipt_seal();

-- Service-local outbox, inbox and audit tables reuse the dwp-core Auth migration
-- baseline. The HRIS command receipt is owner-local because its originating
-- authorization and caller-bound idempotency context must be immutable.
-- Runtime roles are NOINHERIT, NOSUPERUSER and NOBYPASSRLS. The transaction
-- interceptor must SET LOCAL dwp.tenant_id after verified tenant resolution.
DO $$
DECLARE target_table TEXT;
BEGIN
  FOREACH target_table IN ARRAY ARRAY[
    'com_product_access_package_assignments',
    'com_product_access_package_policy_refs',
    'com_product_access_package_projection_status',
    'com_product_access_command_receipts'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', target_table);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', target_table);
    EXECUTE format(
      'CREATE POLICY %I ON %I USING (tenant_id = NULLIF(current_setting(''dwp.tenant_id'', true), '''')::BIGINT) WITH CHECK (tenant_id = NULLIF(current_setting(''dwp.tenant_id'', true), '''')::BIGINT)',
      target_table || '_tenant_policy', target_table
    );
  END LOOP;
END $$;

COMMIT;
