-- SYS G2 dwp-platform-server service-local physical migration blueprint.
-- AUTHORITATIVE SERVICE BOUNDARY: execute only in the dwp-platform-server database.
-- The catalog file g2-physical-schema.sql is retained for review parity and is not an executable migration.
-- Requires PostgreSQL pgcrypto/gen_random_uuid() from the governed Platform database baseline.
-- Integration Control assigns the final Flyway version; this file contains no Auth-owned table or FK.

BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE sys_hris_config_sets (
    config_set_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    config_domain VARCHAR(40) NOT NULL,
    config_key VARCHAR(160) NOT NULL,
    legal_entity_public_id UUID,
    legal_entity_scope_key TEXT GENERATED ALWAYS AS (
        COALESCE(legal_entity_public_id::text, 'GLOBAL')
    ) STORED,
    lifecycle_state VARCHAR(16) NOT NULL CHECK (lifecycle_state IN ('ACTIVE','RETIRED')),
    current_published_version INTEGER,
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_hris_config_set_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_hris_config_set_tenant_id UNIQUE (tenant_id, config_set_id),
    CONSTRAINT uq_sys_hris_config_set_key UNIQUE (
        tenant_id, config_domain, config_key, legal_entity_scope_key
    )
);

CREATE TABLE sys_hris_config_versions (
    config_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    config_set_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL CHECK (version_number > 0),
    lifecycle_state VARCHAR(32) NOT NULL CHECK (lifecycle_state IN (
        'DRAFT','VALIDATED','SIMULATED','PENDING_APPROVAL','APPROVED','SCHEDULED',
        'PUBLISHED','REJECTED','RETIRED','FAILED_ACTIVATION')),
    schema_key VARCHAR(200) NOT NULL,
    schema_version INTEGER NOT NULL CHECK (schema_version > 0),
    payload JSONB NOT NULL,
    payload_digest CHAR(64) NOT NULL CHECK (payload_digest ~ '^[0-9a-f]{64}$'),
    effective_from TIMESTAMPTZ,
    effective_to TIMESTAMPTZ,
    authored_by UUID NOT NULL,
    approved_by UUID,
    approval_public_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_hris_config_version_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_hris_config_version_number UNIQUE (tenant_id, config_set_id, version_number),
    CONSTRAINT uq_sys_hris_config_version_tenant_id UNIQUE (tenant_id, config_version_id),
    CONSTRAINT fk_sys_hris_config_version_set FOREIGN KEY (tenant_id, config_set_id)
        REFERENCES sys_hris_config_sets(tenant_id, config_set_id),
    CONSTRAINT ck_sys_hris_config_version_period CHECK (effective_to IS NULL OR effective_from < effective_to),
    CONSTRAINT ck_sys_hris_config_version_four_eyes CHECK (approved_by IS NULL OR approved_by <> authored_by),
    CONSTRAINT ck_sys_hris_config_version_approval_evidence CHECK (
        lifecycle_state NOT IN ('APPROVED','SCHEDULED','PUBLISHED','RETIRED')
        OR (approved_by IS NOT NULL AND approval_public_id IS NOT NULL)
    ),
    CONSTRAINT ck_sys_hris_config_version_publication_lineage CHECK (
        (lifecycle_state IN ('PUBLISHED','RETIRED') AND published_at IS NOT NULL AND effective_from IS NOT NULL)
        OR (lifecycle_state NOT IN ('PUBLISHED','RETIRED') AND published_at IS NULL)
    ),
    CONSTRAINT ex_sys_hris_config_version_ever_published_period EXCLUDE USING gist (
        tenant_id WITH =,
        config_set_id WITH =,
        tstzrange(effective_from, COALESCE(effective_to, 'infinity'::timestamptz), '[)') WITH &&
    ) WHERE (published_at IS NOT NULL)
);

CREATE OR REPLACE FUNCTION sys_guard_config_publication_lineage() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.published_at IS NOT NULL THEN
            RAISE EXCEPTION 'SYS_CONFIG_PUBLISHED_VERSION_CANNOT_BE_DELETED' USING ERRCODE = '55000';
        END IF;
        RETURN OLD;
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.published_at IS NOT NULL THEN
        IF NEW.published_at IS DISTINCT FROM OLD.published_at
           OR NEW.config_set_id IS DISTINCT FROM OLD.config_set_id
           OR NEW.effective_from IS DISTINCT FROM OLD.effective_from
           OR NEW.schema_key IS DISTINCT FROM OLD.schema_key
           OR NEW.schema_version IS DISTINCT FROM OLD.schema_version
           OR NEW.payload IS DISTINCT FROM OLD.payload
           OR NEW.payload_digest IS DISTINCT FROM OLD.payload_digest THEN
            RAISE EXCEPTION 'SYS_CONFIG_PUBLISHED_LINEAGE_IMMUTABLE' USING ERRCODE = '55000';
        END IF;
        IF NEW.effective_to IS DISTINCT FROM OLD.effective_to
           AND NOT (
               OLD.effective_to IS NULL
               AND NEW.effective_to IS NOT NULL
               AND NEW.effective_to > OLD.effective_from
           ) THEN
            RAISE EXCEPTION 'SYS_CONFIG_PUBLISHED_PERIOD_REWRITE_FORBIDDEN' USING ERRCODE = '55000';
        END IF;
        IF OLD.lifecycle_state = 'RETIRED' AND NEW.lifecycle_state <> 'RETIRED' THEN
            RAISE EXCEPTION 'SYS_CONFIG_RETIREMENT_MONOTONIC' USING ERRCODE = '55000';
        END IF;
        IF NEW.lifecycle_state NOT IN ('PUBLISHED','RETIRED') THEN
            RAISE EXCEPTION 'SYS_CONFIG_PUBLISHED_STATE_REWIND' USING ERRCODE = '55000';
        END IF;
    ELSIF NEW.lifecycle_state IN ('PUBLISHED','RETIRED') THEN
        NEW.published_at := COALESCE(NEW.published_at, CURRENT_TIMESTAMP);
    ELSIF NEW.published_at IS NOT NULL THEN
        RAISE EXCEPTION 'SYS_CONFIG_PUBLICATION_MARKER_WITHOUT_PUBLISHED_STATE' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sys_hris_config_publication_lineage
    BEFORE INSERT OR UPDATE OR DELETE ON sys_hris_config_versions
    FOR EACH ROW EXECUTE FUNCTION sys_guard_config_publication_lineage();

CREATE INDEX idx_sys_hris_config_version_state
    ON sys_hris_config_versions (tenant_id, lifecycle_state, effective_from);

CREATE TABLE sys_hris_config_evaluations (
    evaluation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    config_version_id BIGINT NOT NULL,
    evaluation_kind VARCHAR(16) NOT NULL CHECK (evaluation_kind IN ('VALIDATION','SIMULATION','IMPACT')),
    input_scope_digest CHAR(64) NOT NULL CHECK (input_scope_digest ~ '^[0-9a-f]{64}$'),
    outcome VARCHAR(16) NOT NULL CHECK (outcome IN ('PASS','WARN','FAIL')),
    result JSONB NOT NULL,
    result_digest CHAR(64) NOT NULL CHECK (result_digest ~ '^[0-9a-f]{64}$'),
    generated_by UUID NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    CONSTRAINT uq_sys_hris_config_evaluation_public UNIQUE (tenant_id, public_id),
    CONSTRAINT fk_sys_hris_config_evaluation_version FOREIGN KEY (tenant_id, config_version_id)
        REFERENCES sys_hris_config_versions(tenant_id, config_version_id)
);

CREATE TABLE sys_automation_definitions (
    automation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    automation_key VARCHAR(160) NOT NULL,
    owner_domain VARCHAR(40) NOT NULL,
    lifecycle_state VARCHAR(24) NOT NULL CHECK (lifecycle_state IN ('DRAFT','ACTIVE','SUSPENDED','RETIRED')),
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_automation_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_automation_tenant_id UNIQUE (tenant_id, automation_id),
    CONSTRAINT uq_sys_automation_key UNIQUE (tenant_id, automation_key)
);

CREATE TABLE sys_automation_versions (
    automation_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    automation_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL CHECK (version_number > 0),
    handler_key VARCHAR(200) NOT NULL,
    handler_contract_version INTEGER NOT NULL CHECK (handler_contract_version > 0),
    input_schema_ref VARCHAR(500) NOT NULL,
    receipt_schema_ref VARCHAR(500) NOT NULL,
    execution_policy JSONB NOT NULL,
    execution_policy_digest CHAR(64) NOT NULL CHECK (execution_policy_digest ~ '^[0-9a-f]{64}$'),
    definition_digest CHAR(64) NOT NULL CHECK (definition_digest ~ '^[0-9a-f]{64}$'),
    signature_key_id VARCHAR(200) NOT NULL,
    signature TEXT NOT NULL,
    lifecycle_state VARCHAR(24) NOT NULL CHECK (lifecycle_state IN ('DRAFT','VALIDATED','PENDING_APPROVAL','APPROVED','ACTIVE','SUSPENDED','RETIRED')),
    authored_by UUID NOT NULL,
    approved_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_automation_version UNIQUE (tenant_id, automation_id, version_number),
    CONSTRAINT uq_sys_automation_version_tenant_id UNIQUE (tenant_id, automation_version_id),
    CONSTRAINT fk_sys_automation_version_definition FOREIGN KEY (tenant_id, automation_id)
        REFERENCES sys_automation_definitions(tenant_id, automation_id),
    CONSTRAINT ck_sys_automation_version_four_eyes CHECK (approved_by IS NULL OR approved_by <> authored_by),
    CONSTRAINT ck_sys_automation_version_approval_state CHECK (
        lifecycle_state NOT IN ('APPROVED','ACTIVE','SUSPENDED','RETIRED') OR approved_by IS NOT NULL
    )
);

CREATE TABLE sys_automation_schedules (
    schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    automation_version_id BIGINT NOT NULL,
    schedule_expression VARCHAR(200) NOT NULL,
    timezone VARCHAR(80) NOT NULL,
    input_template_ref VARCHAR(500) NOT NULL,
    input_template_digest CHAR(64) NOT NULL CHECK (input_template_digest ~ '^[0-9a-f]{64}$'),
    concurrency_key_template VARCHAR(300) NOT NULL,
    lifecycle_state VARCHAR(24) NOT NULL DEFAULT 'DRAFT' CHECK (lifecycle_state IN ('DRAFT','PENDING_APPROVAL','APPROVED','ACTIVE','SUSPENDED','RETIRED')),
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    next_fire_at TIMESTAMPTZ,
    authored_by UUID NOT NULL,
    approved_by UUID,
    approval_receipt_public_id UUID,
    activated_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_automation_schedule_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_automation_schedule_tenant_id UNIQUE (tenant_id, schedule_id),
    CONSTRAINT fk_sys_automation_schedule_version FOREIGN KEY (tenant_id, automation_version_id)
        REFERENCES sys_automation_versions(tenant_id, automation_version_id),
    CONSTRAINT ck_sys_automation_schedule_four_eyes CHECK (approved_by IS NULL OR approved_by <> authored_by),
    CONSTRAINT ck_sys_automation_schedule_activation CHECK (
        (lifecycle_state IN ('DRAFT','PENDING_APPROVAL') AND enabled = FALSE)
        OR (lifecycle_state = 'APPROVED' AND approved_by IS NOT NULL AND enabled = FALSE)
        OR (lifecycle_state = 'ACTIVE' AND approved_by IS NOT NULL AND activated_by IS NOT NULL AND enabled = TRUE)
        OR (lifecycle_state IN ('SUSPENDED','RETIRED') AND approved_by IS NOT NULL AND enabled = FALSE)
    )
);

CREATE TABLE sys_automation_runs (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    automation_version_id BIGINT NOT NULL,
    schedule_public_id UUID,
    idempotency_key VARCHAR(200) NOT NULL,
    request_digest CHAR(64) NOT NULL CHECK (request_digest ~ '^[0-9a-f]{64}$'),
    concurrency_key VARCHAR(300) NOT NULL,
    retry_mode VARCHAR(24) NOT NULL DEFAULT 'ALL_ITEMS' CHECK (retry_mode IN ('ALL_ITEMS','FAILED_ITEMS_ONLY')),
    selected_item_count BIGINT NOT NULL DEFAULT 0 CHECK (selected_item_count >= 0),
    selected_item_digest CHAR(64) NOT NULL CHECK (selected_item_digest ~ '^[0-9a-f]{64}$'),
    state VARCHAR(24) NOT NULL CHECK (state IN ('QUEUED','LEASED','RUNNING','SUCCEEDED','PARTIAL','FAILED','CANCELLED','DEAD_LETTER')),
    item_total BIGINT NOT NULL DEFAULT 0,
    item_succeeded BIGINT NOT NULL DEFAULT 0,
    item_failed BIGINT NOT NULL DEFAULT 0,
    output_digest CHAR(64),
    cancel_requested_by UUID,
    cancel_requested_at TIMESTAMPTZ,
    cancel_reason_code VARCHAR(120),
    dead_letter_reason_code VARCHAR(120),
    requested_by UUID NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_automation_run_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_automation_run_tenant_id UNIQUE (tenant_id, run_id),
    CONSTRAINT fk_sys_automation_run_version FOREIGN KEY (tenant_id, automation_version_id)
        REFERENCES sys_automation_versions(tenant_id, automation_version_id),
    CONSTRAINT uq_sys_automation_run_idempotency UNIQUE (tenant_id, automation_version_id, idempotency_key),
    CONSTRAINT ck_sys_automation_run_counts CHECK (item_total >= 0 AND item_succeeded >= 0 AND item_failed >= 0 AND item_succeeded + item_failed <= item_total),
    CONSTRAINT ck_sys_automation_run_retry_selection CHECK (
        (retry_mode = 'ALL_ITEMS' AND selected_item_count = item_total)
        OR (retry_mode = 'FAILED_ITEMS_ONLY' AND selected_item_count > 0 AND selected_item_count <= item_failed)
    ),
    CONSTRAINT ck_sys_automation_run_cancel_context CHECK (
        (cancel_requested_at IS NULL AND cancel_requested_by IS NULL AND cancel_reason_code IS NULL)
        OR (cancel_requested_at IS NOT NULL AND cancel_requested_by IS NOT NULL AND cancel_reason_code IS NOT NULL)
    )
);

CREATE TABLE sys_automation_run_attempts (
    attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    attempt_number INTEGER NOT NULL CHECK (attempt_number > 0),
    selection_mode VARCHAR(24) NOT NULL CHECK (selection_mode IN ('ALL_ITEMS','FAILED_ITEMS_ONLY')),
    selected_item_count BIGINT NOT NULL CHECK (selected_item_count >= 0),
    selected_item_digest CHAR(64) NOT NULL CHECK (selected_item_digest ~ '^[0-9a-f]{64}$'),
    worker_id VARCHAR(200),
    lease_token UUID,
    leased_until TIMESTAMPTZ,
    heartbeat_at TIMESTAMPTZ,
    state VARCHAR(24) NOT NULL CHECK (state IN ('QUEUED','LEASED','RUNNING','SUCCEEDED','PARTIAL','FAILED','CANCELLED','DEAD_LETTER')),
    error_code VARCHAR(120),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_sys_automation_run_attempt_tenant_id UNIQUE (tenant_id, attempt_id),
    CONSTRAINT uq_sys_automation_run_attempt_parent UNIQUE (tenant_id, run_id, attempt_id),
    CONSTRAINT uq_sys_automation_run_attempt UNIQUE (tenant_id, run_id, attempt_number),
    CONSTRAINT fk_sys_automation_run_attempt_run FOREIGN KEY (tenant_id, run_id)
        REFERENCES sys_automation_runs(tenant_id, run_id)
);

CREATE TABLE sys_automation_run_items (
    run_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    item_key VARCHAR(300) NOT NULL,
    input_digest CHAR(64) NOT NULL CHECK (input_digest ~ '^[0-9a-f]{64}$'),
    effect_idempotency_key VARCHAR(300) NOT NULL,
    state VARCHAR(24) NOT NULL CHECK (state IN ('PENDING','RUNNING','SUCCEEDED','FAILED_RETRYABLE','FAILED_FINAL','CANCELLED')),
    effect_digest CHAR(64),
    failure_code VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_automation_run_item_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_automation_run_item_tenant_id UNIQUE (tenant_id, run_item_id),
    CONSTRAINT uq_sys_automation_run_item_parent UNIQUE (tenant_id, run_id, run_item_id),
    CONSTRAINT uq_sys_automation_run_item_key UNIQUE (tenant_id, run_id, item_key),
    CONSTRAINT uq_sys_automation_run_item_effect UNIQUE (tenant_id, effect_idempotency_key),
    CONSTRAINT fk_sys_automation_run_item_run FOREIGN KEY (tenant_id, run_id)
        REFERENCES sys_automation_runs(tenant_id, run_id),
    CONSTRAINT ck_sys_automation_run_item_terminal CHECK (
        state NOT IN ('SUCCEEDED','FAILED_FINAL') OR completed_at IS NOT NULL
    )
);

CREATE TABLE sys_automation_item_attempts (
    item_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    attempt_id BIGINT NOT NULL,
    run_item_id BIGINT NOT NULL,
    attempt_ordinal INTEGER NOT NULL CHECK (attempt_ordinal > 0),
    lease_fence_token UUID NOT NULL,
    state VARCHAR(24) NOT NULL CHECK (state IN ('LEASED','RUNNING','SUCCEEDED','FAILED_RETRYABLE','FAILED_FINAL','CANCELLED')),
    input_digest CHAR(64) NOT NULL CHECK (input_digest ~ '^[0-9a-f]{64}$'),
    output_digest CHAR(64),
    error_code VARCHAR(120),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_sys_automation_item_attempt_tenant_id UNIQUE (tenant_id, item_attempt_id),
    CONSTRAINT uq_sys_automation_item_attempt UNIQUE (tenant_id, attempt_id, run_item_id),
    CONSTRAINT fk_sys_automation_item_attempt_attempt FOREIGN KEY (tenant_id, run_id, attempt_id)
        REFERENCES sys_automation_run_attempts(tenant_id, run_id, attempt_id),
    CONSTRAINT fk_sys_automation_item_attempt_item FOREIGN KEY (tenant_id, run_id, run_item_id)
        REFERENCES sys_automation_run_items(tenant_id, run_id, run_item_id)
);

CREATE TABLE sys_automation_run_checkpoints (
    checkpoint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    attempt_id BIGINT NOT NULL,
    checkpoint_key VARCHAR(200) NOT NULL,
    checkpoint_ordinal BIGINT NOT NULL CHECK (checkpoint_ordinal > 0),
    lease_fence_token UUID NOT NULL,
    processed_item_count BIGINT NOT NULL CHECK (processed_item_count >= 0),
    processed_item_digest CHAR(64) NOT NULL CHECK (processed_item_digest ~ '^[0-9a-f]{64}$'),
    cursor_ref VARCHAR(500),
    cursor_digest CHAR(64),
    output_digest CHAR(64) NOT NULL CHECK (output_digest ~ '^[0-9a-f]{64}$'),
    committed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sys_automation_checkpoint_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_automation_checkpoint_tenant_id UNIQUE (tenant_id, checkpoint_id),
    CONSTRAINT uq_sys_automation_checkpoint_key UNIQUE (tenant_id, run_id, checkpoint_key),
    CONSTRAINT uq_sys_automation_checkpoint_ordinal UNIQUE (tenant_id, run_id, checkpoint_ordinal),
    CONSTRAINT fk_sys_automation_checkpoint_run FOREIGN KEY (tenant_id, run_id)
        REFERENCES sys_automation_runs(tenant_id, run_id),
    CONSTRAINT fk_sys_automation_checkpoint_attempt FOREIGN KEY (tenant_id, run_id, attempt_id)
        REFERENCES sys_automation_run_attempts(tenant_id, run_id, attempt_id),
    CONSTRAINT ck_sys_automation_checkpoint_cursor CHECK (
        (cursor_ref IS NULL AND cursor_digest IS NULL)
        OR (cursor_ref IS NOT NULL AND cursor_digest ~ '^[0-9a-f]{64}$')
    )
);

CREATE INDEX idx_sys_automation_run_queue ON sys_automation_runs (state, requested_at)
    WHERE state IN ('QUEUED','FAILED','PARTIAL');
CREATE INDEX idx_sys_automation_attempt_lease ON sys_automation_run_attempts (state, leased_until)
    WHERE state IN ('LEASED','RUNNING');
CREATE INDEX idx_sys_automation_item_retry ON sys_automation_run_items (tenant_id, run_id, state)
    WHERE state = 'FAILED_RETRYABLE';
CREATE INDEX idx_sys_automation_checkpoint_resume ON sys_automation_run_checkpoints (tenant_id, run_id, checkpoint_ordinal DESC);

CREATE TABLE sys_connector_definitions (
    connector_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    connector_key VARCHAR(160) NOT NULL,
    owner_domain VARCHAR(40) NOT NULL,
    provider_type VARCHAR(80) NOT NULL,
    endpoint_policy_ref VARCHAR(240) NOT NULL,
    secret_ref VARCHAR(500) NOT NULL,
    definition_digest CHAR(64) NOT NULL CHECK (definition_digest ~ '^[0-9a-f]{64}$'),
    lifecycle_state VARCHAR(24) NOT NULL CHECK (lifecycle_state IN ('DRAFT','VALIDATED','TESTED','PENDING_APPROVAL','APPROVED','ACTIVE','SUSPENDED','RETIRED')),
    created_by UUID NOT NULL,
    validated_by UUID,
    test_receipt_public_id UUID,
    approved_by UUID,
    approval_receipt_public_id UUID,
    activated_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_connector_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_connector_tenant_id UNIQUE (tenant_id, connector_id),
    CONSTRAINT uq_sys_connector_key UNIQUE (tenant_id, connector_key),
    CONSTRAINT ck_sys_connector_secret_reference CHECK (secret_ref ~ '^secret_[A-Za-z0-9_-]{16,128}$'),
    CONSTRAINT ck_sys_connector_four_eyes CHECK (approved_by IS NULL OR approved_by <> created_by),
    CONSTRAINT ck_sys_connector_activation_state CHECK (
        lifecycle_state NOT IN ('APPROVED','ACTIVE','SUSPENDED','RETIRED')
        OR (approved_by IS NOT NULL AND approval_receipt_public_id IS NOT NULL)
    ),
    CONSTRAINT ck_sys_connector_active_actor CHECK (
        lifecycle_state <> 'ACTIVE' OR activated_by IS NOT NULL
    )
);

CREATE TABLE sys_connector_mapping_versions (
    mapping_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    connector_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL CHECK (version_number > 0),
    source_schema_key VARCHAR(200) NOT NULL,
    source_schema_version INTEGER NOT NULL CHECK (source_schema_version > 0),
    target_command_key VARCHAR(200) NOT NULL,
    target_schema_version INTEGER NOT NULL CHECK (target_schema_version > 0),
    mapping_ref VARCHAR(500) NOT NULL,
    mapping_digest CHAR(64) NOT NULL CHECK (mapping_digest ~ '^[0-9a-f]{64}$'),
    compatibility_mode VARCHAR(16) NOT NULL CHECK (compatibility_mode IN ('BACKWARD','FORWARD','FULL','EXACT')),
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ,
    lifecycle_state VARCHAR(24) NOT NULL CHECK (lifecycle_state IN ('DRAFT','VALIDATED','PENDING_APPROVAL','APPROVED','ACTIVE','SUSPENDED','RETIRED')),
    authored_by UUID NOT NULL,
    approved_by UUID,
    approval_receipt_public_id UUID,
    activated_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_connector_mapping_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_connector_mapping_tenant_id UNIQUE (tenant_id, mapping_version_id),
    CONSTRAINT uq_sys_connector_mapping_parent UNIQUE (tenant_id, connector_id, mapping_version_id),
    CONSTRAINT fk_sys_connector_mapping_definition FOREIGN KEY (tenant_id, connector_id)
        REFERENCES sys_connector_definitions(tenant_id, connector_id),
    CONSTRAINT uq_sys_connector_mapping_version UNIQUE (tenant_id, connector_id, version_number),
    CONSTRAINT ck_sys_connector_mapping_period CHECK (effective_to IS NULL OR effective_from < effective_to),
    CONSTRAINT ck_sys_connector_mapping_four_eyes CHECK (approved_by IS NULL OR approved_by <> authored_by),
    CONSTRAINT ck_sys_connector_mapping_activation_state CHECK (
        lifecycle_state NOT IN ('APPROVED','ACTIVE','SUSPENDED','RETIRED')
        OR (approved_by IS NOT NULL AND approval_receipt_public_id IS NOT NULL)
    ),
    CONSTRAINT ck_sys_connector_mapping_active_actor CHECK (
        lifecycle_state <> 'ACTIVE' OR activated_by IS NOT NULL
    )
);

CREATE TABLE sys_connector_executions (
    execution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    connector_id BIGINT NOT NULL,
    mapping_version_id BIGINT NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_digest CHAR(64) NOT NULL CHECK (request_digest ~ '^[0-9a-f]{64}$'),
    retry_mode VARCHAR(24) NOT NULL DEFAULT 'ALL_ITEMS' CHECK (retry_mode IN ('ALL_ITEMS','FAILED_ITEMS_ONLY')),
    selected_item_count BIGINT NOT NULL DEFAULT 0 CHECK (selected_item_count >= 0),
    selected_item_digest CHAR(64) NOT NULL CHECK (selected_item_digest ~ '^[0-9a-f]{64}$'),
    state VARCHAR(24) NOT NULL CHECK (state IN ('ACCEPTED','TRANSFORMING','DISPATCHED','RESULT_UNKNOWN','ACKNOWLEDGED','RECONCILING','RECONCILED','PARTIAL','FAILED','DEAD_LETTER','CANCELLED')),
    provider_receipt_ref VARCHAR(500),
    source_count BIGINT NOT NULL DEFAULT 0,
    accepted_count BIGINT NOT NULL DEFAULT 0,
    rejected_count BIGINT NOT NULL DEFAULT 0,
    reconciliation_digest CHAR(64),
    cancel_requested_by UUID,
    cancel_requested_at TIMESTAMPTZ,
    cancel_reason_code VARCHAR(120),
    dead_letter_reason_code VARCHAR(120),
    requested_by UUID NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_connector_execution_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_connector_execution_tenant_id UNIQUE (tenant_id, execution_id),
    CONSTRAINT fk_sys_connector_execution_definition FOREIGN KEY (tenant_id, connector_id)
        REFERENCES sys_connector_definitions(tenant_id, connector_id),
    CONSTRAINT fk_sys_connector_execution_mapping FOREIGN KEY (tenant_id, connector_id, mapping_version_id)
        REFERENCES sys_connector_mapping_versions(tenant_id, connector_id, mapping_version_id),
    CONSTRAINT uq_sys_connector_execution_idempotency UNIQUE (tenant_id, connector_id, idempotency_key),
    CONSTRAINT ck_sys_connector_execution_counts CHECK (source_count >= 0 AND accepted_count >= 0 AND rejected_count >= 0 AND accepted_count + rejected_count <= source_count),
    CONSTRAINT ck_sys_connector_execution_retry_selection CHECK (
        (retry_mode = 'ALL_ITEMS' AND selected_item_count = source_count)
        OR (retry_mode = 'FAILED_ITEMS_ONLY' AND selected_item_count > 0 AND selected_item_count <= rejected_count)
    ),
    CONSTRAINT ck_sys_connector_execution_cancel_context CHECK (
        (cancel_requested_at IS NULL AND cancel_requested_by IS NULL AND cancel_reason_code IS NULL)
        OR (cancel_requested_at IS NOT NULL AND cancel_requested_by IS NOT NULL AND cancel_reason_code IS NOT NULL)
    )
);

CREATE TABLE sys_connector_execution_items (
    execution_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    execution_id BIGINT NOT NULL,
    source_item_key VARCHAR(300) NOT NULL,
    source_item_digest CHAR(64) NOT NULL CHECK (source_item_digest ~ '^[0-9a-f]{64}$'),
    transformed_item_digest CHAR(64),
    provider_item_key VARCHAR(300),
    state VARCHAR(24) NOT NULL CHECK (state IN ('PENDING','TRANSFORMED','DISPATCHED','RESULT_UNKNOWN','ACCEPTED','REJECTED_RETRYABLE','REJECTED_FINAL','RECONCILED','CANCELLED')),
    provider_receipt_ref VARCHAR(500),
    failure_code VARCHAR(120),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_connector_execution_item_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_connector_execution_item_tenant_id UNIQUE (tenant_id, execution_item_id),
    CONSTRAINT uq_sys_connector_execution_item_parent UNIQUE (tenant_id, execution_id, execution_item_id),
    CONSTRAINT uq_sys_connector_execution_item_source UNIQUE (tenant_id, execution_id, source_item_key),
    CONSTRAINT fk_sys_connector_execution_item_execution FOREIGN KEY (tenant_id, execution_id)
        REFERENCES sys_connector_executions(tenant_id, execution_id)
);

CREATE TABLE sys_connector_execution_attempts (
    execution_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    execution_id BIGINT NOT NULL,
    execution_item_id BIGINT NOT NULL,
    attempt_number INTEGER NOT NULL CHECK (attempt_number > 0),
    provider_idempotency_key VARCHAR(300) NOT NULL,
    request_digest CHAR(64) NOT NULL CHECK (request_digest ~ '^[0-9a-f]{64}$'),
    state VARCHAR(24) NOT NULL CHECK (state IN ('READY','DISPATCHED','RESULT_UNKNOWN','ACKNOWLEDGED','RECONCILED','FAILED','CANCELLED')),
    provider_receipt_ref VARCHAR(500),
    response_digest CHAR(64),
    reconciliation_digest CHAR(64),
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_sys_connector_execution_attempt_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_connector_execution_attempt_key UNIQUE (tenant_id, execution_item_id, attempt_number),
    CONSTRAINT uq_sys_connector_provider_idempotency UNIQUE (tenant_id, provider_idempotency_key),
    CONSTRAINT fk_sys_connector_execution_attempt_execution FOREIGN KEY (tenant_id, execution_id)
        REFERENCES sys_connector_executions(tenant_id, execution_id),
    CONSTRAINT fk_sys_connector_execution_attempt_item FOREIGN KEY (tenant_id, execution_id, execution_item_id)
        REFERENCES sys_connector_execution_items(tenant_id, execution_id, execution_item_id)
);

CREATE INDEX idx_sys_connector_execution_state
    ON sys_connector_executions (tenant_id, connector_id, state, requested_at DESC);
CREATE INDEX idx_sys_connector_execution_item_retry
    ON sys_connector_execution_items (tenant_id, execution_id, state)
    WHERE state = 'REJECTED_RETRYABLE';

CREATE TABLE sys_hris_home_contributions (
    contribution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    actor_public_id UUID NOT NULL,
    browser_audience VARCHAR(24) NOT NULL CHECK (browser_audience IN ('SELF','TEAM','OPERATIONS','EXECUTIVE')),
    owner_population_scope VARCHAR(32) NOT NULL CHECK (owner_population_scope IN ('SELF','TEAM','NAMED_POPULATION','TIME_GROUP','PAY_GROUP','LEGAL_ENTITY','AUTHORIZED_PACKAGE_SCOPE')),
    scope_revision BIGINT NOT NULL CHECK (scope_revision > 0),
    population_scope_digest CHAR(64) NOT NULL CHECK (population_scope_digest ~ '^[0-9a-f]{64}$'),
    field_policy_revision BIGINT NOT NULL CHECK (field_policy_revision > 0),
    authorization_revision BIGINT NOT NULL CHECK (authorization_revision > 0),
    purpose_code VARCHAR(80) NOT NULL CHECK (purpose_code = 'HRIS_HOME_VIEW'),
    widget_key VARCHAR(160) NOT NULL,
    widget_type VARCHAR(32) NOT NULL CHECK (widget_type IN ('PEOPLE_SUMMARY','TIME_LEAVE_SUMMARY','PAYROLL_SUMMARY','PERFORMANCE_SUMMARY','ACTION_ITEMS')),
    projection_schema_id VARCHAR(80) NOT NULL CHECK (projection_schema_id IN ('PeopleHomeData.v1','TimeLeaveHomeData.v1','PayrollHomeData.v1','PerformanceHomeData.v1','ActionItemsHomeData.v1')),
    schema_version INTEGER NOT NULL CHECK (schema_version > 0),
    source_service VARCHAR(80) NOT NULL,
    source_version BIGINT NOT NULL CHECK (source_version > 0),
    state VARCHAR(24) NOT NULL CHECK (state IN ('CURRENT','STALE','DEGRADED','UNAVAILABLE','NOT_ENTITLED','EMPTY')),
    typed_projection JSONB NOT NULL CHECK (jsonb_typeof(typed_projection) = 'object' AND typed_projection ? 'kind'),
    field_decisions JSONB NOT NULL CHECK (jsonb_typeof(field_decisions) = 'array'),
    payload_digest CHAR(64) NOT NULL CHECK (payload_digest ~ '^[0-9a-f]{64}$'),
    generated_at TIMESTAMPTZ NOT NULL,
    fresh_until TIMESTAMPTZ NOT NULL,
    stale_after TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sys_hris_home_contribution UNIQUE (tenant_id, actor_public_id, browser_audience, owner_population_scope, scope_revision, widget_key),
    CONSTRAINT ck_sys_hris_home_projection_pair CHECK (
        (widget_type = 'PEOPLE_SUMMARY' AND projection_schema_id = 'PeopleHomeData.v1') OR
        (widget_type = 'TIME_LEAVE_SUMMARY' AND projection_schema_id = 'TimeLeaveHomeData.v1') OR
        (widget_type = 'PAYROLL_SUMMARY' AND projection_schema_id = 'PayrollHomeData.v1') OR
        (widget_type = 'PERFORMANCE_SUMMARY' AND projection_schema_id = 'PerformanceHomeData.v1') OR
        (widget_type = 'ACTION_ITEMS' AND projection_schema_id = 'ActionItemsHomeData.v1')
    ),
    CONSTRAINT ck_sys_hris_home_no_sensitive_payload CHECK (NOT (typed_projection ?| ARRAY['bankAccountNumber','nationalId','taxIdentifier','documentBytes','rawPayload','sourcePayload'])),
    CONSTRAINT ck_sys_hris_home_freshness CHECK (generated_at <= fresh_until AND fresh_until <= stale_after)
);

CREATE INDEX idx_sys_hris_home_contribution_expiry
    ON sys_hris_home_contributions (stale_after);

-- Explorer preferences are server-owned and principal-private.  Route keys are
-- re-authorized on every read/write; retired or denied keys are purged in the
-- same transaction.  No label, source DTO, case body or receipt payload is kept.
CREATE TABLE sys_hris_explorer_preferences (
    explorer_preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    principal_public_id UUID NOT NULL,
    preference_revision BIGINT NOT NULL DEFAULT 1 CHECK (preference_revision > 0),
    route_catalog_revision BIGINT NOT NULL CHECK (route_catalog_revision > 0),
    entitlement_revision BIGINT NOT NULL CHECK (entitlement_revision > 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by UUID NOT NULL,
    CONSTRAINT uq_sys_hris_explorer_preference_id UNIQUE (tenant_id, explorer_preference_id),
    CONSTRAINT uq_sys_hris_explorer_preference_principal UNIQUE (tenant_id, principal_public_id)
);

CREATE TABLE sys_hris_explorer_favorites (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    explorer_preference_id BIGINT NOT NULL,
    route_key VARCHAR(96) NOT NULL CHECK (route_key ~ '^[a-z][a-z0-9.-]{2,95}$'),
    position SMALLINT NOT NULL CHECK (position BETWEEN 1 AND 20),
    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sys_hris_explorer_favorite_id UNIQUE (tenant_id, favorite_id),
    CONSTRAINT uq_sys_hris_explorer_favorite_route UNIQUE (tenant_id, explorer_preference_id, route_key),
    CONSTRAINT uq_sys_hris_explorer_favorite_position UNIQUE (tenant_id, explorer_preference_id, position),
    CONSTRAINT fk_sys_hris_explorer_favorite_preference FOREIGN KEY (tenant_id, explorer_preference_id)
        REFERENCES sys_hris_explorer_preferences(tenant_id, explorer_preference_id) ON DELETE CASCADE
);

CREATE TABLE sys_hris_explorer_recents (
    recent_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    principal_public_id UUID NOT NULL,
    route_key VARCHAR(96) NOT NULL CHECK (route_key ~ '^[a-z][a-z0-9.-]{2,95}$'),
    last_visited_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    route_catalog_revision BIGINT NOT NULL CHECK (route_catalog_revision > 0),
    entitlement_revision BIGINT NOT NULL CHECK (entitlement_revision > 0),
    CONSTRAINT uq_sys_hris_explorer_recent_id UNIQUE (tenant_id, recent_id),
    CONSTRAINT uq_sys_hris_explorer_recent_route UNIQUE (tenant_id, principal_public_id, route_key),
    CONSTRAINT ck_sys_hris_explorer_recent_ttl CHECK (expires_at = last_visited_at + INTERVAL '30 days')
);

CREATE INDEX idx_sys_hris_explorer_favorite_order
    ON sys_hris_explorer_favorites (tenant_id, explorer_preference_id, position);
CREATE INDEX idx_sys_hris_explorer_recent_lru
    ON sys_hris_explorer_recents (tenant_id, principal_public_id, last_visited_at DESC);
CREATE INDEX idx_sys_hris_explorer_recent_expiry
    ON sys_hris_explorer_recents (expires_at);

-- Platform-owned transfer control plane. The object store owns bytes; this
-- table stores only opaque references, integrity/security state and receipts.
CREATE TABLE sys_controlled_file_transfers (
    transfer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    transfer_kind VARCHAR(24) NOT NULL CHECK (transfer_kind IN ('INGEST','EXPORT','DELIVERY','EXCHANGE')),
    owner_module VARCHAR(40) NOT NULL,
    purpose_code VARCHAR(120) NOT NULL,
    recipient_policy_ref VARCHAR(255),
    egress_policy_revision BIGINT,
    classification VARCHAR(24) NOT NULL CHECK (classification IN ('PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED')),
    object_ref VARCHAR(1000) NOT NULL,
    object_version VARCHAR(128) NOT NULL,
    storage_etag VARCHAR(256) NOT NULL,
    object_digest CHAR(64) NOT NULL CHECK (object_digest ~ '^[0-9a-f]{64}$'),
    media_type VARCHAR(160) NOT NULL,
    byte_size BIGINT NOT NULL CHECK (byte_size > 0),
    metadata_authority VARCHAR(80) NOT NULL,
    metadata_snapshot_digest CHAR(64) NOT NULL CHECK (metadata_snapshot_digest ~ '^[0-9a-f]{64}$'),
    scanner_key VARCHAR(64) NOT NULL,
    scanner_version VARCHAR(64) NOT NULL,
    scanned_at TIMESTAMPTZ NOT NULL,
    scan_object_digest CHAR(64) NOT NULL CHECK (scan_object_digest ~ '^[0-9a-f]{64}$'),
    scan_byte_size BIGINT NOT NULL CHECK (scan_byte_size > 0),
    malware_state VARCHAR(24) NOT NULL CHECK (malware_state IN ('PENDING','CLEAN','INFECTED','SCAN_FAILED','NOT_REQUIRED')),
    state VARCHAR(24) NOT NULL CHECK (state IN ('REQUESTED','SCANNING','READY','IN_PROGRESS','COMPLETED','QUARANTINED','FAILED','EXPIRED','CANCELLED')),
    idempotency_key VARCHAR(200) NOT NULL,
    request_digest CHAR(64) NOT NULL CHECK (request_digest ~ '^[0-9a-f]{64}$'),
    receipt_ref VARCHAR(500),
    receipt_digest CHAR(64),
    failure_code VARCHAR(120),
    requested_by UUID NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    CONSTRAINT uq_sys_controlled_transfer_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_controlled_transfer_idempotency UNIQUE (tenant_id, owner_module, idempotency_key),
    CONSTRAINT ck_sys_controlled_transfer_period CHECK (requested_at < expires_at),
    CONSTRAINT ck_sys_controlled_transfer_receipt_digest CHECK (receipt_digest IS NULL OR receipt_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_sys_controlled_transfer_direction_policy CHECK (
        (transfer_kind = 'INGEST' AND recipient_policy_ref IS NULL AND egress_policy_revision IS NULL)
        OR
        (transfer_kind IN ('EXPORT','DELIVERY','EXCHANGE')
         AND recipient_policy_ref IS NOT NULL AND egress_policy_revision IS NOT NULL
         AND egress_policy_revision > 0)
    ),
    CONSTRAINT ck_sys_controlled_transfer_metadata_binding CHECK (
        object_digest = scan_object_digest AND byte_size = scan_byte_size
    ),
    CONSTRAINT ck_sys_controlled_transfer_clean_ready CHECK (
        state NOT IN ('READY','IN_PROGRESS','COMPLETED') OR malware_state IN ('CLEAN','NOT_REQUIRED')
    ),
    CONSTRAINT ck_sys_controlled_transfer_object_ref CHECK (
        object_ref !~* '(password|secret|token)\\s*[:=]' AND object_ref !~ '(^|/)\\.\\.(/|$)'
    )
);

CREATE INDEX idx_sys_controlled_transfer_state
    ON sys_controlled_file_transfers (tenant_id, owner_module, transfer_kind, state, requested_at DESC);
CREATE INDEX idx_sys_controlled_transfer_expiry
    ON sys_controlled_file_transfers (expires_at)
    WHERE state IN ('REQUESTED','SCANNING','READY','IN_PROGRESS');

-- Read-only cross-domain projection for the operations center. Recovery
-- commands remain in the owning module; owner_route_key is an allowlisted
-- route-contract key, never a caller-supplied URL or executable command.
CREATE TABLE sys_operational_exception_projections (
    exception_projection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    owner_service VARCHAR(80) NOT NULL,
    owner_module VARCHAR(40) NOT NULL,
    source_exception_ref VARCHAR(240) NOT NULL,
    source_revision BIGINT NOT NULL CHECK (source_revision >= 0),
    exception_type VARCHAR(120) NOT NULL,
    severity VARCHAR(16) NOT NULL CHECK (severity IN ('INFO','WARNING','ERROR','CRITICAL')),
    state VARCHAR(24) NOT NULL CHECK (state IN ('OPEN','ACKNOWLEDGED','RECOVERING','RESOLVED','SUPPRESSED')),
    error_code VARCHAR(120),
    summary_key VARCHAR(240) NOT NULL,
    owner_route_key VARCHAR(240) NOT NULL,
    evidence_ref VARCHAR(500),
    correlation_id UUID NOT NULL,
    source_event_id UUID NOT NULL,
    source_event_digest CHAR(64) NOT NULL CHECK (source_event_digest ~ '^[0-9a-f]{64}$'),
    first_detected_at TIMESTAMPTZ NOT NULL,
    last_observed_at TIMESTAMPTZ NOT NULL,
    resolved_at TIMESTAMPTZ,
    occurrence_count BIGINT NOT NULL DEFAULT 1 CHECK (occurrence_count > 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    CONSTRAINT uq_sys_operational_exception_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_operational_exception_source UNIQUE (tenant_id, owner_service, source_exception_ref),
    CONSTRAINT uq_sys_operational_exception_event UNIQUE (tenant_id, source_event_id),
    CONSTRAINT ck_sys_operational_exception_time CHECK (first_detected_at <= last_observed_at),
    CONSTRAINT ck_sys_operational_exception_resolved CHECK (
        (state = 'RESOLVED' AND resolved_at IS NOT NULL) OR (state <> 'RESOLVED' AND resolved_at IS NULL)
    ),
    CONSTRAINT ck_sys_operational_exception_route_key CHECK (owner_route_key ~ '^route\\.[a-z0-9._-]+$')
);

CREATE INDEX idx_sys_operational_exception_queue
    ON sys_operational_exception_projections (tenant_id, state, severity, last_observed_at DESC);
CREATE INDEX idx_sys_operational_exception_owner
    ON sys_operational_exception_projections (tenant_id, owner_module, owner_service, state);

CREATE TABLE sys_extension_pack_versions (
    extension_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    extension_key VARCHAR(160) NOT NULL,
    version VARCHAR(80) NOT NULL,
    pack_kind VARCHAR(24) NOT NULL CHECK (pack_kind IN ('COUNTRY','CONNECTOR','TENANT_EXTENSION')),
    manifest JSONB NOT NULL,
    manifest_digest CHAR(64) NOT NULL CHECK (manifest_digest ~ '^[0-9a-f]{64}$'),
    signature_key_id VARCHAR(200) NOT NULL,
    signature TEXT NOT NULL,
    signature_digest CHAR(64) NOT NULL CHECK (signature_digest ~ '^[0-9a-f]{64}$'),
    compatibility_range VARCHAR(200) NOT NULL,
    compatibility_digest CHAR(64) NOT NULL CHECK (compatibility_digest ~ '^[0-9a-f]{64}$'),
    hook_allowlist_digest CHAR(64) NOT NULL CHECK (hook_allowlist_digest ~ '^[0-9a-f]{64}$'),
    schema_digest CHAR(64) NOT NULL CHECK (schema_digest ~ '^[0-9a-f]{64}$'),
    license_digest CHAR(64) NOT NULL CHECK (license_digest ~ '^[0-9a-f]{64}$'),
    permission_manifest_digest CHAR(64) NOT NULL CHECK (permission_manifest_digest ~ '^[0-9a-f]{64}$'),
    lifecycle_state VARCHAR(24) NOT NULL CHECK (lifecycle_state IN ('DISCOVERED','VERIFIED','APPROVED','REVOKED')),
    discovered_by UUID NOT NULL,
    verified_by UUID,
    verified_at TIMESTAMPTZ,
    verification_evidence_digest CHAR(64),
    approved_by UUID,
    approved_at TIMESTAMPTZ,
    approval_receipt_public_id UUID,
    revoked_by UUID,
    revoked_at TIMESTAMPTZ,
    revocation_reason_code VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sys_extension_pack_public UNIQUE (public_id),
    CONSTRAINT uq_sys_extension_pack_version UNIQUE (extension_key, version),
    CONSTRAINT ck_sys_extension_pack_four_eyes CHECK (
        approved_by IS NULL OR (verified_by IS NOT NULL AND approved_by <> verified_by AND approved_by <> discovered_by)
    ),
    CONSTRAINT ck_sys_extension_pack_verified_state CHECK (
        lifecycle_state NOT IN ('VERIFIED','APPROVED')
        OR (verified_by IS NOT NULL AND verified_at IS NOT NULL AND verification_evidence_digest ~ '^[0-9a-f]{64}$')
    ),
    CONSTRAINT ck_sys_extension_pack_approved_state CHECK (
        lifecycle_state <> 'APPROVED'
        OR (approved_by IS NOT NULL AND approved_at IS NOT NULL AND approval_receipt_public_id IS NOT NULL)
    ),
    CONSTRAINT ck_sys_extension_pack_revoked_state CHECK (
        lifecycle_state <> 'REVOKED'
        OR (revoked_by IS NOT NULL AND revoked_at IS NOT NULL AND revocation_reason_code IS NOT NULL)
    )
);

CREATE TABLE sys_tenant_extension_installations (
    installation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    extension_version_id BIGINT NOT NULL REFERENCES sys_extension_pack_versions(extension_version_id),
    state VARCHAR(24) NOT NULL CHECK (state IN ('REQUESTED','PENDING_APPROVAL','APPROVED','INSTALLING','INSTALLED_DISABLED','ENABLED','SUSPENDED','FAILED','REVOKED')),
    config_ref VARCHAR(500) NOT NULL,
    config_digest CHAR(64) NOT NULL CHECK (config_digest ~ '^[0-9a-f]{64}$'),
    manifest_digest CHAR(64) NOT NULL CHECK (manifest_digest ~ '^[0-9a-f]{64}$'),
    signature_digest CHAR(64) NOT NULL CHECK (signature_digest ~ '^[0-9a-f]{64}$'),
    compatibility_digest CHAR(64) NOT NULL CHECK (compatibility_digest ~ '^[0-9a-f]{64}$'),
    approval_workflow_key VARCHAR(160) NOT NULL,
    request_digest CHAR(64) NOT NULL CHECK (request_digest ~ '^[0-9a-f]{64}$'),
    requested_by UUID NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_by UUID,
    approved_at TIMESTAMPTZ,
    approval_receipt_public_id UUID,
    installed_by UUID,
    installed_at TIMESTAMPTZ,
    enabled_by UUID,
    enabled_at TIMESTAMPTZ,
    health_check_receipt_public_id UUID,
    suspended_by UUID,
    suspended_at TIMESTAMPTZ,
    revoked_by UUID,
    revoked_at TIMESTAMPTZ,
    failure_code VARCHAR(120),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_tenant_extension_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_tenant_extension_version UNIQUE (tenant_id, extension_version_id),
    CONSTRAINT ck_sys_tenant_extension_four_eyes CHECK (
        approved_by IS NULL OR (approved_by <> requested_by AND (installed_by IS NULL OR installed_by <> approved_by))
    ),
    CONSTRAINT ck_sys_tenant_extension_approved_state CHECK (
        state NOT IN ('APPROVED','INSTALLING','INSTALLED_DISABLED','ENABLED','SUSPENDED')
        OR (approved_by IS NOT NULL AND approved_at IS NOT NULL AND approval_receipt_public_id IS NOT NULL)
    ),
    CONSTRAINT ck_sys_tenant_extension_installed_state CHECK (
        state NOT IN ('INSTALLED_DISABLED','ENABLED','SUSPENDED')
        OR (installed_by IS NOT NULL AND installed_at IS NOT NULL)
    ),
    CONSTRAINT ck_sys_tenant_extension_enabled_state CHECK (
        state <> 'ENABLED' OR (
            enabled_by IS NOT NULL AND enabled_at IS NOT NULL
            AND health_check_receipt_public_id IS NOT NULL
        )
    ),
    CONSTRAINT ck_sys_tenant_extension_terminal_state CHECK (
        (state <> 'FAILED' OR failure_code IS NOT NULL)
        AND (state <> 'REVOKED' OR (revoked_by IS NOT NULL AND revoked_at IS NOT NULL))
    )
);

CREATE OR REPLACE FUNCTION sys_guard_extension_pack_lifecycle() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.lifecycle_state <> 'DISCOVERED' THEN
            RAISE EXCEPTION 'SYS_EXTENSION_PACK_MUST_START_DISCOVERED' USING ERRCODE = '55000';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'SYS_EXTENSION_PACK_VERSION_CANNOT_BE_DELETED' USING ERRCODE = '55000';
    END IF;
    IF OLD.lifecycle_state = 'REVOKED' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'SYS_EXTENSION_PACK_REVOCATION_MONOTONIC' USING ERRCODE = '55000';
    END IF;
    IF OLD.lifecycle_state <> NEW.lifecycle_state AND NOT (
        (OLD.lifecycle_state = 'DISCOVERED' AND NEW.lifecycle_state = 'VERIFIED')
        OR (OLD.lifecycle_state = 'VERIFIED' AND NEW.lifecycle_state = 'APPROVED')
        OR (OLD.lifecycle_state IN ('DISCOVERED','VERIFIED','APPROVED') AND NEW.lifecycle_state = 'REVOKED')
    ) THEN
        RAISE EXCEPTION 'SYS_EXTENSION_PACK_INVALID_STATE_TRANSITION' USING ERRCODE = '55000';
    END IF;
    IF OLD.lifecycle_state IN ('VERIFIED','APPROVED','REVOKED')
       AND ROW(NEW.extension_key, NEW.version, NEW.pack_kind, NEW.manifest,
               NEW.manifest_digest, NEW.signature_key_id, NEW.signature,
               NEW.signature_digest, NEW.compatibility_range, NEW.compatibility_digest,
               NEW.hook_allowlist_digest, NEW.schema_digest, NEW.license_digest,
               NEW.permission_manifest_digest, NEW.discovered_by)
           IS DISTINCT FROM
           ROW(OLD.extension_key, OLD.version, OLD.pack_kind, OLD.manifest,
               OLD.manifest_digest, OLD.signature_key_id, OLD.signature,
               OLD.signature_digest, OLD.compatibility_range, OLD.compatibility_digest,
               OLD.hook_allowlist_digest, OLD.schema_digest, OLD.license_digest,
               OLD.permission_manifest_digest, OLD.discovered_by) THEN
        RAISE EXCEPTION 'SYS_EXTENSION_PACK_VERIFIED_CONTENT_IMMUTABLE' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sys_guard_tenant_extension_lifecycle() RETURNS trigger AS $$
DECLARE pack_state VARCHAR(24);
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'SYS_TENANT_EXTENSION_INSTALLATION_CANNOT_BE_DELETED' USING ERRCODE = '55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.state <> 'REQUESTED' THEN
            RAISE EXCEPTION 'SYS_TENANT_EXTENSION_MUST_START_REQUESTED' USING ERRCODE = '55000';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'UPDATE' THEN
        IF OLD.state = 'REVOKED' AND NEW IS DISTINCT FROM OLD THEN
            RAISE EXCEPTION 'SYS_TENANT_EXTENSION_REVOCATION_MONOTONIC' USING ERRCODE = '55000';
        END IF;
        IF ROW(NEW.tenant_id, NEW.public_id, NEW.extension_version_id, NEW.config_ref,
               NEW.config_digest, NEW.manifest_digest, NEW.signature_digest,
               NEW.compatibility_digest, NEW.approval_workflow_key, NEW.request_digest,
               NEW.requested_by, NEW.requested_at)
           IS DISTINCT FROM
           ROW(OLD.tenant_id, OLD.public_id, OLD.extension_version_id, OLD.config_ref,
               OLD.config_digest, OLD.manifest_digest, OLD.signature_digest,
               OLD.compatibility_digest, OLD.approval_workflow_key, OLD.request_digest,
               OLD.requested_by, OLD.requested_at) THEN
            RAISE EXCEPTION 'SYS_TENANT_EXTENSION_REQUEST_IDENTITY_IMMUTABLE' USING ERRCODE = '55000';
        END IF;
        IF OLD.state <> NEW.state AND NOT (
            (OLD.state = 'REQUESTED' AND NEW.state IN ('PENDING_APPROVAL','FAILED','REVOKED'))
            OR (OLD.state = 'PENDING_APPROVAL' AND NEW.state IN ('APPROVED','FAILED','REVOKED'))
            OR (OLD.state = 'APPROVED' AND NEW.state IN ('INSTALLING','FAILED','REVOKED'))
            OR (OLD.state = 'INSTALLING' AND NEW.state IN ('INSTALLED_DISABLED','FAILED','REVOKED'))
            OR (OLD.state = 'INSTALLED_DISABLED' AND NEW.state IN ('ENABLED','SUSPENDED','REVOKED'))
            OR (OLD.state = 'ENABLED' AND NEW.state IN ('SUSPENDED','REVOKED'))
            OR (OLD.state = 'SUSPENDED' AND NEW.state IN ('ENABLED','REVOKED'))
            OR (OLD.state = 'FAILED' AND NEW.state IN ('REQUESTED','REVOKED'))
        ) THEN
            RAISE EXCEPTION 'SYS_TENANT_EXTENSION_INVALID_STATE_TRANSITION' USING ERRCODE = '55000';
        END IF;
    END IF;
    IF NEW.state IN ('INSTALLING','INSTALLED_DISABLED','ENABLED','SUSPENDED') THEN
        SELECT lifecycle_state INTO pack_state
          FROM sys_extension_pack_versions
         WHERE extension_version_id = NEW.extension_version_id;
        IF pack_state IS DISTINCT FROM 'APPROVED' THEN
            RAISE EXCEPTION 'SYS_EXTENSION_PACK_NOT_APPROVED' USING ERRCODE = '55000';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sys_cascade_extension_pack_revocation() RETURNS trigger AS $$
BEGIN
    IF OLD.lifecycle_state <> 'REVOKED' AND NEW.lifecycle_state = 'REVOKED' THEN
        UPDATE sys_tenant_extension_installations
           SET state = 'REVOKED',
               revoked_by = NEW.revoked_by,
               revoked_at = NEW.revoked_at,
               version = version + 1
         WHERE extension_version_id = NEW.extension_version_id
           AND state <> 'REVOKED';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public;

CREATE TRIGGER tr_sys_extension_pack_lifecycle
    BEFORE INSERT OR UPDATE OR DELETE ON sys_extension_pack_versions
    FOR EACH ROW EXECUTE FUNCTION sys_guard_extension_pack_lifecycle();
CREATE TRIGGER tr_sys_tenant_extension_lifecycle
    BEFORE INSERT OR UPDATE OR DELETE ON sys_tenant_extension_installations
    FOR EACH ROW EXECUTE FUNCTION sys_guard_tenant_extension_lifecycle();
CREATE TRIGGER tr_sys_extension_pack_revoke_cascade
    AFTER UPDATE OF lifecycle_state ON sys_extension_pack_versions
    FOR EACH ROW EXECUTE FUNCTION sys_cascade_extension_pack_revocation();

CREATE TABLE sys_hris_command_receipts (
    command_receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tenant_id BIGINT NOT NULL,
    command_type VARCHAR(100) NOT NULL,
    originating_action VARCHAR(120) NOT NULL,
    subject_principal_public_id UUID NOT NULL,
    population_scope_digest CHAR(64) NOT NULL,
    field_policy_revision BIGINT NOT NULL,
    purpose_code VARCHAR(120) NOT NULL,
    authorization_revision BIGINT NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    request_digest CHAR(64) NOT NULL,
    aggregate_public_id UUID,
    aggregate_revision BIGINT,
    status VARCHAR(24) NOT NULL,
    result_ref VARCHAR(500),
    error_code VARCHAR(80),
    correlation_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_sys_hris_command_receipt_public UNIQUE (tenant_id, public_id),
    CONSTRAINT uq_sys_hris_command_receipt_idem UNIQUE (tenant_id, subject_principal_public_id, originating_action, idempotency_key),
    CONSTRAINT ck_sys_hris_command_receipt_revisions CHECK (field_policy_revision > 0 AND authorization_revision > 0),
    CONSTRAINT ck_sys_hris_command_receipt_population_digest CHECK (population_scope_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_sys_hris_command_receipt_request_digest CHECK (request_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_sys_hris_command_receipt_status CHECK (status IN ('ACCEPTED','RUNNING','SUCCEEDED','REJECTED','FAILED','RESULT_UNKNOWN'))
);

CREATE OR REPLACE FUNCTION sys_hris_guard_command_receipt_seal()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Platform HRIS command receipt cannot be deleted';
    END IF;
    IF ROW(NEW.tenant_id, NEW.command_type, NEW.originating_action,
           NEW.subject_principal_public_id, NEW.population_scope_digest,
           NEW.field_policy_revision, NEW.purpose_code,
           NEW.authorization_revision, NEW.idempotency_key,
           NEW.request_digest, NEW.correlation_id)
       IS DISTINCT FROM
       ROW(OLD.tenant_id, OLD.command_type, OLD.originating_action,
           OLD.subject_principal_public_id, OLD.population_scope_digest,
           OLD.field_policy_revision, OLD.purpose_code,
           OLD.authorization_revision, OLD.idempotency_key,
           OLD.request_digest, OLD.correlation_id) THEN
        RAISE EXCEPTION 'Platform HRIS command receipt authorization and idempotency seal is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_sys_hris_command_receipt_seal
    BEFORE UPDATE OR DELETE ON sys_hris_command_receipts
    FOR EACH ROW EXECUTE FUNCTION sys_hris_guard_command_receipt_seal();

-- Service-local outbox, inbox and audit tables reuse the dwp-core Platform
-- migration baseline. The HRIS command receipt is owner-local because its
-- originating authorization and caller-bound idempotency context must be immutable.
-- Runtime roles are NOINHERIT, NOSUPERUSER and NOBYPASSRLS. The transaction
-- interceptor must SET LOCAL dwp.tenant_id after verified tenant resolution.
DO $$
DECLARE target_table TEXT;
BEGIN
  FOREACH target_table IN ARRAY ARRAY[
    'sys_hris_config_sets',
    'sys_hris_config_versions',
    'sys_hris_config_evaluations',
    'sys_automation_definitions',
    'sys_automation_versions',
    'sys_automation_schedules',
    'sys_automation_runs',
    'sys_automation_run_attempts',
    'sys_automation_run_items',
    'sys_automation_item_attempts',
    'sys_automation_run_checkpoints',
    'sys_connector_definitions',
    'sys_connector_mapping_versions',
    'sys_connector_executions',
    'sys_connector_execution_items',
    'sys_connector_execution_attempts',
    'sys_hris_home_contributions',
    'sys_hris_explorer_preferences',
    'sys_hris_explorer_favorites',
    'sys_hris_explorer_recents',
    'sys_controlled_file_transfers',
    'sys_operational_exception_projections',
    'sys_tenant_extension_installations',
    'sys_hris_command_receipts'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', target_table);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', target_table);
    EXECUTE format(
      'CREATE POLICY %I ON %I USING (tenant_id = NULLIF(current_setting(''dwp.tenant_id'', true), '''')::BIGINT) WITH CHECK (tenant_id = NULLIF(current_setting(''dwp.tenant_id'', true), '''')::BIGINT)',
      target_table || '_tenant_policy', target_table
    );
  END LOOP;
END $$;

COMMIT;
